Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2018-09, with the labels that each got.

#1455 typo fixes
  docs/deployment/how-to-configure-the-clickonce-trust-prompt-behavior.md
Labels: do-not-merge

#1446 Fix minor code example discrepancy: csharp_style_expression_bodied_indexers
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge

#1272 Add documentation for unit testing in other scenarios
  docs/javascript/develop-javascript-code-without-solutions-projects.md
  docs/javascript/unit-testing-javascript-with-visual-studio.md
Labels: change sent to author, do-not-merge

#1516 Update specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md
  docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md
Labels: change sent to author, do-not-merge

#1517 Adding ResultsDirectory, Port and ParentProcessId
  docs/test/vstest-console-options.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1521 Improved formatting in Writing a T4 Text Template
  docs/modeling/writing-a-t4-text-template.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1532 Fixing reference include in example
  docs/vs-2015/msbuild/msbuild-inline-tasks.md
Labels: "visual-studio-dev14"/prod, change sent to author, ready-to-merge

#1539 fix 1538 example run settings file so it can be debugged
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1554 Fix 2 XAML copy mistakes
  docs/vs-2015/designers/walkthrough-my-first-wpf-desktop-application2.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1553 Fix link title (metapackages instead of metadata)
  docs/msbuild/what-s-new-in-msbuild-15-0.md
Labels: change sent to author, ready-to-merge

#1565 Sample code has redundant '}'
  docs/extensibility/changing-the-appearance-of-a-command.md
Labels: change sent to author, ready-to-merge

#1547 Add documentation for the _Field_z_ annotation
  docs/code-quality/annotating-structs-and-classes.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1548 Delete text where it doesn't apply
  docs/code-quality/annotating-structs-and-classes.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1545 Document WriteOnlyWhenDifferent parameter
  docs/msbuild/writelinestofile-task.md
Labels: area - msbuild, change sent to author, ready-to-merge

#1535 MSBuild: Remove works in evaluation
  docs/msbuild/msbuild-items.md
Labels: area - msbuild, change sent to author, ready-to-merge

#1591 MSBuild: Mention escaping item wildcards
  docs/msbuild/how-to-escape-special-characters-in-msbuild.md
  docs/msbuild/msbuild-items.md
Labels: change sent to author, ready-to-merge
