Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2018-05, with the labels that each got.

#848 Add steps using modern commanding
  docs/extensibility/walkthrough-using-a-shortcut-key-with-an-editor-extension.md
Labels: Change sent to author, ready-to-merge

#880 Update sample-project-for-creating-unit-tests.md
  docs/test/sample-project-for-creating-unit-tests.md
Labels: Change sent to author, do-not-merge

#885 Update C26472.md
  docs/code-quality/C26472.md
Labels: Change sent to author, do-not-merge

#890 Resolve syncing conflicts from FromPrivateLiveToMaster to master
  .openpublishing.redirection.json
  docs/TOC.md
  docs/code-quality/demo-sample.md
  docs/ide/common-quick-actions.md
  docs/ide/find-and-fix-code-errors.md
  docs/ide/getting-started-with-debugging-in-visual-studio.md
  docs/ide/index-writing-code.md
  docs/ide/media/cpp-code-analysis-warning.png
  docs/ide/media/quick-actions-options.png
  docs/ide/not-in-toc/default.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: Change sent to author, ready-to-merge

#887 MSBuild: items can be used in UsingTask
  docs/msbuild/usingtask-element-msbuild.md
Labels: Change sent to author, ready-to-merge

#896 Update web-publish-options.md
  docs/ide/not-in-toc/web-publish-options.md
Labels: Change sent to author, ready-to-merge

#895 Remove spurious space from directory path
  docs/install/set-defaults-for-enterprise-deployments.md
Labels: Change sent to author, do-not-merge

#891 docs/extensibility -- fix typo
  docs/extensibility/inside-the-editor.md
Labels: Change sent to author, ready-to-merge

#892 fix typo in extensibility
  docs/extensibility/commandplacement-element.md
Labels: Change sent to author, ready-to-merge

#907 Update command-line-parameter-examples.md
  docs/install/command-line-parameter-examples.md
Labels: Change sent to author, ready-to-merge

#912 a typo in one of the headings
  docs/designers/working-with-elements-in-xaml-designer.md
Labels: Change sent to author, do-not-merge

#909 Update Visual Studio Tools for Unity change log for 3.7 and 3.7.0.1
  docs/cross-platform/change-log-visual-studio-tools-for-unity.md
Labels: Change sent to author, do-not-merge

#932 Fixed: A typo in one of registry keys
  docs/debugger/debug-using-the-just-in-time-debugger.md
Labels: Change sent to author, do-not-merge

#938 a correction of an expression about ZIndex
  docs/designers/working-with-elements-in-xaml-designer.md
Labels: Change sent to author, do-not-merge

#926 Reopen documents on solution load option
  docs/ide/reference/projects-and-solutions-options-dialog-box.md
Labels: change sent to author, do-not-merge

#950 fix: Use relative markdown links in subscription folder
  subscriptions/cloud-admin.md
  subscriptions/handle-expired-license.md
  subscriptions/leave-vsde.md
  subscriptions/personal-email-sign-ins.md
  subscriptions/resend-assignment-email.md
  subscriptions/software-download-list.md
  subscriptions/subscriber-benefits.md
  subscriptions/using-the-subscriber-portal.md
  subscriptions/vlsc-admin-faq.md
  subscriptions/volume-license-admins.md
  subscriptions/vs-azure.md
  subscriptions/vs-license-terms.md
Labels: change sent to author, ready-to-merge

#954 Update c26444.md
  docs/code-quality/c26444.md
Labels: change sent to author, do-not-merge

#971 Update foreach-method-map for understandability
  scripting-docs/javascript/reference/foreach-method-map-javascript.md
Labels: change sent to author, ready-to-merge

#972 Fix link formatting
  docs/test/writing-unit-tests-for-c-cpp.md
Labels: change sent to author, do-not-merge

#975 remove napa references
  docs/vsto/office-and-sharepoint-development-in-visual-studio.md
Labels: change sent to author, ready-to-merge

#977 Update NUnit Test Generator Extension link for VS 2017
  docs/test/generate-unit-tests-for-your-code-with-intellitest.md
Labels: change sent to author, do-not-merge

#978 Typo: write -> right
  docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md
Labels: change sent to author, do-not-merge

#969 Fix: piracy/activation.mspx was a 404 page
  subscriptions/vs-license-terms.md
Labels: change sent to author, do-not-merge

#988 chore: cross-platform relative link fixes
  docs/cross-platform/learn-about-mobile-development-with-xamarin.md
  docs/cross-platform/visual-studio-and-xamarin.md
Labels: change sent to author, do-not-merge

#935 chore: Update mac links so they work on GH
  mac/activation.md
  mac/azure-workload.md
  mac/compiling-and-building.md
  mac/ide-tour.md
  mac/index.md
  mac/install-preview.md
  mac/installation.md
  mac/keyboard-shortcuts.md
  mac/managing-references-in-a-project.md
  mac/projects-and-solutions.md
  mac/setup-vsmac-tools-unity.md
  mac/unity-tools.md
  mac/using-vsmac-tools-unity.md
  mac/version-control.md
  mac/working-with-subversion.md
  mac/workloads.md
Labels: change sent to author, do-not-merge

#957 Update remarks
  docs/extensibility/providedefaultname-element-visual-studio-templates.md
Labels: Area - extensibility, change sent to author, ready-to-merge

#1014 Method naming casing wrong (minor typo)
  docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md
Labels: change sent to author, do-not-merge

#1016 fix indentation and casing of Source Link bullet
  docs/debugger/general-debugging-options-dialog-box.md
Labels: change sent to author, do-not-merge

#1023 Update how-to-reference-the-name-or-location-of-the-project-file.md
  docs/msbuild/how-to-reference-the-name-or-location-of-the-project-file.md
Labels: change sent to author, do-not-merge

#1006 Minor edit; missing word
  docs/profiling/beginners-guide-to-performance-profiling.md
Labels: Area - profiling, change sent to author, do-not-merge

#1013 Critical differentiation between Self CPU and Total CPU
  docs/profiling/cpu-usage.md
Labels: Area - profiling, change sent to author, ready-to-merge

#1049 M26805: Possible incorrect term: "Django Web Project" vs. "Blank Djan…
  docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md
Labels: ready-to-merge

#1042 Explain "nq"
  docs/debugger/using-the-debuggerdisplay-attribute.md
Labels: change sent to author, ready-to-merge

#1039 Document dotnet_style_readonly_field
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge

#1040 Clarify wording
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge

#1029 typo: xaspx -> aspx file extension
  docs/deployment/creating-bootstrapper-packages.md
Labels: change sent to author, ready-to-merge

#1030 typo: Missing aspx extension on link
  docs/deployment/trusted-application-deployment-overview.md
Labels: change sent to author, ready-to-merge

#1064 Couple of typos
  mac/index.md
Labels: change sent to author, do-not-merge
