Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2018-06, with the labels that each got.

#1073 Update automating-excel-by-using-extended-objects.md
  docs/vsto/automating-excel-by-using-extended-objects.md
Labels: change sent to author, do-not-merge

#1075 Fixes #1074 - updated vs-alternate-identity.md
  subscriptions/vs-alternate-identity.md
Labels: change sent to author, ready-to-merge

#1082 Correct the criteria for `BeforeTargets`
  docs/msbuild/target-build-order.md
Labels: change sent to author, ready-to-merge

#1077 Just updating to the latest Visual Studio folder under My Documents
  docs/debugger/just-my-code.md
Labels: change sent to author, ready-to-merge

#1095 Fix typo
  docs/extensibility/changing-the-text-of-a-menu-command.md
Labels: change sent to author, ready-to-merge

#1096 Fix for xml escaping
  docs/extensibility/internals/guids-and-ids-of-visual-studio-commands.md
Labels: change sent to author, ready-to-merge

#1105 fix: Remove md extension from absolute links
  scripting-docs/javascript/reference/debug-object-javascript.md
  scripting-docs/javascript/reference/javascript-reference.md
Labels: change sent to author, ready-to-merge

#1110 fix: Remve aspx from DotNet link
  docs/debugger/project-settings-for-a-visual-basic-debug-configuration.md
Labels: change sent to author, ready-to-merge

#1113 fix: remove .md from UWP link
  docs/debugger/debug-installed-app-package.md
Labels: change sent to author, ready-to-merge

#1108 fix: Remove extension on Mac install link
  docs/cross-platform/setup-and-install.md
Labels: change sent to author, do-not-merge

#1111 fix: Update python flask sample repo
  docs/python/learn-flask-visual-studio-step-04-full-flask-project-template.md
Labels: change sent to author, do-not-merge

#1112 fix: CPP link fixups
  docs/code-quality/using-rule-sets-to-specify-the-cpp-rules-to-run.md
  docs/debugger/c-cpp-assertions.md
  docs/debugger/debug-multithreaded-applications-in-visual-studio.md
  docs/debugger/debugging-gpu-code.md
  docs/debugger/mfc-debugging-techniques.md
  docs/debugger/using-the-tasks-window.md
  docs/debugger/walkthrough-debugging-a-multithreaded-application.md
Labels: change sent to author, ready-to-merge

#1116 Change three to four (the correct files count)
  docs/extensibility/creating-an-extension-with-an-editor-item-template.md
Labels: change sent to author, ready-to-merge

#1114 Fix repetitive phrasing in docs
  docs/python/installing-python-support-in-visual-studio.md
Labels: change sent to author, ready-to-merge

#1115 fix: overlooked language
  mac/customizing-the-ide.md
Labels: change sent to author, do-not-merge

#1109 fix: GoogleTest link casing
  docs/test/how-to-use-google-test-for-cpp.md
  docs/test/writing-unit-tests-for-c-cpp.md
Labels: change sent to author, do-not-merge

#1107 fix: tfsconfig-cmd links
  docs/ide/codeindex-command.md
  docs/ide/find-code-changes-and-other-history-with-codelens.md
Labels: change sent to author, do-not-merge

#1103 Fix subscription links
  subscriptions/using-admin-portal.md
  subscriptions/vlsc-admin-faq.md
Labels: change sent to author, do-not-merge

#1089 Update ms.date in target-build-order.md
  docs/msbuild/target-build-order.md
Labels: change sent to author, ready-to-merge

#1128 spelling/grammar fix
  docs/extensibility/language-server-protocol.md
Labels: change sent to author, ready-to-merge

#1133 Added the missing "i" for "This"
  docs/debugger/run-windows-store-apps-on-a-remote-machine.md
Labels: change sent to author, ready-to-merge

#1137 Update unit-test-basics.md
  docs/test/unit-test-basics.md
Labels: change sent to author, do-not-merge

#1139 Improve minor things in scripting-docs/jswinrt/handling-windows-runtime-events-in-javascript.md
  scripting-docs/jswinrt/handling-windows-runtime-events-in-javascript.md
Labels: change sent to author, ready-to-merge

#1142 Clarify how event handlers differs between Javascript and .NET/C++
  scripting-docs/jswinrt/handling-windows-runtime-events-in-javascript.md
Labels: change sent to author, ready-to-merge

#1131 Updated to include MSBuildProjectDirectory
  docs/msbuild/how-to-reference-the-name-or-location-of-the-project-file.md
Labels: change sent to author, do-not-merge

#1170 Added missing word "be"
  docs/modeling/run-time-text-generation-with-t4-text-templates.md
Labels: change sent to author, do-not-merge

#1162 Document XmlPoke Namespaces parameter
  docs/msbuild/xmlpoke-task.md
Labels: change sent to author, ready-to-merge

#1172 Fix typo in "design time" section
  docs/modeling/code-generation-and-t4-text-templates.md
Labels: change sent to author, do-not-merge

#1175 Fix typo
  docs/test/live-unit-testing.md
Labels: ready-to-merge

#1167 Fix the fileToFile sample
  docs/ide/file-nesting-solution-explorer.md
Labels: change sent to author, do-not-merge

#1180 Minor typo in creation of "__init__.py"
  docs/python/learn-flask-visual-studio-step-02-create-app.md
Labels: change sent to author, ready-to-merge
