Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2018-11, with the labels that each got.

#1797 Adds -restore switch to MSBuild CLI
  docs/msbuild/msbuild-command-line-reference.md
Labels: change sent to author, ready-to-merge

#1799 T4 Code Snippets Exception Fix
  docs/modeling/design-time-code-generation-by-using-t4-text-templates.md
  docs/modeling/t4-template-directive.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1803 Fix typo in .editorconfig code style settings reference
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1809 typo: occurance -> occurrence
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifclaimsbasedauthorization/cs/webapplication/claims.aspx.cs
Labels: change sent to author, do-not-merge

#1810 typo: occuring -> occurring
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/basicmanipulation/csharp/mainwindow.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/basicmanipulation/visualbasic/mainwindow.xaml.vb
Labels: change sent to author, do-not-merge

#1811 typo: begining -> beginning
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/FlowDocumentSnippets/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/ListSnippets/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/SpanSnippets/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/FlowDocumentSnippets/visualbasic/window1.xaml.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/ListSnippets/visualbasic/window1.xaml.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/SpanSnippets/visualbasic/window1.xaml.vb
Labels: change sent to author, do-not-merge

#1812 typo: colleciton -> collection
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifcustomtokenst/cs/simplewebtoken/simplewebtokenhandler.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifcustomtokensts/cs/simplewebtoken/simplewebtokenhandler.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifrccustomtoken/cs/simplewebtoken/simplewebtokenhandler.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/FlowDocumentSnippets/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/FlowDocumentSnippets/visualbasic/window1.xaml.vb
Labels: change sent to author, do-not-merge

#1813 typo: independend -> independent
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/FlowDocumentSnippets/CSharp/Window1.xaml
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/FlowDocumentSnippets/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/FlowDocumentSnippets/visualbasic/window1.xaml
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/FlowDocumentSnippets/visualbasic/window1.xaml.vb
Labels: change sent to author, do-not-merge

#1814 typo: ththis -> this
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifcustomtokenst/cs/simplewebtoken/simplewebtokenhandler.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifcustomtokensts/cs/simplewebtoken/simplewebtokenhandler.cs
Labels: change sent to author, do-not-merge

#1819 fixed grammar error
  docs/vs-2015/test/isolating-code-under-test-with-microsoft-fakes.md
Labels: do-not-merge

#1820 typo: Properity -> Property
  docs/vs-2015/snippets/cpp/VS_Snippets_Misc/NVC_MFC_DrawClient/cpp/propset.cpp
Labels: change sent to author, do-not-merge

#1821 typo: Double word "of"
  docs/vs-2015/snippets/cpp/VS_Snippets_Misc/NVC_MFC_DrawClient/cpp/propset.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/WordXmlSerialize/WordXmlSerializer.cs
Labels: change sent to author, do-not-merge

#1822 typo: Double word "any"
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/tpldataflow_overview/cs/program.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/tpldataflow_overview/vb/program.vb
Labels: change sent to author, do-not-merge

#1828 typo: Double word "from"
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.RichTextBoxGetLine/CPP/form1.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.RichTextBoxGetLine/CS/form1.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.RichTextBoxGetLine/VB/form1.vb
Labels: do-not-merge

#1829 typo: Double word "continue"
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlLexicalAnalyzer.cs
Labels: change sent to author, do-not-merge

#1840 typo: explicitely -> explicitly
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/StackPanel_snip/CS/OrientationExample.xaml
Labels: change sent to author, do-not-merge

#1842 typo: agressive -> aggressive
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1843 typo: succesful -> successful
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifwsfam/cs/webapplication1/global.asax.cs
Labels: change sent to author, do-not-merge

#1862 typo: propeties -> properties
  docs/extensibility/getting-project-properties.md
  docs/vs-2015/extensibility/getting-project-properties.md
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind client/cs/customeraddress.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind client/vb/customeraddress.vb
Labels: do-not-merge

#1861 typo: mediun -> median
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1860 typo: rrepresentation -> representation
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1859 typo: csll -> css
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: do-not-merge

#1858 typo: interpreation -> interpretation
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1857 typo: valkue -> value
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1856 typo: jsut -> just
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1855 typo: alrady -> already
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1854 typo: inseerted -> inserted
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1853 typo: tbale -> table
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1852 typo: insuccessful -> unsuccessful
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1851 typo: analisys -> analysis
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1850 typo: iteratimg -> iterating
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1849 typo: wneh -> when
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1848 typo: reprsenting -> representing
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1847 typo: dependeing -> depending
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge

#1841 Fixed C# code sample so it compiles and works
  docs/extensibility/ux-guidelines/colors-and-styling-for-visual-studio.md
Labels: change sent to author, do-not-merge

#1845 Fix typo - VB should be C#
  docs/extensibility/creating-an-options-page.md
Labels: change sent to author, ready-to-merge

#1867 typo: certficate -> certificate
  docs/deployment/how-to-publish-a-project-that-has-a-specific-locale.md
  docs/vs-2015/deployment/how-to-publish-a-project-that-has-a-specific-locale.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1869 typo: implmentation -> implementation
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/IServiceContainerExample/CPP/serviceform.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/IServiceContainerExample/CS/serviceform.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/IServiceContainerExample/VB/serviceform.vb
Labels: change sent to author, do-not-merge

#1879 Typo in XML example
  docs/ide/how-to-manually-create-web-templates.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1872 typo: paramter -> parameter
  docs/extensibility/debugger/getting-a-port.md
  docs/extensibility/debugger/reference/idebugcomplussymbolprovider2-gettypesbyname.md
  docs/extensibility/debugger/registering-the-program.md
  docs/test/fix-non-detectable-dynamic-parameters-in-a-web-performance-test.md
  docs/vs-2015/extensibility/debugger/getting-a-port.md
  docs/vs-2015/extensibility/debugger/reference/idebugcomplussymbolprovider2-gettypesbyname.md
  docs/vs-2015/extensibility/debugger/registering-the-program.md
  docs/vs-2015/msbuild/lc-task.md
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlLexicalAnalyzer.cs
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1873 Try to make role of devenv.com clearer
  docs/ide/reference/devenv-command-line-switches.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1874 Fix incorrect command line example
  docs/ide/reference/devenv-command-line-switches.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1875 Format example command lines
  docs/ide/reference/devenv-command-line-switches.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1886 Fix error in extending-the-output-window.md
  docs/extensibility/extending-the-output-window.md
Labels: change sent to author, ready-to-merge

#1888 typo: vaule -> value
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/WordXmlSerialize/WordXmlReader.cs
Labels: change sent to author, do-not-merge

#1890 typo: Scaleable -> Scalable
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/Control_Scale1/CPP/control_scale1.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/Control_Scale1/CS/control_scale1.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/Control_Scale1/VB/control_scale1.vb
Labels: change sent to author, do-not-merge

#1891 typo: Langauge -> Language
  docs/extensibility/internals/vsct-compiler-command-line-flags.md
  docs/extensibility/vsix-language-pack-schema-2-0-reference.md
  docs/extensibility/workspace-language-services.md
  docs/vs-2015/extensibility/internals/vsct-compiler-command-line-flags.md
Labels: do-not-merge

#1892 typo: exection -> execution
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind client/cs/source.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind client/vb/source.vb
Labels: change sent to author, do-not-merge

#1893 typo: specfied -> specified
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/WordXmlSerialize/WordXmlReader.cs
Labels: change sent to author, do-not-merge

#1894 typo: folowed -> followed
  docs/extensibility/internals/vsct-compiler-command-line-flags.md
  docs/vs-2015/extensibility/internals/vsct-compiler-command-line-flags.md
Labels: do-not-merge

#1895 typo: Indcate -> Indicate
  docs/extensibility/internals/vsct-compiler-command-line-flags.md
  docs/vs-2015/extensibility/internals/vsct-compiler-command-line-flags.md
Labels: do-not-merge

#1896 typo: dependancy -> dependency
  docs/extensibility/internals/vsct-compiler-command-line-flags.md
  docs/vs-2015/extensibility/internals/vsct-compiler-command-line-flags.md
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/ImageButton.cs
Labels: do-not-merge

#1889 typo: convertion -> conversion
  docs/vs-2015/snippets/cpp/VS_Snippets_Misc/astoria northwind service/astoriasnippetscs/sourcetest.cs
  docs/vs-2015/snippets/cpp/VS_Snippets_Misc/astoria northwind service/astoriasnippetsvb/sourcevbtest.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind client/cs/source.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind service/astoriasnippetscs/sourcetest.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind service/astoriasnippetsvb/sourcevbtest.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/WordXmlSerialize/WordXmlReader.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind client/vb/source.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind service/astoriasnippetscs/sourcetest.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind service/astoriasnippetsvb/sourcevbtest.cs
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1899 typo: tempalte-> template
  docs/vs-2015/extensibility/internals/making-commands-available.md
Labels: do-not-merge

#1901 typo: defintion -> definition
  docs/azure/vs-azure-tools-resource-groups-ci.md
  docs/vs-2015/azure/vs-azure-tools-resource-groups-ci.md
  docs/vs-2015/debugger/diagnose-problems-after-deployment.md
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/XpsReadWriteSign/CSharp/SignatureDefinitionsAndSigning.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/XpsReadWriteSign/CSharp/SignatureDialog.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/XpsReadWriteSign/visualbasic/signaturedefinitionsandsigning.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/XpsReadWriteSign/visualbasic/signaturedialog.xaml.vb
Labels: azure-resource-manager/svc, change sent to author, do-not-merge, visual-studio-dev14/prod

#1900 typo: utilites -> utilities
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/XpsReadWriteSign/CSharp/SignatureDefinitionsAndSigning.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/XpsReadWriteSign/CSharp/SignatureDialog.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/XpsReadWriteSign/visualbasic/signaturedefinitionsandsigning.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/XpsReadWriteSign/visualbasic/signaturedialog.xaml.vb
Labels: change sent to author, do-not-merge

#1905 Fix "Find component IDs" anchor reference
  docs/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017.md
Labels: change sent to author, ready-to-merge

#1919 Fix NuGet walkthrough typo
  mac/nuget-walkthrough.md
Labels: change sent to author, ready-to-merge

#1912 typo: accomodate -> accommodate
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.ComboBoxOwnerDrawn/CPP/form1.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.ComboBoxOwnerDrawn/CS/form1.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.ComboBoxOwnerDrawn/VB/form1.vb
Labels: change sent to author, do-not-merge

#1923 typo: demonstates -> demonstrates
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/Classic ControlBindingsCollection Example/CPP/source.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/Classic ControlBindingsCollection Example/CS/source.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/OutlineTextControlViewer/CSharp/Window1.xaml
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/Classic ControlBindingsCollection Example/VB/source.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.FormExample/VB/form1.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/OutlineTextControlViewer/visualbasic/window1.xaml
Labels: change sent to author, do-not-merge

#1924 typo: additonal -> additional
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/lazy/cs/cs_lazycodefile.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifissuernameregistry/cs/mvcwepapp/web.config
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/wifissuernameregistry/cs/passivests/web.config
Labels: change sent to author, do-not-merge

#1917 typo: occure* -> occurre*
  docs/ide/reference/introduce-local-variable.md
  docs/profiling/understanding-resource-contention-data-values.md
  docs/test/code-a-custom-validation-rule-for-a-web-performance-test.md
  docs/vs-2015/profiling/understanding-resource-contention-data-values.md
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridView._Virtual/CPP/virtual.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Misc/astoria northwind client/cs/program.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_VBCSharp/toolwindowsearch/cs/testtoolwindowsearch_integrationtests/integrationtest library/dialogboxpurger.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.BindingSourceMultipleControls/CS/Form1.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.CurrencyManagerReset/CS/Form1.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/FindText/CSharp/SearchWindow.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Misc/astoria northwind client/vb/customerorderscustom2.xaml.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.BindingSourceMultipleControls/VB/Form1.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.CurrencyManagerReset/VB/Form1.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/FindText/VisualBasic/SearchWindow.vb
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1913 typo: publically -> publicly
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/TreeViewFindTVI/CSharp/MainWindow.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/TreeViewFindTVI/VisualBasic/MainWindow.xaml.vb
Labels: change sent to author, do-not-merge

#1916 typo: maintance -> maintenance
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridView._Virtual/CPP/virtual.cpp
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewTrinaryVirtualCheckBox/cpp/trivaluevirtualcheckbox.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridView._Virtual/CS/virtual.cs
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewTrinaryVirtualCheckBox/CS/trivaluevirtualcheckbox.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridView._Virtual/VB/virtual.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/System.Windows.Forms.DataGridViewTrinaryVirtualCheckBox/VB/trivaluevirtualcheckbox.vb
Labels: change sent to author, do-not-merge

#1920 typo: everytime -> every time
  docs/vs-2015/snippets/cpp/VS_Snippets_Winforms/Control.Layout/CPP/layout.cpp
  docs/vs-2015/snippets/csharp/VS_Snippets_Winforms/Control.Layout/CS/layout.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Winforms/Control.Layout/VB/layout.vb
Labels: change sent to author, do-not-merge

#1921 typo: libary -> library
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/CommandLibrarySnippets/CSharp/CommandLibrarySnippets.csproj
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/CommandLibrarySnippets/CSharp/Window1.xaml
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/CommandLibrarySnippets/visualbasic/commandlibrarysnippets.vbproj
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/CommandLibrarySnippets/visualbasic/window1.xaml
Labels: change sent to author, do-not-merge

#1931 typo: ouput -> output
  docs/modeling/code-generation-in-a-build-process.md
  docs/vs-2015/modeling/code-generation-in-a-build-process.md
  docs/vs-2015/msbuild/vbc-task.md
  docs/vs-2015/snippets/cpp/VS_Snippets_Misc/NVC_MFC_StateCollection/cpp/Snippets.txt
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentStructure/CSharp/Window1.xaml.cs
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/DocumentStructure/visualbasic/window1.xaml.vb
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1918 chore: Deduplicate code of conduct text
  README.md
Labels: change sent to author, do-not-merge

#1939 typo: paramater -> parameter
  docs/profiling/vsperfaspnetcmd.md
  docs/vs-2015/data-tools/create-a-windows-form-to-search-data.md
  docs/vs-2015/profiling/vsperfaspnetcmd.md
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/DocumentSerialize/CSharp/HtmlXmlConverter/HtmlToXamlConverter.cs
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1940 typo: udpate -> update
  docs/vs-2015/data-tools/save-data-back-to-the-database.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1944 fix error
  subscriptions/vs-pluralsight.md
Labels: change sent to author, do-not-merge, vs-subscription/prod

#1936 Update the version section for VS2017
  docs/extensibility/vsix-extension-schema-2-0-reference.md
Labels: change sent to author, ready-to-merge

#1910 typo: overrided -> override
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/StrokeSnippets/VisualBasic/CustomRenderedStroke.vb
  docs/vs-2015/snippets/visualbasic/VS_Snippets_Wpf/StrokeSnippets/VisualBasic/MyStroke.vb
Labels: change sent to author, do-not-merge

#1948 typo: Double word "that"
  docs/profiling/threads-view-parallel-performance.md
Labels: change sent to author, ready-to-merge

#1951 typo: exmaple -> example
  docs/vs-2015/snippets/csharp/VS_Snippets_Wpf/GeometrySample_snip_XAML/CS/SampleViewer.xaml
Labels: change sent to author, do-not-merge

#1949 typo: paramteer -> parameter
  docs/code-quality/mixed-minimum-rules-rule-set.md
  docs/code-quality/native-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/mixed-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/mixed-recommended-rules-rule-set.md
  docs/vs-2015/code-quality/native-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/native-recommended-rules-rule-set.md
  docs/vs-2015/test/analyze-cpp-code-quality-of-store-apps-using-visual-studio-static-code-analysis.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1950 typo: Argumen -> Argument
  docs/code-quality/mixed-minimum-rules-rule-set.md
  docs/code-quality/native-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/mixed-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/mixed-recommended-rules-rule-set.md
  docs/vs-2015/code-quality/native-minimum-rules-rule-set.md
  docs/vs-2015/code-quality/native-recommended-rules-rule-set.md
  docs/vs-2015/test/analyze-cpp-code-quality-of-store-apps-using-visual-studio-static-code-analysis.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1961 Correct typo: Diagnosis => Diagnostics
  docs/code-quality/code-analysis-for-managed-code-overview.md
  docs/vs-2015/code-quality/code-analysis-for-managed-code-overview.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#1960 Update C26426.md
  docs/code-quality/C26426.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1964 Update t4-template-directive.md
  docs/modeling/t4-template-directive.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#1971 chore: Code formatting how-to-publish-a-wpf-application-with-visual-styles-enabled
  docs/deployment/how-to-publish-a-wpf-application-with-visual-styles-enabled.md
Labels: change sent to author, ready-to-merge
