Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-08, with the labels that each got.

#3712 Fix git push error for protected CLA branch
  docs/extensibility/adding-an-lsp-extension.md
  docs/ide/reference/add-null-checks-for-all-parameters.md
  docs/ide/reference/change-method-signature.md
  docs/ide/reference/media/add-null-checks-for-all-parameters.png
  docs/ide/reference/media/add-null-checks-for-all.png
  docs/test/improve-code-quality.md
  docs/test/media/vs-2019/test-explorer-16-2.png
  docs/test/media/vs-2019/test-explorer-columns-16-2.png
  docs/test/media/vs-2019/test-explorer-detail.png
  docs/test/media/vs-2019/test-explorer-filter-column-16-2.png
  docs/test/media/vs-2019/test-explorer-groupby-162.png
  docs/test/media/vs-2019/test-explorer-groupby-state-16-2.png
  docs/test/media/vs-2019/test-explorer-playlist-16-2.png
  docs/test/media/vs-2019/test-explorer-playlist-tab-16-2.png
  docs/test/media/vs-2019/test-explorer-search-filter-16-2.png
  docs/test/media/vs-2019/test-explorer-sort-column-16-2.png
  docs/test/media/vs-2019/test-explorer-toolbar-16-2.png
  docs/test/media/vs-2019/test-explorer-toolbar-diagram-16-2.png
  docs/test/run-unit-tests-with-test-explorer.md
  docs/toc.yml
Labels: do-not-merge

#3720 Fix git push error for protected CLA branch
  docs/ide/quickstart-python.md
  docs/ide/reference/accessibility-tips-and-tricks.md
  docs/ide/reference/convert-switch-statement-to-switch-expression.md
  docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md
  docs/vs-2015/code-quality/c6029.md
  docs/vs-2015/code-quality/c6277.md
  docs/vs-2015/code-quality/code-analysis-for-c-cpp-overview.md
  docs/vs-2015/code-quality/code-analysis-for-managed-code-overview.md
  docs/vs-2015/cross-platform/application-lifecycle-management-alm-with-unity-apps.md
  docs/vs-2015/cross-platform/application-lifecycle-management-alm-with-xamarin-apps.md
  docs/vs-2015/ide/compiling-and-building-in-visual-studio.md
  docs/vs-2015/ide/reference/resources-for-designing-accessible-applications.md
  docs/vs-2015/ide/tips-and-tricks-for-visual-studio.md
  docs/vs-2015/modeling/scenario-change-your-design-using-visualization-and-modeling.md
  docs/vs-2015/modeling/validate-code-with-layer-diagrams.md
  docs/vs-2015/msbuild/msbuild.md
  docs/vs-2015/msbuild/updatemanifestforbrowserapplication-task.md
  docs/vsto/walkthrough-binding-to-data-from-a-service-in-a-vsto-add-in-project.md
  mac/TOC.md
  mac/media/samples/arkit.png
  mac/media/samples/controls.png
  mac/media/samples/coremlazure.png
  mac/media/samples/crm.png
  mac/media/samples/flash.png
  mac/media/samples/gps.png
  mac/media/samples/hellomac.png
  mac/media/samples/images.png
  mac/media/samples/mapkit.png
  mac/media/samples/material-design.png
  mac/media/samples/myshoppe.png
  mac/media/samples/sample-download.svg
  mac/media/samples/todo-dotnet.png
  mac/media/samples/todo.png
  mac/samples.yml
Labels: do-not-merge, review-team-triage

#3395 Add .NET Core and Standard JS Tests Documentation
  docs/javascript/unit-testing-javascript-with-visual-studio.md
Labels: assessing (C&L), change sent to author, ready-to-merge

#3734 Update xaml-hot-reload.md
  docs/debugger/xaml-hot-reload.md
Labels: change sent to author, ready-to-merge

#3762 Fix git push error for protected CLA branch
  docs/extensibility/ux-guidelines/per-monitor-awareness-extenders.md
  docs/ide/editorconfig-naming-conventions.md
  mac/index.yml
  mac/media/signing-in-image12.png
  mac/media/signing-in-image13.png
  mac/media/signing-in-image14.png
  mac/signing-in.md
  mac/uninstall.md
Labels: do-not-merge

#3769 Fix git push error for protected CLA branch
  docs/containers/media/AzureDevSpaceController_50x.svg
  docs/containers/media/deploy-docker-hub/container-tools-docker-hub-custom.png
  docs/data-tools/add-custom-controls-to-the-data-sources-window.md
  docs/designers/media/calculator-ui.gif
  docs/designers/media/smart-tag-glyph.gif
  docs/designers/media/windows-forms-control-library-template.png
  docs/designers/toc.yml
  docs/designers/walkthrough-windows-forms-designer.md
  docs/designers/windows-forms-designer-overview.md
  docs/ide/build-actions.md
  docs/ide/reference/options-windows-forms-designer-data-ui-customization.md
  docs/ide/reference/options-windows-forms-designer.md
  docs/images/getstarted.svg
  docs/images/i_dev-ops.svg
  docs/images/i_web-color.svg
  docs/images/live-share.svg
  docs/images/setup-install.svg
  docs/images/vs-hub-docs-features-devops.svg
  docs/images/vs-hub-docs-features-version-control.svg
  docs/images/vs_features-1.svg
  docs/images/vs_features-2.svg
  docs/images/vs_features-3.svg
  docs/images/vs_features-4.svg
  docs/images/vs_features-5.svg
  docs/images/vs_features-6.svg
  docs/images/vs_features-7.svg
  docs/images/vs_features-8.svg
  docs/images/vs_features-9.svg
  docs/images/vs_gaming-1.svg
  docs/images/vs_gaming-2.svg
  docs/images/vs_gaming-3.svg
  docs/images/vs_gaming-4.svg
  docs/images/vs_gaming-5.svg
  docs/images/vs_language-1.svg
  docs/images/vs_language-2.svg
  docs/images/vs_language-3.svg
  docs/images/vs_language-4.svg
  docs/images/vs_language-5.svg
  docs/images/vs_language-6.svg
  docs/images/vs_language-7.svg
  docs/images/vs_language-8.svg
  docs/images/vs_tools-1.svg
  docs/images/vs_tools-2.svg
  docs/images/vs_tools-3.svg
  docs/images/vs_web-1.svg
  docs/images/vs_web-2.svg
  docs/images/vs_web-3.svg
  docs/images/vs_web-4.svg
  docs/images/vs_web-5.svg
  docs/images/vs_web-6.svg
  docs/images/vs_web-7.svg
  docs/images/vs_windows-1.svg
  docs/images/vs_windows-2.svg
  docs/images/vs_windows-3.svg
  docs/images/whatsnew.svg
  docs/products/images/vs-ide.svg
  docs/toc.yml
Labels: do-not-merge

#3776 Fix git push error for protected CLA branch
  docs/extensibility/xaml-designer-extensibility-migration.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/test/media/vs-2019/basics-create-unit-tests.png
  docs/test/media/vs-2019/basics-generate-method-tdd.png
  docs/test/media/vs-2019/basics-mybank-solution.png
  docs/test/media/vs-2019/basics-test-explorer.png
  docs/test/media/vs-2019/basics-test-stub.PNG
  docs/test/unit-test-basics.md
Labels: do-not-merge

#3779 Update set-defaults-for-enterprise-deployments.md
  docs/install/set-defaults-for-enterprise-deployments.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech

#3784 Fix git push error for protected CLA branch
  docs/ide/productivity-features.md
  docs/test/assign-roles-to-a-test-controller-and-test-agent.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/customizing-code-coverage-analysis.md
  docs/test/how-to-create-a-test-setting-for-a-distributed-load-test.md
  docs/test/media/vs-2019/select-test-settings-file.png
  docs/test/unit-test-basics.md
  docs/vsto/how-to-programmatically-print-worksheets.md
  docs/vsto/how-to-programmatically-save-documents.md
  subscriptions/TOC.md
  subscriptions/using-admin-portal.md
  subscriptions/vscloud-overview.md
Labels: do-not-merge

#3798 Fix git push error for protected CLA branch
  docs/code-quality/analyzer-rule-sets.md
  docs/code-quality/basic-correctness-rules-rule-set-for-managed-code.md
  docs/code-quality/basic-design-guideline-rules-rule-set-for-managed-code.md
  docs/code-quality/extended-correctness-rules-rule-set-for-managed-code.md
  docs/code-quality/extended-design-guidelines-rules-rule-set-for-managed-code.md
  docs/code-quality/globalization-rules-rule-set-for-managed-code.md
  docs/code-quality/managed-minimum-rules-rule-set-for-managed-code.md
  docs/code-quality/managed-recommended-rules-rule-set-for-managed-code.md
  docs/code-quality/mixed-minimum-rules-rule-set.md
  docs/code-quality/mixed-recommended-rules-rule-set.md
  docs/code-quality/native-minimum-rules-rule-set.md
  docs/code-quality/native-recommended-rules-rule-set.md
  docs/code-quality/rule-set-reference.md
  docs/code-quality/security-rules-rule-set-for-managed-code.md
  docs/code-quality/toc.yml
  docs/designers/disable-dpi-awareness.md
  docs/designers/media/notifications-option.png
  docs/designers/media/scaling-gold-bar.png
  docs/designers/media/win-forms-designer-hdpi.png
  docs/designers/toc.yml
  docs/designers/walkthrough-windows-forms-designer.md
  docs/designers/windows-forms-designer-overview.md
  docs/extensibility/ux-guidelines/per-monitor-awareness-extenders.md
  docs/ide/reference/media/wrap-call-chain.png
  docs/ide/reference/wrap-and-align-call-chains.md
  docs/python/managing-python-environments-in-visual-studio.md
  docs/toc.yml
Labels: do-not-merge

#3801 Fix git push error for protected CLA branch
  docs/code-quality/fxcop-analyzers.yml
  docs/designers/toc.yml
  docs/get-started/csharp/toc.yml
  docs/ide/developer-community-privacy.md
  docs/ide/how-to-configure-projects-to-target-platforms.md
  docs/ide/reference/add-null-checks-for-all-parameters.md
  docs/ide/reference/media/add-null-checks-for-all-parameters.png
  docs/ide/reference/media/add-null-checks-for-all.png
  docs/toc.yml
  mac/net-core-support.md
Labels: do-not-merge

#3807 Fix git push error for protected CLA branch
  docs/code-quality/ca2300-do-not-use-insecure-deserializer-binaryformatter.md
  docs/code-quality/ca2301-do-not-call-binaryformatter-deserialize-without-first-setting-binaryformatter-binder.md
  docs/code-quality/ca2302-ensure-binaryformatter-binder-is-set-before-calling-binaryformatter-deserialize.md
  docs/code-quality/ca2310-do-not-use-insecure-deserializer-netdatacontractserializer.md
  docs/code-quality/ca2311-do-not-deserialize-without-first-setting-netdatacontractserializer-binder.md
  docs/code-quality/ca2312-ensure-netdatacontractserializer-binder-is-set-before-deserializing.md
  docs/code-quality/ca2326.md
  docs/code-quality/ca2327.md
  docs/code-quality/ca2328.md
  docs/code-quality/ca2329.md
  docs/code-quality/ca2330.md
  docs/code-quality/includes/insecure-deserializers-common-safe-to-suppress-md.md
  docs/code-quality/toc.yml
  docs/ide/reference/media/sync-active-document.png
  docs/ide/reference/projects-and-solutions-options-dialog-box.md
  docs/ide/template-parameters.md
  docs/ide/user-permissions-and-visual-studio.md
  docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/test/run-unit-tests-with-test-explorer.md
  docs/test/unit-test-basics.md
  subscriptions/vs-msdn.md
Labels: do-not-merge

#3810 Fix git push error for protected CLA branch
  docs/extensibility/internals/nesting-projects.md
  docs/ide/how-to-sign-application-and-deployment-manifests.md
  docs/ide/reference/media/sync-active-document.png
  docs/ide/reference/projects-and-solutions-options-dialog-box.md
  docs/ide/synchronized-settings-in-visual-studio.md
  docs/test/customizing-code-coverage-analysis.md
  docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md
Labels: do-not-merge

#3814 Fix git push error for protected CLA branch
  docs/extensibility/extending-and-customizing-tool-windows.md
  docs/install/modify-visual-studio.md
  subscriptions/TOC.md
  subscriptions/_img/admin-prefs/admin-prefs-button.png
  subscriptions/_img/admin-prefs/admin-prefs-flyout.png
  subscriptions/_img/admin-roles/add-admins.png
  subscriptions/_img/admin-roles/add-form.png
  subscriptions/_img/contact-my-admin/contact-my-admin-button.png
  subscriptions/_img/volume-license/super-admin-notice.png
  subscriptions/admin-prefs.md
  subscriptions/admin-roles.md
  subscriptions/contact-my-admin.md
  subscriptions/open-migration.md
  subscriptions/volume-license.md
Labels: do-not-merge, review-team-triage
