Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-09, with the labels that each got.

#3855 Fix git push error for protected CLA branch
  docs/deployment/deploying-applications-services-and-components.md
  docs/deployment/index.md
  docs/ide/code-snippets-schema-reference.md
  docs/ide/using-regular-expressions-in-visual-studio.md
  docs/index.yml
  mac/2017/publish-app-svc.md
  mac/2017/publish-folder.md
  mac/TOC.md
  mac/compiling-and-building.md
  mac/publish-app-svc.md
  mac/publish-folder.md
  mac/tf-version-control.md
Labels: do-not-merge

#3863 Fix git push error for protected CLA branch
  docs/code-quality/configure-fxcop-analyzers.md
  docs/get-started/csharp/media/vs-2019/csharp-create-new-project-search-winforms-filtered.png
  docs/ide/media/create-new-project-search-winforms-filtered.png
  docs/ide/media/docs-programming-language-control.png
  docs/ide/step-1-create-a-windows-forms-application-project.md
  docs/ide/step-10-write-code-for-additional-buttons-and-a-check-box.md
  docs/ide/step-11-run-your-program-and-try-other-features.md
  docs/ide/step-2-run-your-program.md
  docs/ide/step-3-set-your-form-properties.md
  docs/ide/step-4-lay-out-your-form-with-a-tablelayoutpanel-control.md
  docs/ide/step-5-add-controls-to-your-form.md
  docs/ide/step-6-name-your-button-controls.md
  docs/ide/step-7-add-dialog-components-to-your-form.md
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
  docs/ide/step-9-review-comment-and-test-your-code.md
  docs/ide/tutorial-1-create-a-picture-viewer.md
  docs/ide/tutorial-2-create-a-timed-math-quiz.md
  docs/ide/tutorial-3-create-a-matching-game.md
  docs/ide/using-regular-expressions-in-visual-studio.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md
  docs/install/install-visual-studio.md
  docs/install/update-visual-studio.md
  subscriptions/contact-my-admin.md
Labels: do-not-merge

#3816 Update walkthrough-creating-and-running-unit-tests-for-managed-code.md
  docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3836 Update visual-studio-build-numbers-and-release-dates.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech

#3870 Fix git push error for protected CLA branch
  docs/code-quality/C26402.md
  docs/code-quality/use-roslyn-analyzers.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/javascript/npm-package-management.md
  subscriptions/index.md
Labels: do-not-merge

#3874 Fix git push error for protected CLA branch
  docs/code-quality/ca2229-implement-serialization-constructors.md
  docs/containers/toc.yml
  docs/extensibility/vsix-language-pack-schema-2-0-reference.md
  docs/install/troubleshooting-installation-issues.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/python/media/vs-getting-started-python-02-windows.png
  docs/test/intellitest-manual/test-generation.md
Labels: do-not-merge

#3878 Fix git push error for protected CLA branch
  docs/code-quality/ca1002-do-not-expose-generic-lists.md
  docs/code-quality/ca1051-do-not-declare-visible-instance-fields.md
  docs/code-quality/ca1801-review-unused-parameters.md
  docs/code-quality/ca1821-remove-empty-finalizers.md
  docs/code-quality/ca2213-disposable-fields-should-be-disposed.md
  docs/ide/code-snippets.md
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
  docs/ide/template-parameters.md
  docs/modeling/create-layer-diagrams-from-your-code.md
  docs/modeling/layer-diagrams-guidelines.md
  docs/modeling/layer-diagrams-reference.md
Labels: do-not-merge

#3884 Fix git push error for protected CLA branch
  docs/code-quality/ca3061.md
  docs/code-quality/ca5363.md
  docs/code-quality/ca5369.md
  docs/code-quality/ca5370.md
  docs/code-quality/ca5371.md
  docs/code-quality/ca5372.md
  docs/code-quality/ca5373.md
  docs/code-quality/ca5380.md
  docs/code-quality/ca5381.md
  docs/code-quality/ca5389.md
  docs/code-quality/toc.yml
  docs/ide/step-2-run-your-program.md
  docs/ide/tutorial-1-create-a-picture-viewer.md
  mac/TOC.md
  mac/samples/index.yml
Labels: do-not-merge

#3885 add missing semicolon in c26478.md
  docs/code-quality/c26478.md
Labels: change sent to author, ready-to-merge, vs-ide-code-analysis/tech

#3892 Fix git push error for protected CLA branch
  docs/get-started/csharp/media/exploreide-wpf-running-app.png
  docs/get-started/csharp/media/vs-2019/exploreide-live-visual-tree.png
  docs/get-started/csharp/media/vs-2019/exploreide-nameproject.png
  docs/get-started/csharp/media/vs-2019/exploreide-newprojectcsharp-vs2019.png
  docs/get-started/csharp/media/vs-2019/exploreide-wpf-running-app.png
  docs/get-started/csharp/tutorial-wpf.md
  docs/get-started/visual-basic/media/exploreide-live-visual-tree.png
  docs/get-started/visual-basic/media/exploreide-wpf-running-app.png
  docs/get-started/visual-basic/media/vs-2019/exploreide-live-visual-tree.png
  docs/get-started/visual-basic/media/vs-2019/exploreide-wpf-running-app.png
  docs/get-started/visual-basic/tutorial-wpf.md
  docs/get-started/visual-studio-ide.md
  docs/ide/developer-community-privacy.md
  docs/ide/media/report-a-problem-logs-collected.png
  docs/index.yml
  docs/vs-2015/ide/get-started-developing-with-visual-studio.md
Labels: do-not-merge

#3727 Updated VSIX references spacing
  docs/extensibility/how-to-use-wizards-with-project-templates.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3817 Update unit-tests-for-generic-methods.md
  docs/test/unit-tests-for-generic-methods.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3890 Update ca1507.md
  docs/code-quality/ca1507.md
Labels: change sent to author, do-not-merge

#3827 Added <Configuration> section to VideoRecorder data collector
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3778 Clarification
  mac/asp-net-core.md
Labels: assessing_(C&L), change sent to author, ready-to-merge

#3897 Fix git push error for protected CLA branch
  docs/debugger/supported-code-changes-csharp.md
  docs/debugger/using-the-debuggerdisplay-attribute.md
  docs/deployment/deployment-element-clickonce-deployment.md
  docs/designers/toc.yml
  docs/ide/how-to-sign-application-and-deployment-manifests.md
  docs/ide/step-1-create-a-windows-forms-application-project.md
  docs/ide/step-10-write-code-for-additional-buttons-and-a-check-box.md
  docs/ide/step-11-run-your-program-and-try-other-features.md
  docs/ide/step-2-run-your-program.md
  docs/ide/step-3-set-your-form-properties.md
  docs/ide/step-4-lay-out-your-form-with-a-tablelayoutpanel-control.md
  docs/ide/step-6-name-your-button-controls.md
  docs/ide/step-7-add-dialog-components-to-your-form.md
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
  docs/ide/step-9-review-comment-and-test-your-code.md
  docs/ide/tutorial-1-create-a-picture-viewer.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/msbuild/csc-task.md
  docs/msbuild/sgen-task.md
Labels: do-not-merge

#3898 Update map-dependencies-across-your-solutions.md
  docs/modeling/map-dependencies-across-your-solutions.md
Labels: change sent to author, do-not-merge

#3908 Fix git push error for protected CLA branch
  docs/get-started/visual-basic/tutorial-console.md
Labels: do-not-merge

#3912 Fix git push error for protected CLA branch
  docs/ide/step-11-run-your-program-and-try-other-features.md
  docs/ide/step-3-set-your-form-properties.md
  docs/ide/step-5-add-controls-to-your-form.md
  docs/ide/tutorial-1-create-a-picture-viewer.md
  docs/install/troubleshooting-installation-issues.md
  docs/install/use-command-line-parameters-to-install-visual-studio.md
  docs/msbuild/how-to-extend-the-visual-studio-build-process.md
  docs/msbuild/msbuild-target-framework-and-target-platform.md
  docs/msbuild/visual-studio-integration-msbuild.md
  docs/msbuild/what-s-new-in-msbuild-15-0.md
  docs/test/media/vs-2019/analyze-code-coverage.png
  docs/test/media/vs-2019/coverage-fonts-and-colors.png
  docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md
Labels: do-not-merge

#3926 Fix git push error for protected CLA branch
  docs/get-started/csharp/media/csharp-aspnet-razor-solution-explorer-mycoreapp.png
  docs/get-started/csharp/tutorial-aspnet-core-ef-step-01.md
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/ide/step-2-create-a-random-addition-problem.md
  docs/ide/step-3-add-a-countdown-timer.md
  docs/ide/step-4-add-the-checktheanswer-parens-method.md
  docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md
  docs/ide/step-6-add-a-subtraction-problem.md
  docs/ide/step-7-add-multiplication-and-division-problems.md
  docs/ide/step-8-customize-the-quiz.md
  docs/ide/tutorial-2-create-a-timed-math-quiz.md
Labels: do-not-merge

#3931 Fix git push error for protected CLA branch
  docs/debugger/debugger-feature-tour.md
  docs/debugger/debugger-tips-and-tricks.md
  docs/debugger/general-debugging-options-dialog-box.md
  docs/debugger/inspect-xaml-properties-while-debugging.md
  docs/debugger/media/xaml-hot-reload-available.png
  docs/debugger/media/xaml-hot-reload-enable.png
  docs/debugger/media/xaml-hot-reload-show-runtime-tools.png
  docs/debugger/media/xaml-hot-reload-using.gif
  docs/debugger/toc.yml
  docs/debugger/xaml-hot-reload-troubleshooting.md
  docs/debugger/xaml-hot-reload.md
  docs/ide/step-1-create-a-project-and-add-a-table-to-your-form.md
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/ide/step-10-write-code-for-additional-buttons-and-a-check-box.md
  docs/ide/step-2-create-a-random-addition-problem.md
  docs/ide/step-3-add-a-countdown-timer.md
  docs/ide/step-4-add-the-checktheanswer-parens-method.md
  docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md
  docs/ide/step-6-add-a-subtraction-problem.md
  docs/ide/step-6-name-your-button-controls.md
  docs/ide/step-7-add-multiplication-and-division-problems.md
  docs/ide/step-8-customize-the-quiz.md
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
  docs/ide/tutorial-2-create-a-timed-math-quiz.md
Labels: do-not-merge

#3934 Fix Typos in Documentation
  docs/rtvs/r-projects-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3950 Fix git push error for protected CLA branch
  docs/debugger/media/actionsmessageinoutputwindow.png
  docs/debugger/media/breakpointinitialization.png
  docs/debugger/media/breakpointwindow.png
  docs/debugger/media/checkedactionsbox.png
  docs/debugger/media/checkedconditionsbox.png
  docs/debugger/media/conditionalexpressionfilter.png
  docs/debugger/media/conditionalexpressionhitcount.png
  docs/debugger/media/conditionalexpressionistrue.png
  docs/debugger/media/conditionalexpressionwhenchanged.png
  docs/debugger/media/counterexample.png
  docs/debugger/media/counteroutputmessage.png
  docs/debugger/toc.yml
  docs/debugger/using-tracepoints.md
  docs/ide/step-10-write-code-for-additional-buttons-and-a-check-box.md
  docs/ide/step-2-add-a-random-object-and-a-list-of-icons.md
  docs/ide/step-2-create-a-random-addition-problem.md
  docs/ide/step-3-add-a-countdown-timer.md
  docs/ide/step-3-assign-a-random-icon-to-each-label.md
  docs/ide/step-4-add-a-click-event-handler-to-each-label.md
  docs/ide/step-4-add-the-checktheanswer-parens-method.md
  docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md
  docs/ide/step-5-add-label-references.md
  docs/ide/step-6-add-a-subtraction-problem.md
  docs/ide/step-6-name-your-button-controls.md
  docs/ide/step-7-add-multiplication-and-division-problems.md
  docs/ide/step-8-customize-the-quiz.md
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
  docs/ide/step-9-review-comment-and-test-your-code.md
  docs/install/troubleshooting-installation-issues.md
Labels: do-not-merge

#3951 Update troubleshooting-code-coverage.md
  docs/test/troubleshooting-code-coverage.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3959 Fix git push error for protected CLA branch
  docs/deployment/deploying-applications-services-and-components.md
  docs/deployment/index.md
  docs/deployment/index.yml
  docs/deployment/quickstart-deploy-to-a-web-site.md
  docs/deployment/quickstart-deploy-to-local-folder.md
  docs/deployment/toc.yml
  docs/get-started/csharp/toc.yml
  docs/get-started/visual-basic/toc.yml
  docs/index.yml
  docs/profiling/analyze-energy-use-in-store-apps.md
  docs/profiling/analyze-memory-usage.md
  docs/profiling/analyzing-performance-tools-data.md
  docs/profiling/application-timeline.md
  docs/profiling/beginners-guide-to-cpu-sampling.md
  docs/profiling/beginners-guide-to-performance-profiling.md
  docs/profiling/concurrency-visualizer.md
  docs/profiling/index.md
  docs/profiling/index.yml
  docs/profiling/memory-usage-without-debugging2.md
  docs/profiling/network-usage.md
  docs/profiling/perftips.md
  docs/profiling/quickstart-cpu-usage-aspnet.md
  docs/profiling/quickstart-cpu-usage-managed.md
  docs/profiling/quickstart-cpu-usage-native.md
  docs/profiling/toc.yml
  docs/profiling/what-s-new-in-profiling-tools.md
  docs/toc.yml
  mac/build-actions.md
  mac/building-and-cleaning-projects-and-solutions.md
  mac/compiling-and-building.md
  mac/configurations.md
  mac/create-and-edit-configurations.md
  mac/customizing-build-system.md
  mac/razor.md
Labels: do-not-merge

#3960 VS Subscriptions + GitHub is an offer
  subscriptions/access-github.md
  subscriptions/assign-github.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3962 Fixed typo (aplications)
  docs/deployment/how-to-manage-updates-for-a-clickonce-application.md
Labels: change sent to author, do-not-merge

#3967 Fix git push error for protected CLA branch
  mac/javascript.md
  mac/media/javascript-type-intellisense-2019.gif
  mac/media/razor-2019.png
  mac/media/tsjseditor-2019.gif
  mac/razor.md
Labels: do-not-merge

#3939 MSBuild: Details on Task parameters
  docs/msbuild/task-writing.md
Labels: assessing_(C&L), change sent to author, ready-to-merge

#3914 Edit.ExpandSelection/Edit.ContractSelection have been fixed again for C++
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3379 Dev16.3+ cannot migrate xproj projects
  docs/porting/port-migrate-and-upgrade-visual-studio-projects.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3975 Update convert-local-function-method.md
  docs/ide/reference/convert-local-function-method.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3966 Add Build Tools download link to installers
  docs/install/create-an-offline-installation-of-visual-studio.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech

#3995 Update stop-statements-in-visual-basic.md
  docs/debugger/stop-statements-in-visual-basic.md
Labels: assessing_(C&L), change sent to author, ready-to-merge

#4001 Fix git push error for protected CLA branch
  mac/TOC.md
  mac/vsmac-for-windows-users.md
Labels: do-not-merge

#4002 Fix syntax sample of WaitStart flag
  docs/profiling/waitstart.md
Labels: assessing_(C&L), change sent to author, ready-to-merge

#4003 Fix git push error for protected CLA branch
  docs/debugger/inspect-xaml-properties-while-debugging.md
  docs/debugger/stop-statements-in-visual-basic.md
  docs/python/index.yml
  mac/TOC.md
  mac/launch-settings.md
Labels: do-not-merge

#3998 Changed formatting of some named files/paths
  docs/vsto/office-primary-interop-assemblies.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3894 Update unit-testing-visual-csharp-code-in-a-store-app.md
  docs/test/unit-testing-visual-csharp-code-in-a-store-app.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#3895 Update unit-testing-visual-csharp-code-in-a-store-app.md
  docs/test/unit-testing-visual-csharp-code-in-a-store-app.md
Labels: assessing_(C&L), change sent to author, do-not-merge
