Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-06, with the labels that each got.

#3365 Fix git push error for protected CLA branch
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3366 Fix git push error for protected CLA branch
  docs/index.md
  docs/index.yml
Labels: change sent to author, do-not-merge

#3319 Global binding Edit.GoToFindCombo overridden
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, ready-to-merge

#3374 Fix git push error for protected CLA branch
  docs/data-tools/create-a-sql-database-by-using-a-designer.md
  docs/ide/reference/rename.md
  docs/ide/step-1-create-a-project-and-add-a-table-to-your-form.md
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/ide/step-1-create-a-windows-forms-application-project.md
  docs/ide/step-5-add-controls-to-your-form.md
  docs/install/update-servicing-baseline.md
  mac/2017/installation.md
  mac/2017/javascript.md
  mac/2017/report-a-problem.md
  mac/2017/tf-version-control.md
  mac/javascript.md
  mac/net-core-support.md
  mac/report-a-problem.md
  mac/tf-version-control.md
  subscriptions/vs-office-dev.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3369 Update live-unit-testing-faq.md
  docs/test/live-unit-testing-faq.md
Labels: change sent to author, ready-to-merge

#3377 Preface `ArgumentOutOfRangeException` with `System.`
  docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md
Labels: change sent to author, do-not-merge

#3390 Remove meaningless sentence
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
Labels: change sent to author, ready-to-merge

#3402 Fixed "Dipose" typo.
  docs/code-quality/ca1063-implement-idisposable-correctly.md
Labels: change sent to author, do-not-merge

#3401 Update connect-to-data-in-an-access-database-windows-forms.md
  docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md
Labels: change sent to author, do-not-merge

#3318 Debug.FunctionBreakpoint shortcut keys
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3406 Fixed "Dipose" typo.
  docs/vs-2015/code-quality/ca1063-implement-idisposable-correctly.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-code-analysis/tech

#3422 fix broken link to CMake tools for Visual C++
  docs/test/how-to-use-ctest-for-cpp.md
Labels: change sent to author, do-not-merge

#3426 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/debugger/debugger-tips-and-tricks.md
  docs/debugger/error-the-microsoft-visual-studio-remote-debugging-monitor-no-permission.md
  docs/debugger/error-the-visual-studio-remote-debugger-service-on-the-target-computer-cannot-connect-back-to-this-computer.md
  docs/debugger/includes/remote-debugger-configuration.md
  docs/debugger/remote-debugging-errors-and-troubleshooting.md
  docs/debugger/remote-debugging.md
  docs/get-started/csharp/tutorial-wpf.md
  docs/get-started/visual-basic/tutorial-wpf.md
  docs/ide/class-designer/keyboard-and-mouse-shortcuts-in-the-class-diagram-and-class-details-window.md
  docs/ide/csharp-developer-productivity.md
  docs/ide/default-keyboard-shortcuts-for-frequently-used-commands-in-visual-studio.md
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
  docs/ide/getting-started-with-cpp-in-visual-studio.md
  docs/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12.md
  docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md
  docs/ide/media/named-capture-group.png
  docs/ide/media/numbered-capture-group.png
  docs/ide/productivity-features.md
  docs/ide/productivity-shortcuts.md
  docs/ide/reference/how-to-use-the-keyboard-exclusively.md
  docs/ide/reference/log-command-window-output-command.md
  docs/ide/reference/visual-studio-commands.md
  docs/ide/tips-and-tricks-for-visual-studio.md
  docs/ide/using-regular-expressions-in-visual-studio.md
  docs/python/installing-python-interpreters.md
  docs/python/overview-of-python-tools-for-visual-studio.md
  docs/toc.yml
  docs/xml-tools/debugging-xslt.md
  mac/2017/set-startup-projects.md
  mac/set-startup-projects.md
Labels: do-not-merge

#3428 Fix git push error for protected CLA branch
  docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md
  docs/test/how-to-use-microsoft-test-framework-for-cpp.md
  docs/test/how-to-write-unit-tests-for-cpp-dlls.md
  docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md
  docs/test/unit-testing-a-visual-cpp-dll-for-store-apps.md
  docs/test/walkthrough-writing-unit-tests-for-cpp-dlls.md
  mac/net-core-support.md
  mac/report-a-problem.md
Labels: change sent to author, do-not-merge

#3423 Document the selection-modifying commands in editor context
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3435 Fix git push error for protected CLA branch
  docs/msbuild/customize-your-build.md
  docs/msbuild/msbuild-targets.md
  docs/msbuild/target-element-msbuild.md
  mac/net-core-support.md
Labels: do-not-merge

#3432 CA2105 - Add related rules CA2104: Do not declare read only mutable reference types
  docs/code-quality/ca2105-array-fields-should-not-be-read-only.md
Labels: change sent to author, do-not-merge

#3436 Tag was not closed
  docs/extensibility/templatecontent-element-visual-studio-templates.md
Labels: change sent to author, do-not-merge, vs-ide-general/tech

#3441 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/cross-platform/index.md
  docs/extensibility/index.md
  docs/ide/editorconfig-code-style-settings-reference.md
  docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md
  docs/ide/how-to-target-a-version-of-the-dotnet-framework.md
  docs/ide/media/merge-if-statement-complete.png
  docs/ide/media/merge-if-statement.png
  docs/ide/media/split-if-statement-complete.png
  docs/ide/media/split-if-statement.png
  docs/ide/reference/application-page-project-designer-csharp.md
  docs/ide/reference/application-page-project-designer-visual-basic.md
  docs/ide/reference/media/sync-namespace-and-folder-name.png
  docs/ide/reference/output-window.md
  docs/ide/reference/split-or-merge-if-statement.md
  docs/ide/reference/sync-namespace-and-folder-name.md
  docs/ide/visual-studio-multi-targeting-overview.md
  docs/install/update-visual-studio.md
  docs/products/index.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/how-to-use-ctest-for-cpp.md
  docs/test/writing-unit-tests-for-c-cpp.md
  docs/toc.yml
  docs/version-control/index.md
Labels: do-not-merge

#3446 Fix git push error for protected CLA branch
  docs/code-quality/code-analysis-for-managed-code-overview.md
  docs/code-quality/fxcop-analyzers.yml
  docs/code-quality/roslyn-analyzers-overview.md
  docs/code-quality/static-code-analysis-for-managed-code-overview.md
  docs/code-quality/toc.yml
  docs/code-quality/walkthrough-analyzing-managed-code-for-code-defects.md
  docs/debugger/general-debugging-options-dialog-box.md
  docs/debugger/toc.yml
  docs/ide/finding-references.md
  docs/ide/media/vside_findallreferencesKind.png
  docs/install/update-visual-studio.md
  docs/msbuild/msbuild-special-characters.md
  docs/profiling/toc.yml
  mac/TOC.md
  mac/docker-multi-container.md
  mac/docker-quickstart.md
  mac/media/docker-multicontainer-debug.png
  mac/media/docker-quickstart-1.png
  mac/media/docker-quickstart-2.png
  mac/media/docker-quickstart-3.png
  mac/media/docker-quickstart-4.png
  mac/media/docker-quickstart-5.png
  mac/media/docker-quickstart-6.png
  mac/media/docker-quickstart-7.png
  mac/media/docker-quickstart-8.png
  mac/media/docker-quickstart-9.png
  scripting-docs/_breadcrumb/toc.yml
Labels: do-not-merge

#3414 Remove "Lightweight solution load" reference
  docs/test/live-unit-testing-faq.md
Labels: change sent to author, do-not-merge

#3447 Add subsection link.
  docs/code-quality/c26444.md
Labels: change sent to author, do-not-merge

#3463 Fix git push error for protected CLA branch
  docs/debugger/debug-live-azure-apps-faq.md
  docs/deployment/toc.yml
  docs/ide/create-portable-custom-editor-options.md
  docs/ide/editorconfig-code-style-settings-reference.md
  docs/ide/editorconfig-formatting-conventions.md
  docs/ide/editorconfig-language-conventions.md
  docs/ide/editorconfig-naming-conventions.md
  docs/ide/reference/convert-for-loop-to-foreach.md
  docs/ide/reference/convert-linq-to-foreach.md
  docs/ide/reference/options-text-editor-csharp-formatting.md
  docs/ide/walkthrough-creating-a-code-snippet.md
  docs/install/update-visual-studio.md
  docs/msbuild/toc.yml
  docs/toc.yml
  mac/asp-net-core.md
  mac/building-asp-net-core.md
  subscriptions/index.md
  subscriptions/whats-new-in-subscriptions.md
Labels: do-not-merge

#3499 Remove any mention of VSWorkspaceSettings.json
  docs/ide/customize-build-and-debug-tasks-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3503 Fix git push error for protected CLA branch
  docs/ide/code-styles-and-code-cleanup.md
  docs/ide/csharp-developer-productivity.md
  docs/ide/media/run-code-cleanup-project-solution.png
  docs/ide/reference/media/move-to-namespace.png
  docs/ide/reference/media/select-target-namespace.png
  docs/ide/reference/move-type-to-namespace.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/update-visual-studio.md
  docs/toc.yml
Labels: do-not-merge

#3507 Fix broken image link
  docs/ide/report-a-problem.md
Labels: change sent to author, do-not-merge

#3513 Fix git push error for protected CLA branch
  docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md
  docs/ide/editorconfig-naming-conventions.md
  docs/ide/file-nesting-solution-explorer.md
  docs/ide/reference/intellisense-completion-unimported-types.md
  docs/ide/reference/media/intellisense-completion-unimported-types.png
  docs/index.yml
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/workload-component-id-vs-build-tools.md
  docs/products/images/vs-code.svg
  docs/toc.yml
  mac/2017/TOC.md
  mac/2017/media/update-vsmac-installer.png
  mac/2017/media/update-vsmac-updater.png
  mac/2017/update-vsmac-8.0.md
  mac/installation.md
  mac/media/install-privacy.png
  mac/media/install-selection-sml.png
  mac/media/install-selection.png
  mac/updater-troubleshooting.md
Labels: do-not-merge

#3516 Fix git push error for protected CLA branch
  docs/ide/code-styles-and-code-cleanup.md
  docs/ide/create-portable-custom-editor-options.md
  docs/ide/csharp-developer-productivity.md
  docs/ide/media/editorconfig-dotnet.png
  docs/ide/media/editorconfig-item-templates.png
  docs/ide/media/run-code-cleanup-project-solution.png
  docs/ide/reference/convert-switch-statement-to-switch-expression.md
  docs/ide/reference/generate-parameter.md
  docs/ide/reference/media/convert-switch-statement-to-switch-expression.png
  docs/ide/reference/media/generate-parameter.png
  docs/ide/reference/media/sort-usings.png
  docs/ide/reference/setting-language-specific-editor-options.md
  docs/ide/reference/sort-usings.md
  docs/ide/visual-csharp-intellisense.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/index.yml
  docs/install/visual-studio-administrator-guide.md
  docs/toc.yml
  docs/vsto/how-to-programmatically-retrieve-start-and-end-characters-in-ranges.md
  docs/vsto/how-to-programmatically-retrieve-unread-messages-from-the-inbox.md
  docs/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items.md
  docs/vsto/how-to-programmatically-search-for-an-e-mail-address-in-contacts.md
  docs/vsto/how-to-programmatically-search-for-and-replace-text-in-documents.md
  docs/vsto/how-to-programmatically-store-and-retrieve-date-values-in-excel-ranges.md
  docs/vsto/how-to-set-up-configuration-information-for-an-office-solution.md
  docs/vsto/how-to-target-office-applications-through-primary-interop-assemblies.md
  docs/vsto/how-to-validate-data-when-a-new-row-is-added-to-a-listobject-control.md
  docs/vsto/publish-page-project-designer-office-development-in-visual-studio.md
  docs/vsto/updating-excel-and-word-projects-that-you-migrate-to-the-dotnet-framework-4-or-the-dotnet-framework-4-5.md
  docs/vsto/walkthrough-adding-controls-to-a-document-at-run-time-in-a-vsto-add-in.md
  docs/vsto/walkthrough-adding-controls-to-a-worksheet-at-run-time-in-vsto-add-in-project.md
  docs/vsto/walkthrough-binding-to-data-from-a-service-in-a-vsto-add-in-project.md
  docs/vsto/walkthrough-changing-document-formatting-using-checkbox-controls.md
  docs/vsto/walkthrough-changing-worksheet-formatting-using-checkbox-controls.md
  docs/vsto/walkthrough-creating-a-master-detail-relation-using-a-cached-dataset.md
  docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md
  docs/vsto/walkthrough-creating-your-first-document-level-customization-for-word.md
  docs/vsto/walkthrough-displaying-custom-task-panes-with-e-mail-messages-in-outlook.md
  docs/vsto/walkthrough-displaying-text-in-a-text-box-in-a-document-using-a-button.md
  docs/vsto/walkthrough-displaying-text-in-a-text-box-in-a-worksheet-using-a-button.md
  docs/vsto/walkthrough-synchronizing-a-custom-task-pane-with-a-ribbon-button.md
  docs/vsto/walkthrough-updating-a-chart-in-a-worksheet-using-radio-buttons.md
  mac/2017/update-vsmac-8.0.md
Labels: do-not-merge

#3517 Fixed typo "lauch" to "launch"
  docs/debugger/how-to-debug-managed-and-native-code.md
Labels: change sent to author, ready-to-merge

#3515 Replace placeholder variable with actual variable
  docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md
Labels: change sent to author, ready-to-merge

#3410 Move adding of System and System.Drawing references
  docs/extensibility/how-to-use-wizards-with-project-templates.md
Labels: change sent to author, ready-to-merge

#3344 Update idebugcodecontext2-getdocumentcontext.md
  docs/extensibility/debugger/reference/idebugcodecontext2-getdocumentcontext.md
Labels: change sent to author, ready-to-merge

#3531 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/ca1801-review-unused-parameters.md
  docs/debugger/using-breakpoints.md
  docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md
  docs/get-started/csharp/media/exploreide-greetingswithcontrollabels-cs.png
  docs/ide/quickstart-python.md
  docs/install/create-a-network-installation-of-visual-studio.md
  docs/install/create-an-offline-installation-of-visual-studio.md
  docs/install/modify-visual-studio.md
  docs/install/using-visual-studio-vm.md
  docs/install/workload-component-id-vs-build-tools.md
  subscriptions/_img/manage-vs-subscriptions/change-prefs.png
  subscriptions/_img/vs-opsgility/vs-opsgility-tile.PNG
  subscriptions/_img/vs-opsgility/vs-vse-landing-page.png
  subscriptions/manage-vs-subscriptions.md
  subscriptions/vs-opsgility.md
Labels: do-not-merge

#3532 "Introduction to code signing" that's maintained
  docs/deployment/clickonce-and-authenticode.md
Labels: change sent to author, ready-to-merge

#3534 Fix git push error for protected CLA branch
  docs/code-quality/toc.yml
  docs/install/visual-studio-build-numbers-and-release-dates.md
  mac/2017/tf-version-control.md
  mac/tf-version-control.md
Labels: do-not-merge

#3536 Category Moved for Modeling SDK
  docs/modeling/includes/modeling_sdk_info.md
Labels: change sent to author, do-not-merge

#3543 Clarify that .edmx files support EF6 only
  docs/data-tools/entity-data-model-tools-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3546 Fix git push error for protected CLA branch
  docs/containers/troubleshooting-docker-errors.md
Labels: change sent to author, do-not-merge, tracking (C&L), vs-azure/tech

#3552 Fix git push error for protected CLA branch
  docs/containers/container-build.md
  docs/containers/container-msbuild-properties.md
  docs/containers/container-tools-react.md
  docs/containers/container-unit-testing.md
  docs/containers/edit-and-refresh.md
  docs/containers/toc.yml
  mac/snippets.md
  subscriptions/vscloud-overview.md
  subscriptions/whats-new-in-subscriptions.md
Labels: do-not-merge
