Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-07, with the labels that each got.

#3557 Fix git push error for protected CLA branch
  docs/code-quality/annotating-structs-and-classes.md
  docs/index.yml
  docs/vs-2015/modeling/uml-use-case-diagrams-guidelines.md
  mac/2017/asp-net-core.md
  mac/configurations.md
  subscriptions/subscriber-benefits.md
Labels: do-not-merge

#3564 Fix git push error for protected CLA branch
  docs/ide/media/attach-to-process.png
  docs/ide/msbuild-logs.md
  docs/ide/report-a-problem-minidumps.md
  docs/ide/report-a-problem-perfview.md
  docs/toc.yml
Labels: do-not-merge

#3570 fix: MD030/list-marker-space
  docs/extensibility/debugger/reference/idebugstackframe2-getlanguageinfo.md
  mac/nuget-walkthrough.md
  subscriptions/access-github.md
  subscriptions/assign-github.md
  subscriptions/handle-overclaimed-license.md
Labels: change sent to author, do-not-merge

#3569 fix: MD033/no-inline-html
  docs/code-quality/fxcop-rule-port-status.md
  docs/debugger/debug-live-azure-apps-troubleshooting.md
  docs/extensibility/upgrading-custom-project-and-item-templates-for-visual-studio-2017.md
  docs/test/vstest-console-options.md
  subscriptions/assign-github.md
Labels: change sent to author, do-not-merge

#3573 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/containers/container-build.md
  docs/containers/container-unit-testing.md
  docs/containers/toc.yml
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/advanced-build-tools-container.md
  docs/install/build-tools-container-issues.md
  docs/install/build-tools-container.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/products/images/vs-code.svg
  docs/products/index.md
  subscriptions/TOC.md
  subscriptions/_img/vs-cloudpilot-tile.png
  subscriptions/_img/vs-rstudio/vs-rstudio-apply-code unblocked.png
  subscriptions/_img/vs-rstudio/vs-rstudio-apply-code.png
  subscriptions/_img/vs-rstudio/vs-rstudio-choose-version.png
  subscriptions/_img/vs-rstudio/vs-rstudio-complete.png
  subscriptions/_img/vs-rstudio/vs-rstudio-cran-page.png
  subscriptions/_img/vs-rstudio/vs-rstudio-dashboard.png
  subscriptions/_img/vs-rstudio/vs-rstudio-destination.png
  subscriptions/_img/vs-rstudio/vs-rstudio-installer.png
  subscriptions/_img/vs-rstudio/vs-rstudio-landing-page.png
  subscriptions/_img/vs-rstudio/vs-rstudio-not-installed.png
  subscriptions/_img/vs-rstudio/vs-rstudio-plan-summary.png
  subscriptions/_img/vs-rstudio/vs-rstudio-progress.png
  subscriptions/_img/vs-rstudio/vs-rstudio-start-folder.png
  subscriptions/_img/vs-rstudio/vs-rstudio-tile.png
  subscriptions/_img/vs-rstudio/vs-rstudio-wizard.png
  subscriptions/_img/vs-success-dialog.PNG
  subscriptions/_img/vs-xamarin/vs-xamarin-access.png
  subscriptions/_img/vs-xamarin/vs-xamarin-activate.png
  subscriptions/_img/vs-xamarin/vs-xamarin-confirm.png
  subscriptions/_img/vs-xamarin/vs-xamarin-connect.png
  subscriptions/_img/vs-xamarin/vs-xamarin-portal.png
  subscriptions/_img/vs-xamarin/vs-xamarin-tile.PNG
  subscriptions/vs-rstudio.md
  subscriptions/vs-xamarin.md
Labels: do-not-merge

#3580 fix: MD005/list-indent
  docs/ide/editorconfig-language-conventions.md
Labels: change sent to author, do-not-merge

#3581 fix: MD006/ul-start-left
  docs/code-quality/ca2105-array-fields-should-not-be-read-only.md
Labels: change sent to author, do-not-merge

#3583 fix: MD012/no-multiple-blanks
  docs/containers/container-tools.md
  docs/cross-platform/install-and-configure-tools-to-build-using-ios.md
  docs/debugger/debug-live-azure-apps-faq.md
  docs/extensibility/getting-started-with-roslyn-analyzers.md
  docs/msbuild/custombuild-task.md
  mac/building-asp-net-core.md
  mac/install-behind-a-firewall-or-proxy-server.md
  subscriptions/access-github.md
  subscriptions/assign-github.md
  subscriptions/handle-overclaimed-license.md
  subscriptions/subscriber-benefits.md
  subscriptions/vs-azure-advisory-chat.md
  subscriptions/vs-azure-community.md
  subscriptions/vs-azure-devops.md
  subscriptions/vs-concierge-chat.md
  subscriptions/vs-ide-benefit.md
  subscriptions/vscloud-overview.md
Labels: change sent to author, do-not-merge, vs-ide-mobile/tech

#3582 fix: MD031/blanks-around-fences
  docs/debugger/debug-live-azure-apps-faq.md
  docs/ide/file-nesting-solution-explorer.md
  docs/install/command-line-parameter-examples.md
  mac/docker-multi-container.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#3586 Fix git push error for protected CLA branch
  docs/get-started/csharp/toc.yml
  docs/get-started/visual-basic/toc.yml
  docs/products/images/vs-code-logo.svg
  docs/products/index.md
Labels: do-not-merge

#3589 chore: Remove link locale
  docs/install/build-tools-container.md
Labels: change sent to author, do-not-merge, review-team-triage, visual-studio-windows/prod, vs-installation/tech

#3599 Fix git push error for protected CLA branch
  .markdownlint.json
  docs/azure/vs-azure-tools-cloud-service-project-managing-roles.md
  docs/azure/vs-azure-tools-configure-roles-for-cloud-service.md
  docs/azure/vs-azure-tools-migrate-publish-web-app-to-cloud-service.md
  docs/azure/vs-azure-tools-publish-webapplicationwebsite-windows-powershell-script.md
  docs/azure/vs-azure-tools-storage-resources-server-explorer-browse-manage.md
  docs/azure/vs-azure-tools-table-designer-construct-filter-strings.md
  docs/data-tools/create-a-windows-forms-user-control-that-supports-simple-data-binding.md
  docs/deployment/creating-bootstrapper-packages.md
  docs/extensibility/dynamically-adding-menu-items.md
  docs/vs-2015/azure/vs-azure-tools-cloud-service-project-managing-roles.md
  docs/vs-2015/azure/vs-azure-tools-migrate-publish-web-app-to-cloud-service.md
  docs/vs-2015/azure/vs-azure-tools-publish-webapplicationwebsite-windows-powershell-script.md
  docs/vs-2015/azure/vs-azure-tools-storage-resources-server-explorer-browse-manage.md
  docs/vs-2015/azure/vs-azure-tools-table-designer-construct-filter-strings.md
  docs/vs-2015/misc/menucommands-vs-olemenucommands.md
  docs/xml-tools/walkthrough-using-xml-editor-features.md
  mac/media/razor-editor.png
  mac/media/razor-new-netcore22.png
  mac/media/razor-new-project1.png
  mac/media/razor-new-project2.png
  mac/media/razor-new.png
  mac/media/razor-webapp.png
  mac/razor.md
  subscriptions/TOC.md
Labels: do-not-merge

#3604 fix: MD030/list-marker-space
  mac/razor.md
Labels: change sent to author, do-not-merge, vs-ide-general/tech

#3605 fix: MD046/code-block-style
  docs/debugger/debug-live-azure-applications.md
  docs/javascript/configure-packages-with-package-json.md
  docs/vs-2015/azure/vs-azure-tools-configure-roles-for-cloud-service.md
Labels: do-not-merge, tracking (C&L), visual-studio-dev14/prod, vs-azure/tech

#3606 chore: Updated Mardownlint config
  .markdownlint.json
Labels: do-not-merge, tracking (C&L)

#3603 Add VB example to Xaml designer extensibility
  docs/extensibility/xaml-designer-extensibility-migration.md
Labels: change sent to author, do-not-merge, review-team-triage, tracking (C&L)

#3585 Follow coding conventions.
  docs/get-started/csharp/tutorial-console.md
Labels: change sent to author, do-not-merge, review-team-triage, tracking (C&L), visual-studio-windows/prod, vs-ide-general/tech

#3547 Fix paths in example output
  docs/msbuild/msbuild-transforms.md
Labels: change sent to author, ready-to-merge, tracking (C&L)

#3566 Make specification of SDK version clearer
  docs/msbuild/how-to-use-project-sdk.md
Labels: change sent to author, ready-to-merge, tracking (C&L)

#3628 Fix git push error for protected CLA branch
  docs/code-quality/annotating-function-parameters-and-return-values.md
  docs/code-quality/fxcop-analyzers.yml
  docs/debugger/debugging-errors-and-warning-dialog-boxes.md
  docs/debugger/error-debugger-services-no-memory.md
  docs/debugger/toc.yml
  docs/extensibility/set-install-root.md
Labels: do-not-merge

#3635 fix: Convert **Note** to Alert style
  docs/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md
  docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md
  docs/deployment/how-to-specify-the-clickonce-offline-or-online-install-mode.md
  docs/deployment/how-to-specify-the-location-where-end-users-will-install-from.md
  docs/extensibility/internals/reformatting-code-in-a-legacy-language-service.md
  docs/extensibility/ngen-support.md
  docs/extensibility/ux-guidelines/common-control-patterns-for-visual-studio.md
  docs/extensibility/ux-guidelines/fonts-and-formatting-for-visual-studio.md
  docs/extensibility/ux-guidelines/images-and-icons-for-visual-studio.md
  docs/extensibility/walkthrough-creating-a-view-adornment-commands-and-settings-column-guides.md
  docs/ide/class-designer/creating-and-configuring-type-members.md
  docs/modeling/how-to-add-a-command-to-the-shortcut-menu.md
  docs/modeling/how-to-modify-a-standard-menu-command-in-a-domain-specific-language.md
  docs/vs-2015/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md
  docs/vs-2015/code-quality/ca2124-wrap-vulnerable-finally-clauses-in-outer-try.md
  docs/vs-2015/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md
  docs/vs-2015/debugger/walkthrough-writing-a-visualizer-in-csharp.md
  mac/2017/extending-visual-studio-mac.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-sdk/tech

#3633 fix: MD046/code-block-style
  docs/vs-2015/debugger/using-saved-intellitrace-data.md
  docs/vs-2015/modeling/define-a-gesture-handler-on-a-modeling-diagram.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-modeling/tech

#3634 fix: MD047/single-trailing-newline
  subscriptions/admin-responsibilities.md
  subscriptions/cloud-admin.md
  subscriptions/find-pcn.md
  subscriptions/handle-expired-license.md
  subscriptions/includes/gdpr-intro-sentence.md
  subscriptions/join-dev-essentials.md
  subscriptions/maximum-usage.md
  subscriptions/open-migration.md
  subscriptions/personal-email-sign-ins.md
  subscriptions/post-migration-onboarding.md
  subscriptions/program-mpn.md
  subscriptions/program-startups.md
  subscriptions/software-download-list.md
  subscriptions/volume-license-onboarding-email.md
  subscriptions/vs-azure-advisory-chat.md
  subscriptions/vs-azure-community.md
  subscriptions/vs-ems.md
  subscriptions/vs-msdn.md
  subscriptions/vs-office-dev.md
  subscriptions/vs-office365.md
  subscriptions/vs-whitesource.md
  subscriptions/vs-windows-dev.md
  subscriptions/vscloud-billing-faq.md
  subscriptions/vscloud-csp.md
Labels: change sent to author, do-not-merge

#3638 Fix git push error for protected CLA branch
  docs/azure/includes/create-aspnet5-app.md
  docs/azure/includes/vs-2019/create-aspnet5-app-2019.md
  docs/code-quality/ca5361.md
  docs/code-quality/ca5364.md
  docs/code-quality/ca5378.md
  docs/code-quality/ca5386.md
  docs/code-quality/toc.yml
  docs/containers/edit-and-refresh.md
  docs/designers/toc.yml
  docs/extensibility/xaml-designer-extensibility-migration.md
  docs/ide/template-tags.md
  docs/install/includes/install_get_support_md.md
  docs/install/update-servicing-baseline.md
  docs/modeling/toc.yml
  docs/toc.yml
  docs/workflow-designer/toc.yml
  docs/xml-tools/toc.yml
  subscriptions/docfx.json
  subscriptions/vscloud-billing-faq.md
  subscriptions/vscloud-overview.md
  subscriptions/whats-new-in-subscriptions.md
Labels: do-not-merge

#3640 fix: Markdownlint
  docs/containers/edit-and-refresh.md
  docs/install/update-servicing-baseline.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#3644 Fix git push error for protected CLA branch
  docs/ide/class-designer/creating-and-configuring-type-members.md
  docs/install/media/vs-2019/update-settings-options.png
  docs/install/update-visual-studio.md
Labels: do-not-merge

#3650 Fix git push error for protected CLA branch
  docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md
  docs/code-quality/configure-fxcop-analyzers.md
  docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md
  docs/ide/editorconfig-language-conventions.md
  docs/ide/media/code-language-picker.png
  docs/install/update-servicing-baseline.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: do-not-merge

#3651 Fix git push error for protected CLA branch
  docs/toc.yml
  mac/nuget-walkthrough.md
Labels: do-not-merge

#3667 Add project template selection screenshot
  docs/extensibility/creating-custom-project-and-item-templates.md
  docs/extensibility/media/project-template-selection.png
Labels: assessing (C&L), ready-to-merge

#3587 Remove .NET Core limitation for Dependency Validation
  docs/modeling/validate-code-with-layer-diagrams.md
Labels: assessing (C&L), change sent to author, do-not-merge

#3670 Fix git push error for protected CLA branch
  docs/ide/editorconfig-language-conventions.md
  docs/ide/how-to-change-text-case-in-the-editor.md
  subscriptions/_img/manage-vs-subscriptions/alternate-account-resized.png
  subscriptions/_img/manage-vs-subscriptions/alternate-account.png
  subscriptions/_img/manage-vs-subscriptions/change-prefs.png
  subscriptions/_img/manage-vs-subscriptions/change-subscription-resized.png
  subscriptions/_img/manage-vs-subscriptions/current-subscription-cropped.png
  subscriptions/_img/product-keys/download-get-key-cropped.png
  subscriptions/_img/product-keys/download-get-key.PNG
  subscriptions/_img/product-keys/product-keys-page.png
  subscriptions/_img/product-keys/search-keys.png
  subscriptions/_img/product-keys/visio-product-key-cropped.png
  subscriptions/_img/product-keys/visio-product-key.PNG
  subscriptions/_img/subscriber-downloads/subscriber-downloads-resized.png
  subscriptions/_img/subscriber-downloads/vs2017-new-UI.png
  subscriptions/_img/subscriber-downloads/vs2017-pro-claim-keys.png
  subscriptions/_img/subscriber-downloads/vs2017-pro-details.png
  subscriptions/_img/subscriber-downloads/vs2017-pro-keys.png
  subscriptions/_img/subscriber-downloads/vs2019-claim-keys.png
  subscriptions/_img/subscriber-downloads/vs2019-info.png
  subscriptions/_img/subscriber-downloads/vs2019-keys.png
  subscriptions/_img/subscriber-downloads/vs2019-product-list.png
  subscriptions/_img/vs-alternate-identity/add-alternate-account-my-visual-studio-com-portal.png
  subscriptions/_img/vs-alternate-identity/choose-add-alternate-account.png
  subscriptions/_img/vs-alternate-identity/choose-subscriptions-my-visual-studio-com-portal.png
  subscriptions/_img/vs-alternate-identity/my-vs-subscriptions.png
  subscriptions/access-github.md
  subscriptions/activate-store-subscriptions.md
  subscriptions/aliasing.md
  subscriptions/anonymization.md
  subscriptions/download-software.md
  subscriptions/find-keys.md
  subscriptions/internet-demos.md
  subscriptions/manage-vs-subscriptions.md
  subscriptions/product-keys.md
  subscriptions/sign-in-issues.md
  subscriptions/software-download-list.md
  subscriptions/using-the-subscriber-portal.md
  subscriptions/vs-alternate-identity.md
  subscriptions/whats-new-in-subscriptions.md
Labels: do-not-merge

#3658 Added dev_langs
  docs/ide/step-10-write-code-for-additional-buttons-and-a-check-box.md
  docs/ide/step-2-add-a-random-object-and-a-list-of-icons.md
  docs/ide/step-2-create-a-random-addition-problem.md
  docs/ide/step-3-add-a-countdown-timer.md
  docs/ide/step-3-assign-a-random-icon-to-each-label.md
  docs/ide/step-4-add-a-click-event-handler-to-each-label.md
  docs/ide/step-4-add-the-checktheanswer-parens-method.md
  docs/ide/step-5-add-label-references.md
  docs/ide/step-6-add-a-subtraction-problem.md
  docs/ide/step-6-add-a-timer.md
  docs/ide/step-6-name-your-button-controls.md
  docs/ide/step-7-add-multiplication-and-division-problems.md
  docs/ide/step-7-keep-pairs-visible.md
  docs/ide/step-8-add-a-method-to-verify-whether-the-player-won.md
  docs/ide/step-8-customize-the-quiz.md
  docs/ide/step-8-write-code-for-the-show-a-picture-button-event-handler.md
  docs/ide/step-9-review-comment-and-test-your-code.md
Labels: assessing (C&L), change sent to author, ready-to-merge

#3672 Fix indentation
  docs/msbuild/msbuild-inline-tasks.md
Labels: change sent to author, ready-to-merge

#3675 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/c26478.md
  docs/code-quality/c26812.md
  docs/code-quality/c26814.md
  docs/code-quality/toc.yml
  docs/debugger/debug-live-azure-applications.md
  docs/debugger/debug-live-azure-kubernetes.md
  docs/debugger/debug-live-azure-virtual-machines.md
  docs/get-started/csharp/media/tutorial-projects-add-reference-cs.png
  docs/get-started/csharp/media/tutorial-projects-code-cs.png
  docs/get-started/csharp/media/tutorial-projects-new-test-project-cs.png
  docs/get-started/csharp/media/tutorial-projects-properties-cs.png
  docs/get-started/csharp/media/tutorial-projects-solution-explorer-cs.png
  docs/get-started/csharp/toc.yml
  docs/get-started/csharp/tutorial-projects-solutions.md
  docs/get-started/media/tutorial-projects-add-reference.png
  docs/get-started/media/tutorial-projects-netcore-properties.png
  docs/get-started/media/tutorial-projects-solution-explorer.png
  docs/get-started/media/vs-2019/tutorial-projects-blank-solution-template.png
  docs/get-started/media/vs-2019/tutorial-projects-open-installer.png
  docs/get-started/media/vs-2019/tutorial-projects-solution-explorer-reference.png
  docs/get-started/media/vs-2019/tutorial-projects-solution-explorer.png
  docs/get-started/tutorial-projects-solutions.md
  docs/get-started/visual-basic/tutorial-projects-solutions.md
  docs/ide/build-actions.md
  docs/ide/building-and-cleaning-projects-and-solutions-in-visual-studio.md
  docs/ide/compiling-and-building-in-visual-studio.md
  docs/ide/how-to-build-multiple-configurations-simultaneously.md
  docs/ide/how-to-build-to-a-common-output-directory.md
  docs/ide/how-to-change-the-build-output-directory.md
  docs/ide/how-to-configure-projects-to-target-multiple-platforms.md
  docs/ide/how-to-configure-projects-to-target-platforms.md
  docs/ide/how-to-create-and-edit-configurations.md
  docs/ide/how-to-create-and-remove-project-dependencies.md
  docs/ide/how-to-exclude-projects-from-a-build.md
  docs/ide/how-to-manage-build-configurations-with-visual-basic-developer-settings-applied.md
  docs/ide/how-to-set-multiple-startup-projects.md
  docs/ide/how-to-suppress-compiler-warnings.md
  docs/ide/how-to-view-save-and-configure-build-log-files.md
  docs/ide/reference/generate-usings.md
  docs/ide/specifying-custom-build-events-in-visual-studio.md
  docs/ide/understanding-build-configurations.md
  docs/ide/understanding-build-platforms.md
  docs/ide/walkthrough-building-an-application.md
  docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md
  docs/vs-2015/test/analyze-the-code-quality-of-store-apps-using-visual-studio-static-code-analysis.md
  docs/vs-2015/test/analyze-visual-basic-and-csharp-code-quality-in-store-apps-using-visual-studio-static-code-analysis.md
  docs/vs-2015/test/troubleshooting-code-analysis-issues.md
  docs/vs-2015/test/troubleshooting-code-metrics-issues.md
  docs/vs-2015/test/troubleshooting-quality-tools.md
  mac/media/asp-net-core-2019-new-asp-core.png
  subscriptions/TOC.md
  subscriptions/admin-inventory.md
  subscriptions/admin-responsibilities.md
  subscriptions/assignments-orders.md
  subscriptions/manage-teams.md
  subscriptions/maximum-usage.md
Labels: do-not-merge

#3678 Fix git push error for protected CLA branch
  docs/ide/getting-started-with-cpp-in-visual-studio.md
  docs/ide/how-to-sign-application-and-deployment-manifests.md
  docs/ide/how-to-specify-build-events-csharp.md
  docs/ide/how-to-specify-build-events-visual-basic.md
  docs/ide/managing-assembly-and-manifest-signing.md
  docs/ide/media/vs-2019/edge-chromium-breakpoint.png
  docs/ide/media/vs-2019/test-explorer-ui.png
  docs/ide/msbuild-logs.md
  docs/ide/reference/advanced-build-settings-dialog-box-csharp.md
  docs/ide/reference/advanced-compiler-settings-dialog-box-visual-basic.md
  docs/ide/reference/advanced-security-settings-dialog-box.md
  docs/ide/reference/build-events-dialog-box-visual-basic.md
  docs/ide/reference/build-events-page-project-designer-csharp.md
  docs/ide/reference/build-page-project-designer-csharp.md
  docs/ide/reference/compile-page-project-designer-visual-basic.md
  docs/ide/reference/debug-page-project-designer.md
  docs/ide/reference/file-properties-javascript.md
  docs/ide/reference/miscellaneous-files.md
  docs/ide/reference/options-dialog-box-projects-and-solutions-build-and-run.md
  docs/ide/reference/options-text-editor-c-cpp-advanced.md
  docs/ide/reference/options-text-editor-c-cpp-experimental.md
  docs/ide/reference/options-text-editor-c-cpp-formatting.md
  docs/ide/reference/options-text-editor-c-cpp-view.md
  docs/ide/reference/options-text-editor-javascript-code-validation.md
  docs/ide/reference/options-text-editor-javascript-formatting.md
  docs/ide/reference/options-text-editor-javascript-intellisense.md
  docs/ide/reference/options-text-editor-javascript-linting.md
  docs/ide/reference/options-text-editor-javascript-project.md
  docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md
  docs/ide/reference/prerequisites-dialog-box.md
  docs/ide/reference/project-properties-reference.md
  docs/ide/reference/property-pages-javascript.md
  docs/ide/reference/publish-page-project-designer.md
  docs/ide/reference/security-page-project-designer.md
  docs/ide/reference/signing-page-project-designer.md
  docs/ide/reference/vcpp-project-settings-projects-and-solutions-options-dialog-box.md
  docs/ide/report-a-problem-minidumps.md
  docs/ide/report-a-problem-perfview.md
  docs/ide/visual-cpp-code-snippets.md
  docs/ide/visual-cpp-intellisense-configuration.md
  docs/ide/visual-cpp-intellisense.md
  docs/ide/walkthrough-creating-a-multiple-computer-build-environment.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-controller.md
  docs/install/includes/workloads-components-header-2019_md.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/install/workload-and-component-ids.md
Labels: do-not-merge

#3679 Fix git push error for protected CLA branch
  mac/net-core-support.md
Labels: change sent to author, do-not-merge

#3680 Fix git push error for protected CLA branch
  docs/ide/common-quick-actions.md
  docs/ide/how-to-specify-build-events-csharp.md
  docs/ide/media/intellisenseInternalModifier.png
  docs/ide/media/intellisensePrivateModifier.png
  docs/ide/media/intellisenseProtectedInternalModifier.png
  docs/ide/media/intellisenseProtectedModifier.png
  docs/ide/media/intellisensePublicNoModifier.png
  docs/ide/media/quickstart-IDE-solution-explorer.png
  docs/ide/media/vs-2019/send-feedback-menu.png
  docs/ide/quickstart-ide-orientation.md
  docs/ide/refactoring-in-visual-studio.md
  docs/ide/reference/change-method-signature.md
  docs/ide/reference/convert-foreach-linq.md
  docs/ide/reference/convert-linq-to-foreach.md
  docs/ide/reference/extract-method.md
  docs/ide/reference/introduce-local-variable.md
  docs/ide/reference/move-type-to-matching-file.md
  docs/ide/using-intellisense.md
  docs/ide/work-with-multiple-user-accounts.md
  docs/install/create-an-offline-installation-of-visual-studio.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-controller.md
  docs/test/create-a-unit-test-project.md
  docs/test/media/test-project-templates.png
  docs/test/media/vs-2019/test-project-templates.png
  docs/xml-tools/how-to-edit-xml-files.md
Labels: do-not-merge

#3682 fix: MD012/no-multiple-blanks
  docs/code-quality/c26814.md
  docs/debugger/debug-live-azure-applications.md
  docs/extensibility/creating-custom-project-and-item-templates.md
  docs/ide/using-intellisense.md
  subscriptions/internet-demos.md
  subscriptions/manage-teams.md
  subscriptions/manage-vs-subscriptions.md
  subscriptions/maximum-usage.md
  subscriptions/sign-in-msa.md
  subscriptions/whats-new-in-subscriptions.md
Labels: change sent to author, do-not-merge, vs-ide-code-analysis/tech

#3684 Details on new features in the C# editor released VS for Mac 8.1
  mac/media/source-neweditor-image1.png
  mac/media/source-neweditor-image2.png
  mac/media/source-neweditor-wordwrap1.png
  mac/media/source-neweditor-wordwrap2.png
  mac/source-editor.md
Labels: assessing (C&L), do-not-merge

#3685 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2019.md
  docs/modeling/generating-files-with-the-texttransform-utility.md
  docs/test/media/test-driven-development-generate-new-type.png
  docs/test/media/test-driven-development-generate-type-dialog.png
  docs/test/media/test-driven-development-ide.png
  docs/test/media/test-driven-development-passed-test.png
  docs/test/media/test-driven-development-test-detail-summary.png
  docs/test/media/test-driven-development-three-passed-tests.png
  docs/test/quick-start-test-driven-development-with-test-explorer.md
  docs/test/run-unit-tests-with-test-explorer.md
  docs/test/toc.yml
Labels: do-not-merge

#3688 Fix git push error for protected CLA branch
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough1.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough10.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough11b.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough12.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough13.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough14.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough15.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough16.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough17.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough18.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough2.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough3.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough4.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough5.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough6.png
  docs/azure/media/vs-azure-tools-resource-groups-ci-in-vsts/walkthrough9.png
  docs/code-quality/roslyn-analyzers-overview.md
  docs/containers/media/view-and-diagnose-containers/filesystem.png
  docs/cross-platform/media/cppmdd_opengles_iossimulator.png
  docs/data-tools/includes/vsindigo_md.md
  docs/debugger/debugging-preparation-console-projects.md
  docs/debugger/includes/winmobile_md.md
  docs/debugger/media/vs-2019/cpu-use-wt-getmaxnumbercalltree-annotated.png
  docs/debugger/media/vs-2019/cpu-use-wt-showexternalcodetoowide-found.png
  docs/deployment/creating-bootstrapper-packages.md
  docs/deployment/deploying-applications-services-and-components.md
  docs/ide/includes/net_win8_profile_md.md
  docs/ide/media/code-cleanup-options.png
  docs/ide/media/code-cleanup-settings.png
  docs/ide/media/editorconfig-extension-add.png
  docs/ide/media/editorconfig-in-solution-explorer.png
  docs/ide/media/report-an-issue.png
  docs/ide/media/vs_slnexplorer_properties.png
  docs/ide/reference/includes/trprvstoshort_md.md
  docs/ide/reference/includes/vbprvblong_md.md
  docs/ide/reference/prerequisites-dialog-box.md
  docs/install/media/vs-2019/config-file-recommend-install.png
  docs/install/media/vs-2019/export-configuration-vs-installer.png
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
  docs/modeling/code-generation-in-a-build-process.md
  docs/test/media/cpp-cmake-run-tests.png
  docs/test/media/cuit_overview.png
  docs/test/media/unittestexplorer-beta-.png
  docs/test/media/unittestexplorerwalk1.png
  docs/test/media/unittestexplorerwalkthrough2.png
  docs/test/media/unittestexplorerwalkthrough3.png
  docs/test/media/unittestexplorerwalkthrough4.png
  docs/test/media/utecpp01.png
  docs/test/media/utecpp02.png
  docs/test/media/utecpp05.png
  docs/test/media/utecpp08.png
  docs/xml-tools/includes/msconame_md.md
Labels: do-not-merge

#3690 Removed dev_langs
  docs/debugger/diagnostic-messages-in-the-output-window.md
Labels: change sent to author, ready-to-merge

#3696 Fix git push error for protected CLA branch
  docs/cross-platform/change-log-visual-studio-tools-for-unity-mac.md
  docs/cross-platform/change-log-visual-studio-tools-for-unity.md
  docs/debugger/debug-interface-access/namesearchoptions.md
  docs/javascript/npm-package-management.md
  docs/msbuild/msbuild-target-framework-and-target-platform.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/live-unit-testing-faq.md
  docs/test/live-unit-testing.md
  docs/test/load-test-run-settings-properties.md
  docs/test/media/vs-2019/trait-column-filter.png
  docs/test/media/vs-2019/trait-column.png
  docs/test/test-explorer-faq.md
  docs/test/unit-test-basics.md
  docs/test/vstest-console-options.md
  docs/test/walkthrough-writing-unit-tests-for-cpp-dlls.md
Labels: do-not-merge

#3705 Update designing-user-interfaces.md to add XAML Hot Reload
  docs/designers/designing-user-interfaces.md
Labels: change sent to author, do-not-merge

#3706 Update xaml-hot-reload.md - capitalizing Hot Reload to match VS
  docs/debugger/xaml-hot-reload.md
Labels: change sent to author, ready-to-merge
