Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-03, with the labels that each got.

#2789 Fix indent
  docs/extensibility/how-to-register-editor-file-types.md
Labels: change sent to author, do-not-merge

#2790 Delete unnecessary spaces
  docs/vs-2015/code-quality/c26100.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#2799 Delete unnecessary spaces
  docs/vs-2015/code-quality/c26117.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod

#2801 Update t4-include-directive.md
  docs/modeling/t4-include-directive.md
Labels: change sent to author, do-not-merge

#2800 ms-xhelp seems to need 3 slashes
  docs/extensibility/internals/microsoft-help-viewer-sdk.md
Labels: change sent to author, do-not-merge

#2805 fix: MD038/no-space-in-code
  docs/extensibility/ux-guidelines/color-value-reference-for-visual-studio.md
Labels: change sent to author, do-not-merge

#2831 Add the port numbers used by the forwarder on x86
  docs/debugger/remote-debugger-port-assignments.md
Labels: change sent to author, do-not-merge

#2836 Fixed typo in target name
  docs/msbuild/how-to-extend-the-visual-studio-build-process.md
Labels: change sent to author, do-not-merge

#2834 fix MSBuild property function IsOSUnixLike
  docs/msbuild/property-functions.md
Labels: change sent to author, do-not-merge

#2851 Update install-certificates-for-visual-studio-offline.md
  docs/install/install-certificates-for-visual-studio-offline.md
Labels: change sent to author, do-not-merge

#2844 Update walkthrough-analyzing-c-cpp-code-for-defects.md
  docs/code-quality/walkthrough-analyzing-c-cpp-code-for-defects.md
Labels: change sent to author, do-not-merge

#2855 Change quick launch use cases to more real life
  docs/ide/reference/quick-launch-environment-options-dialog-box.md
Labels: change sent to author, do-not-merge

#2852 Update command-line-parameter-examples.md
  docs/install/command-line-parameter-examples.md
Labels: change sent to author, do-not-merge

#2870 Fix dialog title
  docs/ide/filtered-solutions.md
Labels: change sent to author, do-not-merge, visual-studio-dev16/prod

#2905 Clarity Edit
  docs/vsto/walkthrough-designing-an-outlook-form-region.md
Labels: change sent to author, do-not-merge

#2917 Make two small corrections to text.
  docs/modeling/design-time-code-generation-by-using-t4-text-templates.md
Labels: change sent to author, do-not-merge

#2918 Remove a blank line
  docs/msbuild/msbuild-properties.md
Labels: change sent to author, do-not-merge

#2193 Clarify that verification only works for the latest patch level release
  docs/install/update-a-network-installation-of-visual-studio.md
Labels: change sent to author, ready-to-merge, visual-studio-dev15/prod

#2941 Fix git push error for protected CLA branch
  docs/debugger/debugging-absolute-beginners.md
  docs/debugger/get-started-debugging-multithreaded-apps.md
  docs/debugger/how-to-debug-managed-and-native-code.md
  docs/debugger/how-to-use-the-threads-window.md
  docs/debugger/quickstart-debug-with-cplusplus.md
  docs/debugger/quickstart-debug-with-managed.md
  docs/debugger/walkthrough-debugging-a-parallel-application.md
  docs/get-started/csharp/media/vs-2019/csharp-create-aspnet-core-razor-pages-app.png
  docs/get-started/csharp/media/vs-2019/csharp-create-new-project-search-aspnet-core-filtered.png
  docs/get-started/csharp/media/vs-2019/csharp-name-your-aspnet-helloworld-project.png
  docs/get-started/csharp/media/vs-2019/csharp-name-your-aspnet-mycoreapp-project.png
  docs/get-started/csharp/tutorial-aspnet-core.md
  docs/get-started/csharp/tutorial-uwp.md
  docs/get-started/media/aspnet-core-web-dev-workload.png
  docs/ide/quickstart-aspnet-core.md
  docs/ide/whats-new-visual-studio-2017.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/using-visual-studio-vm.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod

#2944 Use consistent names in registry property example
  docs/msbuild/msbuild-properties.md
Labels: change sent to author, ready-to-merge

#2942 Fix Typo
  docs/rtvs/r-projects-in-visual-studio.md
Labels: change sent to author, do-not-merge

#2946 Fix git push error for protected CLA branch
  docs/code-quality/use-roslyn-analyzers.md
  docs/code-quality/using-rule-sets-to-group-code-analysis-rules.md
  docs/containers/vs-azure-tools-docker-hosting-web-apps-in-docker.md
  docs/get-started/visual-basic/media/vs-2019/vb-button-control-text.png
  docs/get-started/visual-basic/media/vs-2019/vb-create-new-project-search-winforms-filtered.png
  docs/get-started/visual-basic/media/vs-2019/vb-name-your-winform-project-helloworld.png
  docs/get-started/visual-basic/tutorial-wpf.md
  docs/ide/create-a-visual-basic-winform-in-visual-studio.md
  docs/ide/step-1-create-a-windows-forms-application-project.md
  docs/index.md
  docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md
  docs/install/install-visual-studio.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/msbuild/clangcompile-task.md
  docs/msbuild/custombuild-task.md
  docs/msbuild/fxc-task.md
  docs/msbuild/getoutofdateitems-task.md
  docs/msbuild/getoutputfilename-task.md
  docs/msbuild/multitooltask-task.md
  docs/msbuild/parallelcustombuild-task.md
  docs/msbuild/trackedvctooltask-base-class.md
  docs/msbuild/vctooltask-base-class.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod

#2921 Xmlns -> xmlns
  docs/msbuild/project-element-msbuild.md
Labels: change sent to author, ready-to-merge

#2954 Update visibilityconstraints-element.md
  docs/extensibility/visibilityconstraints-element.md
Labels: change sent to author, ready-to-merge

#2955 Update FxCop analyzers version to 2.9.1
  docs/code-quality/install-fxcop-analyzers.md
Labels: change sent to author, do-not-merge

#2963 Fix git push error for protected CLA branch
  docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md
  docs/data-tools/create-a-sql-database-by-using-a-designer.md
  docs/data-tools/media/add-connection-access-db.png
  docs/designers/creating-a-ui-by-using-blend-for-visual-studio.md
  docs/designers/creating-a-ui-by-using-xaml-designer-in-visual-studio.md
  docs/designers/media/objects-and-timeline-window.png
  docs/designers/media/rectangle-shape-tool-blend.png
  docs/designers/media/xaml-designer-properties-window.png
  docs/designers/modify-the-style-of-objects-in-blend.md
  docs/get-started/csharp/tutorial-wpf.md
  docs/get-started/media/overview-start-without-debugging.png
  docs/get-started/visual-basic/media/vs-2019/vb-name-your-project-whatname.png
  docs/get-started/visual-basic/tutorial-console.md
  docs/ide/code-styles-and-quick-actions.md
  docs/ide/media/vs-2019/code-style-quick-actions-dialog.png
  docs/ide/media/vs-2019/dark-theme.png
  docs/ide/media/vs-2019/generate-editorconfig-file-small.png
  docs/ide/media/vs-2019/pma-dpi-scaling.png
  docs/ide/quickstart-personalize-the-ide.md
  docs/ide/quickstart-visual-basic-console.md
  docs/ide/reference/documents-environment-options-dialog-box.md
  docs/ide/reference/extensions-and-updates-environment-options-dialog-box.md
  docs/ide/reference/fonts-and-colors-environment-options-dialog-box.md
  docs/ide/reference/general-environment-options-dialog-box.md
  docs/ide/reference/how-to-display-line-numbers-in-the-editor.md
  docs/ide/reference/import-and-export-settings-environment-options-dialog-box.md
  docs/ide/reference/international-settings-environment-options-dialog-box.md
  docs/ide/reference/keyboard-environment-options-dialog-box.md
  docs/ide/reference/media/line-numbers-option.png
  docs/ide/reference/options-dialog-box-projects-and-solutions-build-and-run.md
  docs/ide/reference/startup-environment-options-dialog-box.md
  docs/ide/reference/tabs-and-windows-environment-options-dialog-box.md
  docs/ide/reference/task-list-environment-options-dialog-box.md
  docs/ide/reference/web-browser-environment-options-dialog-box.md
  docs/ide/step-1-create-a-project-and-add-a-table-to-your-form.md
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/ide/step-1-create-a-windows-forms-application-project.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/create-an-offline-installation-of-visual-studio.md
  docs/install/media/vs-2019/download-all-then-install-from-ide.png
  docs/install/media/vs-2019/download-all-then-install-from-installer.png
  docs/install/using-visual-studio-vm.md
  docs/javascript/debug-nodejs.md
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
  docs/test/media/create-unit-tests.png
  docs/test/unit-test-basics.md
  mac/2017/index.yml
Labels: do-not-merge

#2965 Fix git push error for protected CLA branch
  docs/designers/creating-a-ui-by-using-xaml-designer-in-visual-studio.md
  docs/designers/media/document-outline-window.png
Labels: do-not-merge
