Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-11, with the labels that each got.

#3938 Add documentation for AssemblyMetadata item
  docs/msbuild/common-msbuild-project-items.md
Labels: assessing_(C&L), change sent to author, ready-to-merge

#4265 Fix git push error for protected CLA branch
  docs/debugger/media/dbg-options-symbols.gif
  docs/debugger/media/dbg-options-symbols.png
  docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md
  docs/javascript/quickstart-vuejs-with-nodejs.md
  docs/javascript/tutorial-nodejs.md
Labels: do-not-merge

#4266 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/ca2301.md
  docs/code-quality/ca2302.md
  docs/code-quality/ca2311.md
  docs/code-quality/ca2312.md
  docs/code-quality/ca2327.md
  docs/code-quality/ca2328.md
  docs/code-quality/ca2329.md
  docs/code-quality/ca2330.md
Labels: do-not-merge

#4274 Fix git push error for protected CLA branch
  docs/debugger/debugger-feature-tour.md
  docs/debugger/find-your-debugging-task.md
Labels: do-not-merge

#4267 Update install-roslyn-analyzers.md
  docs/code-quality/install-roslyn-analyzers.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#4282 Fix git push error for protected CLA branch
  docs/javascript/debug-nodejs.md
  docs/javascript/media/tutorial-nodejs-react-set-breakpoint-in-tsx-file.png
  docs/javascript/quickstart-ide-orientation-js.md
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
Labels: do-not-merge

#4286 Fix git push error for protected CLA branch
  docs/debugger/run-windows-store-apps-in-the-simulator.md
  docs/install/troubleshooting-network-related-errors-in-visual-studio.md
  docs/python/managing-python-environments-in-visual-studio.md
  docs/python/python-support-options-and-settings-in-visual-studio.md
  docs/python/visual-studio-ide.md
  docs/sharepoint/sharepoint-project-and-project-item-templates.md
  docs/sharepoint/troubleshooting-sharepoint-solutions.md
  docs/sharepoint/walkthrough-deploying-a-project-task-list-definition.md
  docs/vsto/excel-object-model-overview.md
  docs/vsto/improving-the-performance-of-a-vsto-add-in.md
Labels: do-not-merge

#4291 Fix git push error for protected CLA branch
  docs/ide/media/vs-2019/csharp-aspnet-generic-iisbutton.png
  docs/ide/media/vs-2019/csharp-aspnet-index-cshtml-page-hello-world.png
  docs/ide/media/vs-2019/csharp-aspnet-index-cshtml-page.png
  docs/ide/media/vs-2019/csharp-aspnet-index-page-cshtml-file.png
  docs/ide/media/vs-2019/csharp-aspnet-index-page-hello-world.png
  docs/ide/media/vs-2019/csharp-aspnet-index-page.png
  docs/ide/quickstart-aspnet-core.md
Labels: do-not-merge

#4300 Fix git push error for protected CLA branch
  docs/javascript/debug-nodejs.md
Labels: do-not-merge

#4301 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md
  docs/extensibility/media/xaml-designer-extensibility-migration-architecture.png
  docs/extensibility/toc.yml
  docs/extensibility/xaml-designer-extensibility-migration.md
  docs/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio.md
Labels: do-not-merge

#3937 Documents InternalsVisibleTo item
  docs/msbuild/common-msbuild-project-items.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4309 Fix git push error for protected CLA branch
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/modeling/directed-graph-markup-language-dgml-reference.md
  docs/msbuild/msbuild-dot-targets-files.md
  docs/profiling/da0001-use-stringbuilder-for-concatenations.md
  docs/sharepoint/security-for-sharepoint-solutions.md
  docs/sharepoint/walkthrough-creating-and-debugging-a-sharepoint-workflow-solution.md
  docs/vs-2015/extensibility/debugger/visual-studio-debugger-extensibility.md
  docs/vs-2015/install/how-to-locate-the-visual-studio-product-key.md
  docs/vs-2015/profiling/profiling-on-hpc-high-performance-computing-clusters.md
  subscriptions/vs-azure-community.md
  subscriptions/vs-azure-devops.md
  subscriptions/vs-azure.md
  subscriptions/vs-cast.md
Labels: do-not-merge

#4326 Fix git push error for protected CLA branch
  docs/ide/index-writing-code.yml
  docs/toc.yml
Labels: do-not-merge

#4327 Fix git push error for protected CLA branch
  docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  subscriptions/vs-cloudpilot.md
  subscriptions/vs-code-magazine.md
  subscriptions/vs-concierge-chat.md
  subscriptions/vs-datacamp.md
  subscriptions/vs-ems.md
  subscriptions/vs-ide-benefit.md
  subscriptions/vs-linkedin-learning.md
  subscriptions/vs-m365.md
  subscriptions/vs-office365.md
Labels: do-not-merge

#4332 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/_breadcrumb/toc.yml
  docs/index.yml
  docs/media/vs-code-logo.svg
  docs/media/vs-ide-2019.svg
  docs/media/vs-mac-2019.svg
  docs/media/vs-mobile-center.svg
  docs/media/vs-subscription-temp.svg
  docs/products/images/vs-code-logo.svg
  docs/products/images/vs-ide-2019.svg
  docs/products/images/vs-mac-2019.svg
  docs/products/images/vs-mobile-center.svg
  docs/products/images/vs-subscription-temp.svg
  docs/products/images/vs-team-services.svg
  docs/products/index.md
  docs/windows/index.yml
Labels: do-not-merge

#4338 Remove indentation from paragraph
  docs/debugger/remote-debugger-port-assignments.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4336 Update unity-scripting-upgrade.md
  docs/cross-platform/unity-scripting-upgrade.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-unity-tools/tech

#4345 Fix git push error for protected CLA branch
  subscriptions/vs-parasoft.md
  subscriptions/vs-pbi.md
  subscriptions/vs-pluralsight.md
  subscriptions/vs-tech-support.md
  subscriptions/vs-visual-studio-app-center.md
Labels: do-not-merge

#4347 Fix git push error for protected CLA branch
  docs/ai/create-project-gallery.md
  docs/debugger/graphics/16bpp-render-target-format-variant.md
  docs/install/using-visual-studio-vm.md
  subscriptions/vs-whitesource.md
  subscriptions/vs-windows-dev.md
Labels: do-not-merge

#4353 Fix git push error for protected CLA branch
  docs/get-started/csharp/index.yml
  docs/get-started/visual-basic/index.yml
Labels: do-not-merge

#4356 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  subscriptions/TOC.md
  subscriptions/_img/vs-msdn/vs-msdn-confirmation.PNG
  subscriptions/_img/vs-msdn/vs-msdn-profile.PNG
  subscriptions/_img/vs-msdn/vs-msdn-subs-page-resized.png
  subscriptions/_img/vs-msdn/vs-msdn-subs-page.PNG
  subscriptions/_img/vs-msdn/vs-msdn-tile.PNG
  subscriptions/_img/vs-rstudio/vs-rstudio-apply-code unblocked.png
  subscriptions/_img/vs-rstudio/vs-rstudio-apply-code.png
  subscriptions/_img/vs-rstudio/vs-rstudio-choose-version.png
  subscriptions/_img/vs-rstudio/vs-rstudio-complete.png
  subscriptions/_img/vs-rstudio/vs-rstudio-cran-page.png
  subscriptions/_img/vs-rstudio/vs-rstudio-dashboard.png
  subscriptions/_img/vs-rstudio/vs-rstudio-destination.png
  subscriptions/_img/vs-rstudio/vs-rstudio-installer.png
  subscriptions/_img/vs-rstudio/vs-rstudio-landing-page.png
  subscriptions/_img/vs-rstudio/vs-rstudio-not-installed.png
  subscriptions/_img/vs-rstudio/vs-rstudio-plan-summary.png
  subscriptions/_img/vs-rstudio/vs-rstudio-progress.png
  subscriptions/_img/vs-rstudio/vs-rstudio-start-folder.png
  subscriptions/_img/vs-rstudio/vs-rstudio-tile.png
  subscriptions/_img/vs-rstudio/vs-rstudio-wizard.png
  subscriptions/vs-datacamp.md
  subscriptions/vs-msdn.md
  subscriptions/vs-rstudio.md
Labels: do-not-merge

#4358 Spelling correction and sentence improvement
  subscriptions/admin-inventory.md
  subscriptions/admin-responsibilities.md
  subscriptions/assignments-orders.md
  subscriptions/contact-my-admin.md
  subscriptions/delete-license.md
  subscriptions/exporting-subscriptions.md
  subscriptions/manage-teams.md
  subscriptions/maximum-usage.md
  subscriptions/program-mpn.md
  subscriptions/volume-license.md
  subscriptions/vs-code-magazine.md
  subscriptions/vs-ide-benefit.md
  subscriptions/vs-pluralsight.md
  subscriptions/vs-windows-dev.md
  subscriptions/vscloud-billing-faq.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4368 Update - Installing a Visualizer
  docs/debugger/how-to-install-a-visualizer.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4352 MSBuild: Say "dotnet build" in MSBuildRuntimeType
  docs/msbuild/msbuild-reserved-and-well-known-properties.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4375 Fix git push error for protected CLA branch
  docs/code-quality/fxcop-analyzers.yml
  docs/code-quality/index.yml
  docs/data-tools/codesnippet/CSharp/CreateWPFDataApp/NorthwindModel.Designer.cs
  docs/extensibility/how-to-roundtrip-VSIXs.md
  docs/ide/index-writing-code.yml
  docs/ide/index.yml
  docs/ide/navigating-code.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/msbuild/how-to-build-incrementally.md
  docs/msbuild/how-to-specify-which-target-to-build-first.md
  docs/xaml-tools/index.yml
Labels: do-not-merge

#4379 Fix XML code
  docs/msbuild/target-element-msbuild.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4392 Fix git push error for protected CLA branch
  docs/javascript/publish-nodejs-app-azure.md
Labels: do-not-merge

#4394 Fix git push error for protected CLA branch
  docs/ide/csharp-developer-productivity.md
  docs/ide/how-to-increase-chances-of-performance-issue-being-fixed.md
  docs/ide/media/configure-severity-level.png
  docs/toc.yml
  subscriptions/program-mpn.md
Labels: do-not-merge

#4395 Fix git push error for protected CLA branch
  docs/code-quality/analyzer-rule-sets.md
  docs/containers/index.yml
  docs/ide/codeindex-command.md
  docs/ide/connect-team-project.md
  docs/ide/find-code-changes-and-other-history-with-codelens.md
  docs/ide/reference/team-explorer-reference.md
  docs/vs-2015/cross-platform/setup-install-and-verifications-for-mac-users.md
  docs/vs-2015/welcome-to-visual-studio-2015.md
  docs/vs-2015/what-s-new-in-visual-studio-2015.md
Labels: do-not-merge

#4407 Fix git push error for protected CLA branch
  docs/install/modify-visual-studio.md
  docs/vsto/includes/new-project-dialog-search-md.md
  docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md
  docs/vsto/walkthrough-creating-your-first-document-level-customization-for-word.md
Labels: do-not-merge
