Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-12, with the labels that each got.

#4385 Fix sample code
  docs/msbuild/item-metadata-in-task-batching.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4412 fix a broken link
  docs/debugger/how-can-i-find-out-if-my-pointers-corrupt-a-memory-address-q.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4413 Fix git push error for protected CLA branch
  docs/profiling/how-to-specify-symbol-file-locations-from-the-command-line.md
  docs/test/writing-unit-tests-for-c-cpp.md
Labels: do-not-merge

#4418 removed duplicate word
  scripting-docs/winscript/active-script-profiling-overview.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4420 Remove bullet points from section descriptions.
  docs/deployment/building-clickonce-applications-from-the-command-line.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4424 Fix git push error for protected CLA branch
  docs/code-quality/ca5369.md
  docs/ide/media/vs-2019/debugger-pinnable-properties.gif
  docs/ide/reference/add-null-checks-for-parameters.md
  docs/ide/reference/media/add-null-checks-for-all-parameters.png
  docs/ide/reference/media/add-null-checks-for-all.png
  docs/ide/reference/media/make-local-function-static.png
  docs/ide/reference/media/pass-variable-explicitly-static-local-function.png
  docs/ide/reference/static-local-function-refactor-options.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/javascript/debug-nodejs.md
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/media/vs-2019/auto-detect-runsettings-menu.png
  docs/test/media/vs-2019/auto-detect-runsettings-tools-window.png
  docs/test/media/vs-2019/select-solution-settings-file.png
Labels: do-not-merge

#4425 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: do-not-merge

#4323 Update finding-memory-leaks-using-the-crt-library.md
  docs/debugger/finding-memory-leaks-using-the-crt-library.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4369 Update c6067.md
  docs/code-quality/c6067.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4430 Fix git push error for protected CLA branch
  docs/cross-platform/media/unity-diagnostics.png
  docs/cross-platform/visual-studio-tools-for-unity.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/install/workload-component-id-vs-build-tools.md
  docs/install/workload-component-id-vs-community.md
  docs/install/workload-component-id-vs-enterprise.md
  docs/install/workload-component-id-vs-professional.md
  docs/install/workload-component-id-vs-team-explorer.md
  docs/install/workload-component-id-vs-test-agent.md
  docs/install/workload-component-id-vs-test-controller.md
  docs/msbuild/how-to-ignore-errors-in-tasks.md
  mac/media/using-vsmac-tools-unity-image9.png
  mac/unity-tools.md
  subscriptions/assign-license.md
Labels: do-not-merge

#4434 Fix git push error for protected CLA branch
  docs/code-quality/ca1031.md
  docs/code-quality/ca1062.md
  docs/code-quality/ca1303.md
  docs/code-quality/ca1801.md
  docs/code-quality/ca1802.md
  docs/code-quality/ca2000.md
  docs/code-quality/ca2100.md
  docs/code-quality/ca2241.md
  docs/code-quality/ca2301.md
  docs/code-quality/ca2302.md
  docs/code-quality/ca2311.md
  docs/code-quality/ca2312.md
  docs/code-quality/ca2321.md
  docs/code-quality/ca2322.md
  docs/code-quality/ca2327.md
  docs/code-quality/ca2328.md
  docs/code-quality/ca2329.md
  docs/code-quality/ca2330.md
  docs/code-quality/ca3001.md
  docs/code-quality/ca3002.md
  docs/code-quality/ca3003.md
  docs/code-quality/ca3004.md
  docs/code-quality/ca3005.md
  docs/code-quality/ca3006.md
  docs/code-quality/ca3007.md
  docs/code-quality/ca3008.md
  docs/code-quality/ca3009.md
  docs/code-quality/ca3010.md
  docs/code-quality/ca3011.md
  docs/code-quality/ca3012.md
  docs/code-quality/ca5361.md
  docs/code-quality/ca5378.md
  docs/code-quality/ca5380.md
  docs/code-quality/ca5381.md
  docs/code-quality/ca5389.md
  docs/code-quality/fxcop-analyzer-options.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/media/locate-the-visual-studio-installer.png
  docs/install/media/modify-workloads.png
  docs/install/media/vs-2019/vs-installer-modify-workloads.png
  docs/install/media/vs-2019/vs-installer-modify.png
  docs/install/modify-visual-studio.md
  docs/install/uninstall-visual-studio.md
  subscriptions/vs-azure.md
Labels: do-not-merge

#4437 Fix git push error for protected CLA branch
  docs/get-started/csharp/tutorial-console.md
  docs/get-started/csharp/tutorial-debugger.md
  docs/get-started/visual-basic/tutorial-console.md
  docs/get-started/visual-basic/tutorial-debugger.md
  docs/install/using-visual-studio-vm.md
  mac/_breadcrumb/toc.yml
  mac/index.yml
Labels: do-not-merge

#4440 Fix git push error for protected CLA branch
  docs/ide/feedback-options.md
  docs/ide/report-a-problem.md
  docs/ide/suggest-a-feature.md
  docs/toc.yml
Labels: do-not-merge

#4442 Fix git push error for protected CLA branch
  docs/sharepoint/creating-sharepoint-solution-packages.md
  docs/sharepoint/includes/new-project-dialog-search-md.md
  docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md
  docs/vsto/codesnippet/CSharp/Trin_OL_SearchEmail/thisaddin.cs
  subscriptions/TOC.md
  subscriptions/_breadcrumb/toc.yml
  subscriptions/docfx.json
  subscriptions/index.md
  subscriptions/index.yml
  subscriptions/using-admin-portal.md
Labels: do-not-merge

#4449 Fix git push error for protected CLA branch
  docs/debugger/autos-and-locals-windows.md
  docs/debugger/just-in-time-debugging-in-visual-studio.md
  docs/debugger/media/basic-pin-datatip.gif
  docs/debugger/media/basic-pin-watch.gif
  docs/debugger/media/basic-pin.gif
  docs/debugger/media/filter-favorites.gif
  docs/debugger/media/filter-pinned-properties-locals.png
  docs/debugger/media/filter-pinned-properties.png
  docs/debugger/media/toggle-property-names.gif
  docs/debugger/view-data-values-in-data-tips-in-the-code-editor.md
  docs/debugger/watch-and-quickwatch-windows.md
  docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md
  docs/ide/how-to-increase-chances-of-performance-issue-being-fixed.md
  docs/install/using-visual-studio-vm.md
Labels: do-not-merge

#4450 Remove unused languages from dev_langs
  docs/debugger/finding-memory-leaks-using-the-crt-library.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4453 Fix git push error for protected CLA branch
  docs/debugger/toc.yml
  docs/debugger/troubleshoot-data-breakpoint-errors.md
  docs/vsto/registry-entries-for-vsto-add-ins.md
Labels: do-not-merge

#4454 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2017.md
  docs/vsto/registry-entries-for-vsto-add-ins.md
Labels: do-not-merge

#4464 Fix git push error for protected CLA branch
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: do-not-merge

#4475 Fix formatting of ruleset configuration
  docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4486 Fix git push error for protected CLA branch
  docs/code-quality/ca2214.md
Labels: do-not-merge

#4478 Update azure-functions-lab.md
  mac/azure-functions-lab.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-install/tech

#4490 Fix git push error for protected CLA branch
  docs/extensibility/extensibility-hello-world.md
  docs/extensibility/media/hello-world-vsix-command.png
Labels: do-not-merge

#4493 Fix git push error for protected CLA branch
  docs/debugger/media/dbg_basics_break_mode.png
  docs/debugger/media/dbg_basics_start_debugging.png
  docs/debugger/media/filter-favorites.gif
  docs/debugger/media/filter-pinned-properties.png
  docs/extensibility/media/extension-compatibility-options.png
  docs/extensibility/media/extension-compatibility-warning.png
  docs/extensibility/media/hello-world-custom-command.png
  docs/get-started/csharp/media/vs-2019/csharp-create-aspnet-core-razor-pages-app.png
  docs/test/media/lut-start/add-project-vb.png
  docs/test/media/lut-start/add-unit-test-vb.png
  docs/test/media/lut-start/code-coverage-vb1.png
  docs/test/media/lut-start/code-coverage-vb2.png
  docs/test/media/lut-start/debugging-tools-vb.png
  docs/test/media/lut-start/exception-dialog-vb.png
  docs/test/media/lut-start/lut-extended-vb.png
  docs/test/media/lut-start/lut-results-vb.png
  docs/test/media/lut-start/test-failure-info-vb.png
  docs/test/media/lut-start/test-success-vb.png
  docs/test/media/lut-start/vb-properties.png
Labels: do-not-merge

#4307 Number for supressing warning "0168" corrected
  docs/ide/walkthrough-building-an-application.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-ide-compile/tech

#4472 Add doc for collecting ServiceHub logs
  docs/ide/how-to-increase-chances-of-performance-issue-being-fixed.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4330 Fixed the markdown for the VS2019 table
  docs/containers/container-launch-settings.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-azure/tech

#4495 Updating Python Workload installation links for 2010, 2012, 2013
  docs/python/installing-python-support-in-visual-studio.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4251 Update walkthrough-highlighting-text.md
  docs/extensibility/walkthrough-highlighting-text.md
Labels: assessing_(C&L), change sent to author, do-not-merge

#4435 Update naming convention example
  docs/ide/editorconfig-naming-conventions.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#4497 Fix git push error for protected CLA branch
  docs/install/install-visual-studio.md
  docs/install/media/vs-2019/vs-installer-individual-components.png
  docs/install/media/vs-2019/vs-installer-language-packs.png
  docs/install/media/vs-2019/vs-installer-modify.png
  docs/install/media/vs-2019/vs-installer-workloads.png
  mac/asp-net-core.md
  mac/media/asp-net-web-picker.png
Labels: do-not-merge

#4508 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2019.md
Labels: do-not-merge

#4280 Updating missing dependency validation error codes
  docs/modeling/validate-code-with-layer-diagrams.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4512 Fix git push error for protected CLA branch
  mac/building-asp-net-core.md
  mac/debugging.md
  mac/ide-tour.md
  mac/media/debugging-image0.png
  mac/media/debugging-image0a.png
  mac/media/debugging-image1.png
  mac/media/debugging-image2.png
  mac/media/debugging-image5.png
  mac/media/debugging-image8.png
  mac/media/debugging-image_0.png
  mac/media/netcore-build-nested.png
  mac/set-startup-projects.md
  mac/using-vsmac-tools-unity.md
Labels: do-not-merge

#4510 fix extra whitespace
  docs/code-quality/codesnippet/CSharp/ca2229-implement-serialization-constructors_1.cs
Labels: assessing_(C&L), ready-to-merge, review-team-triage

#4502 Update debugbreak-and-debugbreak.md
  docs/debugger/debugbreak-and-debugbreak.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4517 Fix git push error for protected CLA branch
  docs/ide/how-to-unlock-visual-studio.md
  docs/porting/port-migrate-and-upgrade-visual-studio-projects.md
Labels: do-not-merge

#4417 Add IntermediateOutputPath
  docs/test/live-unit-testing-faq.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4519 Fix git push error for protected CLA branch
  docs/code-quality/how-to-create-or-update-standard-code-analysis-check-in-policies.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/test/intellitest-manual/introduction.md
  docs/test/live-unit-testing.md
  mac/TOC.md
  mac/media/project-multitargeting-framework-selector.png
  mac/media/project-multitargeting-intellisense-warnings.png
  mac/media/source-link1.png
  mac/media/source-link2.png
  mac/project-multitargeting.md
  mac/source-link.md
Labels: do-not-merge

#4532 Fix git push error for protected CLA branch
  docs/code-quality/annotating-locking-behavior.md
  docs/code-quality/ca1001.md
  docs/code-quality/ca1707.md
  docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md
  docs/debugger/troubleshoot-data-breakpoint-errors.md
  docs/vs-2015/xml-tools/xslt-profiler.md
  subscriptions/_img/vs-azure/vs-azure-about-you.png
  subscriptions/_img/vs-azure/vs-azure-agreement.png
  subscriptions/_img/vs-azure/vs-azure-dashboard-quickstart.png
  subscriptions/_img/vs-azure/vs-azure-getting-ready-cropped.png
  subscriptions/_img/vs-azure/vs-azure-identity.png
  subscriptions/_img/vs-azure/vs-azure-quick-start.png
  subscriptions/_img/vs-azure/vs-azure-sign-up-cropped.png
  subscriptions/vs-azure.md
Labels: do-not-merge

#4534 Fix git push error for protected CLA branch
  docs/code-quality/ca1001.md
  docs/code-quality/ca1802.md
  docs/code-quality/ca2002.md
  docs/code-quality/ca2213.md
  docs/install/media/vs-2019/modify-update-visual-studio.png
  docs/install/modify-visual-studio.md
Labels: do-not-merge

#4539 Fix git push error for protected CLA branch
  docs/install/remove-visual-studio.md
  docs/install/uninstall-visual-studio.md
  mac/extending-visual-studio-mac.md
  mac/updater-troubleshooting.md
Labels: do-not-merge

#4536 Added missing semi-colon
  docs/xml-tools/debugging-xslt.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-javascript/tech

#4540 Fix git push error for protected CLA branch
  docs/code-quality/ca1003.md
  docs/code-quality/ca1062.md
Labels: do-not-merge

#4553 Fix git push error for protected CLA branch
  subscriptions/manage-mpn-subscriptions.md
Labels: do-not-merge

#4568 Fix git push error for protected CLA branch
  subscriptions/using-the-subscriber-portal.md
Labels: do-not-merge

#4567 Fix see also section
  docs/vs-2015/ide/reference/options-page-environment-node-properties.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-general/tech

#4570 Fix git push error for protected CLA branch
  docs/vs-2015/porting/porting-migrating-and-upgrading-visual-studio-projects.md
Labels: do-not-merge

#4573 Fix git push error for protected CLA branch
  docs/misc/includes/gdpr-hybrid-note.md
Labels: do-not-merge
