Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-05, with the labels that each got.

#3196 Fix spelling
  docs/deployment/security-versioning-and-manifest-issues-in-clickonce-deployments.md
Labels: change sent to author, do-not-merge, triaged

#3195 chore: Remove Markdown HR rendered on page
  scripting-docs/index.md
Labels: change sent to author, do-not-merge, triaged, visual-studio-windows/prod, vs-ide-nodejs/tech

#3180 Update code-analysis-for-c-cpp-overview.md
  docs/code-quality/code-analysis-for-c-cpp-overview.md
Labels: change sent to author, do-not-merge, triaged

#3179 Update adding-a-submenu-to-a-menu.md
  docs/extensibility/adding-a-submenu-to-a-menu.md
Labels: change sent to author, ready-to-merge, triaged

#3169 Remove duplicate link
  docs/vsto/using-wpf-controls-in-office-solutions.md
Labels: change sent to author, do-not-merge, triaged

#3207 Add missing 'to'
  mac/installation.md
Labels: change sent to author, ready-to-merge, vs-ide-install/tech

#3202 fix: Deploy a C/C++ app link
  docs/deployment/index.md
Labels: change sent to author, ready-to-merge

#3223 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/modeling/add-commands-and-gestures-to-layer-diagrams.md
  docs/modeling/add-custom-architecture-validation-to-layer-diagrams.md
  docs/modeling/analyze-and-model-your-architecture.md
  docs/modeling/creating-custom-t4-text-template-directive-processors.md
  docs/modeling/customizing-and-extending-a-domain-specific-language.md
  docs/modeling/customizing-presentation-on-the-diagram.md
  docs/modeling/deploying-domain-specific-language-solutions.md
  docs/modeling/design-time-code-generation-by-using-t4-text-templates.md
  docs/modeling/extend-layer-diagrams.md
  docs/modeling/generating-code-from-a-domain-specific-language.md
  docs/modeling/modeling-sdk-for-visual-studio-domain-specific-languages.md
  docs/modeling/properties-of-model-elements.md
  docs/modeling/responding-to-and-propagating-changes.md
  docs/modeling/scenario-change-your-design-using-visualization-and-modeling.md
  docs/modeling/t4-text-template-directives.md
  docs/modeling/toc.yml
  docs/modeling/using-escape-sequences-in-text-templates.md
  docs/modeling/validate-your-system-during-development.md
  docs/modeling/what-s-new-for-design-in-visual-studio.md
  docs/modeling/working-with-domain-specific-language-solutions.md
  docs/modeling/writing-user-commands-and-actions.md
  docs/workflow-designer/toc.yml
  docs/workflow-designer/using-the-activity-designers.md
  docs/workflow-designer/workflow-designer-ui-help.md
Labels: do-not-merge

#3226 Update import-element-msbuild.md
  docs/msbuild/import-element-msbuild.md
Labels: change sent to author, ready-to-merge

#3224 Update configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
Labels: change sent to author, do-not-merge

#3237 Changed Find the specific object instance in the **Locals** window to…
  docs/debugger/using-breakpoints.md
Labels: change sent to author, ready-to-merge

#3232 Update vcremote setup and requirements
  docs/cross-platform/install-and-configure-tools-to-build-using-ios.md
Labels: change sent to author, do-not-merge, vs-ide-mobile/tech

#3243 The link to Visual Studio for Mac workloads is broken
  mac/ide-tour.md
Labels: change sent to author, ready-to-merge

#3244 Fix for Visual Studio for Mac Workloads link from VS for Mac 2019 installation page
  mac/installation.md
Labels: change sent to author, ready-to-merge, vs-ide-install/tech

#3248 Fixed NuGet package id for Microsoft.Build.Utilities.Core
  docs/msbuild/updating-an-existing-application.md
Labels: change sent to author, needs-more-info, ready-to-merge

#3254 Change project string wrapper character from ` to '
  docs/msbuild/property-functions.md
Labels: change sent to author, do-not-merge

#3255 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/analyzer-rule-sets.md
  docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md
  docs/code-quality/how-to-create-a-custom-rule-set.md
  docs/code-quality/media/diagnostics-severity-colors.png
  docs/code-quality/toc.yml
  docs/code-quality/use-roslyn-analyzers.md
  docs/debugger/debugger-feature-tour.md
  docs/debugger/debugging-absolute-beginners.md
  docs/debugger/getting-started-with-the-debugger-cpp.md
  docs/debugger/how-to-debug-managed-and-native-code.md
  docs/debugger/quickstart-debug-aspnet.md
  docs/debugger/quickstart-debug-with-cplusplus.md
  docs/debugger/quickstart-debug-with-managed.md
  docs/debugger/view-historical-application-state.md
  docs/debugger/view-snapshots-with-intellitrace.md
  docs/debugger/walkthrough-debugging-a-windows-form.md
  docs/deployment/deploying-applications-services-and-components.md
  docs/deployment/quickstart-deploy-to-a-web-site.md
  docs/deployment/quickstart-deploy-to-azure.md
  docs/deployment/quickstart-deploy-to-linux.md
  docs/deployment/quickstart-deploy-to-local-folder.md
  docs/deployment/tutorial-import-publish-settings-azure.md
  docs/deployment/tutorial-import-publish-settings-iis.md
  docs/get-started/csharp/tutorial-debugger.md
  docs/get-started/visual-basic/tutorial-debugger.md
  docs/install/install-visual-studio.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/javascript/publish-nodejs-app-azure.md
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
  docs/javascript/tutorial-nodejs.md
  docs/profiling/beginners-guide-to-performance-profiling.md
  docs/profiling/memory-usage.md
  docs/profiling/profiling-feature-tour.md
  docs/profiling/quickstart-cpu-usage-aspnet.md
  docs/profiling/quickstart-cpu-usage-managed.md
  docs/profiling/quickstart-cpu-usage-native.md
  docs/test/includes/coded-ui-test-deprecation.md
  docs/test/media/test-explorer-banktests-passed.png
  docs/test/sample-project-for-creating-unit-tests.md
  docs/test/toc.yml
  docs/test/use-ui-automation-to-test-your-code.md
  docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md
  subscriptions/subscriber-downloads.md
  subscriptions/vs-office-dev.md
  subscriptions/vscloud-overview.md
Labels: do-not-merge

#3263 Fix git push error for protected CLA branch
  docs/code-quality/ca2000-dispose-objects-before-losing-scope.md
  docs/code-quality/ca2213-disposable-fields-should-be-disposed.md
  docs/debugger/graphics/graphics-event-list.md
  docs/debugger/includes/remote-debugger-download.md
  docs/extensibility/adding-an-lsp-extension.md
  docs/extensibility/toc.yml
  docs/ide/adding-visual-studio-editor-support-for-other-languages.md
  docs/ide/how-to-change-the-build-output-directory.md
  docs/ide/media/build-configuration-chooser.png
  docs/ide/media/output-path.png
  docs/install/import-export-installation-configurations.md
  subscriptions/program-mpn.md
  subscriptions/signing-in.md
  subscriptions/vs-cast.md
  subscriptions/vs-cloudpilot.md
Labels: do-not-merge

#3157 Add missing word
  docs/deployment/deploying-applications-services-and-components.md
Labels: change sent to author, do-not-merge

#3171 Updated CustomBuild task
  docs/msbuild/custombuild-task.md
Labels: change sent to author, do-not-merge

#3010 Two sgen msbuild properties on the page are for desktop use only
  docs/msbuild/common-msbuild-project-properties.md
Labels: change sent to author, ready-to-merge

#3197 Update C26432.md
  docs/code-quality/C26409.md
  docs/code-quality/C26432.md
Labels: change sent to author, do-not-merge, ready-to-merge

#3274 Grammatical corrections
  mac/ide-tour.md
Labels: change sent to author, do-not-merge

#3276 Fix git push error for protected CLA branch
  docs/ide/finding-and-using-visual-studio-extensions.md
  docs/test/how-to-use-microsoft-test-framework-for-cpp.md
  docs/test/run-unit-tests-with-test-explorer.md
  subscriptions/vs-office-dev.md
Labels: change sent to author, do-not-merge

#3283 Fix git push error for protected CLA branch
  docs/code-quality/ca1507.md
  docs/code-quality/ca2208-instantiate-argument-exceptions-correctly.md
  docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md
  docs/code-quality/codesnippet/CSharp/ca2208-instantiate-argument-exceptions-correctly_1.cs
  docs/code-quality/codesnippet/CSharp/ca2208-instantiate-argument-exceptions-correctly_2.cs
  docs/code-quality/extended-design-guidelines-rules-rule-set-for-managed-code.md
  docs/code-quality/maintainability-warnings.md
  docs/code-quality/media/ca1507-code-fix.png
  docs/code-quality/reliability-warnings.md
  docs/code-quality/toc.yml
  docs/ide/media/vs-2019/pma-dpi-scaling.png
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md
  docs/install/troubleshooting-network-related-errors-in-visual-studio.md
  docs/install/visual-studio-administrator-guide.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/toc.yml
  mac/TOC.md
  mac/ide-tour.md
  subscriptions/index.md
Labels: do-not-merge

#3292 Fix git push error for protected CLA branch
  docs/code-quality/fxcop-analyzers-faq.md
  docs/code-quality/fxcop-analyzers.yml
  docs/code-quality/fxcop-rule-port-status.md
  docs/code-quality/toc.yml
  docs/debugger/general-debugging-options-dialog-box.md
  docs/extensibility/synchronously-autoloaded-extensions.md
  docs/ide/creating-project-and-item-templates.md
  docs/ide/media/npd-item-with-template-tags.png
  docs/ide/media/npd-search-and-filter.png
  docs/ide/reference/wrap-align-indent-parameters.md
  docs/ide/template-tags.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-controller.md
  docs/install/includes/workloads-components-header-2019_md.md
  docs/install/visual-studio-administrator-guide.md
  docs/install/workload-and-component-ids.md
  docs/install/workload-component-id-vs-build-tools.md
  docs/install/workload-component-id-vs-community.md
  docs/install/workload-component-id-vs-enterprise.md
  docs/install/workload-component-id-vs-professional.md
  docs/install/workload-component-id-vs-team-explorer.md
  docs/install/workload-component-id-vs-test-agent.md
  docs/install/workload-component-id-vs-test-controller.md
  docs/install/workload-component-id-vs-test-professional.md
  docs/toc.yml
  mac/TOC.md
  mac/installation.md
  mac/net-core-support.md
Labels: do-not-merge

#3296 Add F10 launch shortcut
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod, vs-ide-general/tech

#3297 Update creating-a-software-development-kit.md
  docs/extensibility/creating-a-software-development-kit.md
Labels: change sent to author, do-not-merge

#3298 Update creating-a-software-development-kit.md
  docs/extensibility/creating-a-software-development-kit.md
Labels: change sent to author, do-not-merge

#3300 Fix git push error for protected CLA branch
  docs/azure/vs-azure-tools-diagnostics-for-cloud-services-and-virtual-machines.md
  docs/azure/vs-azure-tools-publishing-using-powershell-scripts.md
  docs/code-quality/ca2235-mark-all-non-serializable-fields.md
  docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md
  docs/debugger/how-can-i-debug-access-violations-when-running-my-program-outside-the-debugger-q.md
  docs/extensibility/numberofparentcategoriestorollup-visual-studio-templates.md
  docs/install/build-tools-container.md
  docs/install/workload-and-component-ids.md
  docs/sharepoint/creating-item-templates-and-project-templates-for-sharepoint-project-items.md
  docs/sharepoint/providing-packaging-and-deployment-information-in-project-items.md
  docs/sharepoint/walkthrough-creating-a-site-column-project-item-with-a-project-template-part-1.md
  docs/test/assign-roles-to-a-test-controller-and-test-agent.md
  docs/vsto/changes-to-the-design-of-office-projects-that-target-the-dotnet-framework-4-or-the-dotnet-framework-4-5.md
  docs/vsto/enable-access-to-vba-to-create-or-open-a-visual-studio-tools-for-office-system-project.md
  docs/vsto/how-to-add-an-actions-pane-to-word-documents-or-excel-workbooks.md
  docs/vsto/how-to-programmatically-add-pictures-and-word-art-to-documents.md
  docs/vsto/how-to-programmatically-automatically-fill-ranges-with-incrementally-changing-data.md
  docs/vsto/how-to-programmatically-populate-word-tables-with-document-properties.md
  docs/vsto/information-rights-management-and-managed-code-extensions-overview.md
  docs/workflow-designer/add-parameters-and-add-arguments-dialog-boxes.md
  subscriptions/vs-azure-devops.md
  subscriptions/vs-office365.md
  subscriptions/vscloud-overview.md
Labels: do-not-merge

#3306 Added Extentions Menu to guids-and-ids-of-visual-studio-menus
  docs/extensibility/internals/guids-and-ids-of-visual-studio-menus.md
Labels: change sent to author, ready-to-merge

#3331 fix typo
  docs/debugger/write-better-code-with-visual-studio.md
Labels: change sent to author, ready-to-merge

#3326 Missing bar character causing formatting issue
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3322 Edit.OpenFile vs File.OpenFile
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3332 Updating the sample for PexAssemblySettings
  docs/test/intellitest-manual/attribute-glossary.md
Labels: change sent to author, do-not-merge

#3327 Updated notes
  docs/ide/class-designer/how-to-add-class-diagrams-to-projects.md
Labels: change sent to author, do-not-merge

#3341 PopBrowseContext is misspelled and also C++-only
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3342 Minor language changes
  docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md
Labels: change sent to author, do-not-merge

#3323 Tools.GoToCommandLine doesn't do anything
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3325 Edit.CharTranspose is no longer bound to Ctrl+T
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3320 Edit.GoToNextLocation note
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3321 Edit.NavigateTo is gone
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3324 View.Backward vs View.NavigateBackward
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3350 Add ARM64 to CV_CPU_TYPE_e
  docs/debugger/debug-interface-access/cv-cpu-type-e.md
Labels: change sent to author, ready-to-merge

#3349 Make code format more simpler.
  docs/test/isolating-code-under-test-with-microsoft-fakes.md
Labels: change sent to author, do-not-merge

#3345 Add Edit.GoToMember default hotkeys
  docs/ide/default-keyboard-shortcuts-in-visual-studio.md
Labels: change sent to author, do-not-merge

#3353 Fix git push error for protected CLA branch
  docs/debugger/debug-live-azure-apps-faq.md
  docs/debugger/debug-live-azure-virtual-machines-time-travel-debugging.md
  docs/ide/file-nesting-solution-explorer.md
  docs/ide/reference/edit-devenv-exe.md
  docs/ide/solutions-and-projects-in-visual-studio.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/workload-component-id-vs-enterprise.md
  docs/test/analyze-load-test-results-in-the-graphs-view.md
  docs/test/analyzing-coded-ui-tests-using-coded-ui-test-logs.md
  docs/test/code-generation-compilation-and-naming-conventions-in-microsoft-fakes.md
  docs/test/how-to-create-a-custom-http-body-editor-for-the-web-performance-test-editor.md
  docs/test/how-to-specify-the-number-of-test-iterations-in-a-load-test.md
  docs/test/how-to-specify-the-percentage-of-virtual-users-that-use-web-cache-data.md
  docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
  docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md
  docs/toc.yml
  docs/workflow-designer/how-to-add-a-new-item-to-a-workflow-project.md
  docs/workflow-designer/how-to-debug-xaml-with-the-workflow-designer.md
  docs/workflow-designer/how-to-define-and-consume-activity-delegates-in-the-workflow-designer.md
  docs/workflow-designer/keyboard-shortcuts-in-the-workflow-designer.md
  docs/workflow-designer/system-activities-tab-choose-toolbox-items-dialog-box.md
  docs/xml-tools/how-to-add-nodes-to-the-workspace-from-the-start-view.md
  docs/xml-tools/how-to-add-nodes-to-the-workspace-from-the-xml-schema-explorer.md
  docs/xml-tools/how-to-get-an-overview-of-a-schema-set-using-the-graph-view.md
  subscriptions/_img/vs-modernreq/vs-modernreq-download-page-new.PNG
  subscriptions/_img/vs-modernreq/vs-modernreq-download-page.PNG
  subscriptions/_img/vs-modernreq/vs-modernreq-downloaded-cropped.png
  subscriptions/_img/vs-modernreq/vs-modernreq-downloaded.png
  subscriptions/_img/vs-modernreq/vs-modernreq-extracted-cropped.png
  subscriptions/_img/vs-modernreq/vs-modernreq-extracted.png
  subscriptions/_img/vs-modernreq/vs-modernreq-landing-780.png
  subscriptions/_img/vs-modernreq/vs-modernreq-landing.PNG
  subscriptions/_img/vs-modernreq/vs-modernreq-license-new-resized.png
  subscriptions/_img/vs-modernreq/vs-modernreq-license-new.PNG
  subscriptions/_img/vs-modernreq/vs-modernreq-license.PNG
  subscriptions/_img/vs-modernreq/vs-modernreq-smartword.png
  subscriptions/_img/vs-modernreq/vs-modernreq-tile.PNG
  subscriptions/vs-modernreq.md
Labels: do-not-merge

#3355 Fix Visual Studio version reference
  docs/debugger/xaml-hot-reload.md
Labels: change sent to author, ready-to-merge
