Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-04, with the labels that each got.

#2957 Update how-to-view-save-and-configure-build-log-files.md
  docs/ide/how-to-view-save-and-configure-build-log-files.md
Labels: change sent to author, do-not-merge, vs-ide-compile/tech

#2964 Update Dotfuscator Community Documentation for VS 2019
  docs/deployment/securing-clickonce-applications.md
  docs/ide/dotfuscator/capabilities.md
  docs/ide/dotfuscator/index.md
  docs/ide/dotfuscator/install.md
  docs/ide/dotfuscator/media/install_in_vs19_12.png
  docs/ide/dotfuscator/media/install_in_vs19_34.png
  docs/ide/dotfuscator/media/install_ui.png
  docs/ide/dotfuscator/media/install_ui_17.png
  docs/ide/dotfuscator/upgrades.md
  docs/ide/managing-assembly-and-manifest-signing.md
  docs/toc.yml
  docs/vs-2015/extensibility/visual-studio-shell-integrated.md
  docs/vs-2015/ide/managing-external-tools.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-general/tech

#2978 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/using-visual-studio-vm.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#2979 Update documentation to match implementation
  docs/msbuild/common-msbuild-project-items.md
Labels: change sent to author, ready-to-merge

#2890 Maj ClickOnce packages path location for VS 2017
  docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md
Labels: change sent to author, do-not-merge, ready-to-merge

#2995 Use uniform syntax for bl command line switch
  docs/msbuild/obtaining-build-logs-with-msbuild.md
Labels: change sent to author, ready-to-merge

#3001 typo: Double word "the"
  docs/install/update-visual-studio.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech

#2999 fix: MD037/no-space-in-emphasis
  .markdownlint.json
  docs/extensibility/ux-guidelines/shared-colors-for-visual-studio.md
  docs/ide/how-to-report-a-problem-with-visual-studio.md
  docs/python/python-environments-window-tab-reference.md
Labels: change sent to author, ready-to-merge

#3000 typo: Double word "as"
  docs/javascript/javascript-in-vs-2019.md
Labels: change sent to author, do-not-merge, vs-javascript/tech

#3002 typo: Double word "and"
  docs/code-quality/fxcop-analyzers.yml
Labels: change sent to author, do-not-merge

#3003 fix: subscriptions/vs-ems.md
  subscriptions/vs-ems.md
Labels: change sent to author, do-not-merge

#3011 Fix semantic's confusion and add missing pseudovariable
  docs/debugger/pseudovariables.md
Labels: change sent to author, ready-to-merge

#3016 remove redundant string conversions
  docs/msbuild/msbuild-conditions.md
Labels: change sent to author, do-not-merge

#3025 Fix link to multicontainer tutorial
  docs/containers/index.yml
Labels: change sent to author, do-not-merge

#3032 Fix git push error for protected CLA branch
  docs/code-quality/ca1501-avoid-excessive-inheritance.md
  docs/code-quality/ca1502-avoid-excessive-complexity.md
  docs/code-quality/ca1505-avoid-unmaintainable-code.md
  docs/code-quality/ca1506-avoid-excessive-class-coupling.md
  docs/code-quality/codesnippet/CSharp/ca1502-avoid-excessive-complexity_2.cs
  docs/code-quality/codesnippet/CSharp/ca1502-avoid-excessive-complexity_4.cs
  docs/code-quality/codesnippet/VisualBasic/ca1502-avoid-excessive-complexity_3.vb
  docs/code-quality/codesnippet/VisualBasic/ca1502-avoid-excessive-complexity_4.vb
  docs/code-quality/fxcop-analyzers-faq.md
  docs/code-quality/how-to-generate-code-metrics-data.md
  docs/code-quality/roslyn-analyzers-overview.md
  docs/cross-platform/change-log-visual-studio-tools-for-unity-mac.md
  docs/cross-platform/change-log-visual-studio-tools-for-unity.md
  docs/debugger/includes/remote-debugger-download.md
  docs/debugger/intellitrace.md
  docs/debugger/using-the-microsoft-monitoring-agent.md
  docs/extensibility/roslyn-version-support.md
  docs/ide/adding-visual-studio-editor-support-for-other-languages.md
  docs/ide/editorconfig-code-style-settings-reference.md
  docs/ide/editorconfig-naming-conventions.md
  docs/ide/find-code-changes-and-other-history-with-codelens.md
  docs/ide/how-to-create-multi-project-templates.md
  docs/profiling/beginners-guide-to-performance-profiling.md
  docs/profiling/media/DiagToolsCPUUsageFunctionList.png
  docs/profiling/media/DiagToolsCPUUsageTab.png
  docs/profiling/media/DiagToolsCallTree.png
  docs/profiling/media/DiagToolsEnableCPUProfiling.png
  docs/profiling/media/DiagToolsPreparingThreads.png
  docs/profiling/media/DiagToolsSelectTimeSegment.png
  docs/profiling/media/DiagToolsShowExternalCode.png
  docs/profiling/media/DiagToolsSummaryTab.png
  docs/profiling/media/diag-tools-call-tree.png
  docs/profiling/media/diag-tools-caller-callee-2.png
  docs/profiling/media/diag-tools-caller-callee.png
  docs/profiling/media/diag-tools-cpu-usage-function-list.png
  docs/profiling/media/diag-tools-cpu-usage-tab.png
  docs/profiling/media/diag-tools-enable-cpu-profiling.png
  docs/profiling/media/diag-tools-preparing-data.png
  docs/profiling/media/diag-tools-select-time-segment.png
  docs/profiling/media/diag-tools-select-tool-2.png
  docs/profiling/media/diag-tools-select-tool.png
  docs/profiling/media/diag-tools-show-external-code.png
  docs/profiling/media/diag-tools-summary-tab-2.png
  docs/profiling/media/diag-tools-summary-tab.png
  docs/profiling/media/vs-2019/diag-tools-call-tree.png
  docs/profiling/media/vs-2019/diag-tools-hot-path.png
  docs/profiling/memory-usage.md
  docs/profiling/what-s-new-in-profiling-tools.md
  docs/toc.yml
  mac/docfx.json
Labels: do-not-merge

#3045 Fixing typo from "tpics" to "topics"
  docs/deployment/publishing-clickonce-applications.md
Labels: change sent to author, ready-to-merge

#3046 Fix git push error for protected CLA branch
  docs/cross-platform/change-log-visual-studio-tools-for-unity.md
  docs/extensibility/toc.yml
  docs/extensibility/ux-guidelines/media/PMA-parenting-behavior.PNG
  docs/extensibility/ux-guidelines/per-monitor-awareness-extenders.md
  docs/ide/reference/convert-foreach-linq.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md
  docs/install/repair-visual-studio.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/porting/port-migrate-and-upgrade-visual-studio-projects.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3052 fix: MD023/heading-start-left/header-start-left
  docs/ide/reference/convert-foreach-linq.md
Labels: change sent to author, do-not-merge

#3055 Fix git push error for protected CLA branch
  docs/debugger/debug-installed-app-package.md
  docs/debugger/debugging-managed-code.md
  docs/debugger/general-debugging-options-dialog-box.md
  docs/debugger/media/managed-data-breakpoint.png
  docs/debugger/media/vs-2019/cpu-use-wt-getmaxnumbercalltree-annotated.png
  docs/debugger/media/vs-2019/cpu-use-wt-showexternalcodetoowide-found.png
  docs/debugger/quickstart-debug-aspnet.md
  docs/debugger/quickstart-debug-with-cplusplus.md
  docs/debugger/quickstart-debug-with-managed.md
  docs/debugger/using-breakpoints.md
  docs/debugger/view-historical-application-state.md
  docs/extensibility/ux-guidelines/per-monitor-awareness-extenders.md
  docs/ide/advanced-feature-overview.md
  docs/ide/find-and-fix-code-errors.md
  docs/ide/reference/debug-page-project-designer.md
  docs/porting/port-migrate-and-upgrade-visual-studio-projects.md
  docs/sharepoint/getting-started-sharepoint-development-in-visual-studio.md
  docs/sharepoint/includes/vsprvs-current-md.md
  docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md
  docs/vsto/deploying-an-office-solution-by-using-clickonce.md
Labels: do-not-merge

#3061 Guidance applies to F# as well
  docs/msbuild/customize-your-build.md
Labels: change sent to author, ready-to-merge

#2974 Including CodeCracker
  docs/ide/csharp-developer-productivity.md
Labels: change sent to author, do-not-merge

#3082 MSBuild: Property function returns are escaped
  docs/msbuild/property-functions.md
Labels: change sent to author, ready-to-merge

#3081 Updated info for downloading older versions.
  mac/2017/installation.md
Labels: change sent to author, ready-to-merge, vs-ide-install/tech

#3070 Fix missing quotation mark in example
  docs/msbuild/how-to-exclude-files-from-the-build.md
Labels: change sent to author, ready-to-merge

#3089 Fix git push error for protected CLA branch
  docs/cross-platform/using-visual-studio-tools-for-unity.md
  docs/data-tools/accessing-data-in-visual-studio.md
  docs/debugger/debug-live-azure-applications.md
  docs/debugger/debug-live-azure-kubernetes.md
  docs/debugger/debug-live-azure-virtual-machines-time-travel-debugging.md
  docs/debugger/debug-live-azure-virtual-machines.md
  docs/debugger/getting-started-with-the-debugger-cpp.md
  docs/debugger/includes/remote-debugger-download.md
  docs/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio.md
  docs/debugger/media/time-travel-debugging-select-azure-resource-vm.png
  docs/debugger/media/time-travel-debugging-set-snappoint-action.png
  docs/debugger/media/time-travel-debugging-set-snappoint-settings.png
  docs/debugger/media/time-travel-debugging-start-debugging.png
  docs/debugger/media/time-travel-debugging-step-commands.png
  docs/debugger/toc.yml
  docs/deployment/includes/quickstart-prereqs-azure-linux.md
  docs/deployment/includes/quickstart-prereqs-azure.md
  docs/deployment/includes/quickstart-prereqs.md
  docs/get-started/includes/ide-overview.md
  docs/ide/advanced-feature-overview.md
  docs/ide/create-a-visual-basic-winform-in-visual-studio.md
  docs/ide/optimize-visual-studio-performance.md
  docs/ide/quickstart-aspnet-core.md
  docs/ide/quickstart-ide-orientation.md
  docs/ide/quickstart-nodejs.md
  docs/ide/quickstart-personalize-the-ide.md
  docs/ide/quickstart-python.md
  docs/ide/reference/xaml-designer.md
  docs/ide/whats-new-visual-studio-2017.md
  docs/install/create-an-offline-installation-of-visual-studio.md
  docs/install/install-visual-studio.md
  docs/test/includes/web-load-test-deprecated.md
  subscriptions/vs-linkedin-learning.md
Labels: do-not-merge

#3069 Update per-monitor-awareness-extenders.md
  docs/extensibility/ux-guidelines/per-monitor-awareness-extenders.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3097 Fix git push error for protected CLA branch
  docs/containers/deploy-app-service.md
  docs/containers/edit-and-refresh.md
  docs/containers/hosting-web-apps-in-docker.md
  docs/containers/includes/vs-2017/container-tools.md
  docs/containers/tutorial-kubernetes-tools.md
  docs/containers/tutorial-multicontainer.md
  docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md
  docs/cross-platform/unity-scripting-upgrade.md
  docs/debugger/debug-live-azure-applications.md
  docs/get-started/csharp/tutorial-aspnet-core.md
  docs/get-started/csharp/tutorial-console.md
  docs/get-started/csharp/tutorial-debugger.md
  docs/get-started/csharp/tutorial-editor.md
  docs/get-started/csharp/tutorial-projects-solutions.md
  docs/get-started/csharp/tutorial-uwp.md
  docs/get-started/csharp/tutorial-wpf.md
  docs/get-started/tutorial-editor.md
  docs/get-started/tutorial-open-project-from-repo.md
  docs/get-started/tutorial-projects-solutions.md
  docs/get-started/visual-basic/tutorial-console.md
  docs/get-started/visual-basic/tutorial-debugger.md
  docs/get-started/visual-basic/tutorial-editor.md
  docs/get-started/visual-basic/tutorial-projects-solutions.md
  docs/get-started/visual-basic/tutorial-wpf.md
  docs/get-started/visual-basic/visual-studio-ide.md
  docs/ide/quickstart-csharp-console.md
  docs/ide/quickstart-fsharp.md
  docs/ide/quickstart-visual-basic-console.md
  docs/install/troubleshooting-installation-issues.md
  docs/javascript/tutorial-nodejs.md
  docs/vs-2015/code-quality/ca1500-variable-names-should-not-match-field-names.md
  docs/vs-2015/code-quality/ca1702-compound-words-should-be-cased-correctly.md
  docs/vs-2015/code-quality/ca1707-identifiers-should-not-contain-underscores.md
  docs/vs-2015/code-quality/ca1709-identifiers-should-be-cased-correctly.md
  docs/vs-2015/code-quality/ca1715-identifiers-should-have-correct-prefix.md
  docs/vs-2015/code-quality/ca1726-use-preferred-terms.md
  docs/vs-2015/code-quality/ca1801-review-unused-parameters.md
  docs/vs-2015/code-quality/ca1822-mark-members-as-static.md
  docs/vs-2015/code-quality/ca1900-value-type-fields-should-be-portable.md
  docs/vs-2015/code-quality/ca1903-use-only-api-from-targeted-framework.md
  docs/vs-2015/code-quality/ca2238-implement-serialization-methods-correctly.md
  docs/vs-2015/debugger/using-the-microsoft-monitoring-agent.md
  docs/vs-2015/ide/how-to-report-a-problem-with-visual-studio-2015.md
  docs/vs-2015/ide/talk-to-us.md
  docs/vs-2015/install/create-an-offline-installation-of-visual-studio.md
  docs/vs-2015/install/how-to-automatically-apply-product-keys-when-deploying-visual-studio.md
  docs/vs-2015/install/install-multiple-language-versions-of-visual-studio.md
  docs/vs-2015/install/uninstall-visual-studio.md
  docs/vs-2015/install/use-command-line-parameters-to-install-visual-studio.md
  docs/vs-2015/install/visual-studio-administrator-guide.md
  docs/vs-2015/porting/porting-migrating-and-upgrading-visual-studio-projects.md
  docs/vs-2015/profiling/da0001-use-stringbuilder-for-concatenations.md
  docs/vs-2015/profiling/da0010-expensive-gethashcode.md
  docs/vs-2015/profiling/da0011-expensive-compareto.md
  docs/vs-2015/profiling/da0038-high-rate-of-lock-contentions.md
  docs/vs-2015/profiling/da0039-very-high-rate-of-lock-contentions.md
Labels: do-not-merge

#3100 typo: Double word "the"
  docs/cross-platform/using-visual-studio-tools-for-unity.md
  docs/debugger/debug-live-azure-virtual-machines-time-travel-debugging.md
  docs/debugger/using-breakpoints.md
Labels: change sent to author, do-not-merge, vs-unity-tools/tech

#3101 fix: docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md
  docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md
Labels: change sent to author, do-not-merge, vs-ide-general/tech

#3092 fix: subscriptions\vs-rstudio.md
  subscriptions/vs-rstudio.md
Labels: change sent to author, do-not-merge

#3105 fix: MD030/list-marker-space
  subscriptions/vs-rstudio.md
Labels: change sent to author, do-not-merge

#3111 Wrong bracket in the Example
  docs/debugger/using-the-debuggerdisplay-attribute.md
Labels: change sent to author, ready-to-merge

#3106 fix: MD003/heading-style/header-style
  .markdownlint.json
  docs/ide/managing-application-settings-dotnet.md
  docs/test/how-to-create-a-load-test-plug-in.md
  docs/vs-2015/csharp-ide/using-the-visual-studio-development-environment-for-csharp.md
  docs/vs-2015/debugger/debugging-f-hash.md
  docs/vs-2015/debugger/format-specifiers-in-csharp.md
  docs/vs-2015/debugger/walkthrough-writing-a-visualizer-in-csharp.md
  docs/vs-2015/deployment/walkthrough-downloading-satellite-assemblies-on-demand-with-the-clickonce-deployment-api-using-the-designer.md
  docs/vs-2015/ide/how-to-suppress-compiler-warnings.md
  docs/vs-2015/ide/managing-application-settings-dotnet.md
  docs/vs-2015/ide/refactoring-in-visual-studio.md
  docs/vs-2015/ide/walkthrough-building-an-application.md
  docs/vs-2015/misc/completion-lists-in-csharp.md
  docs/vs-2015/profiling/how-to-use-the-concurrency-visualizer-markers-sdk.md
  docs/vsto/deploying-an-office-solution-by-using-windows-installer.md
  docs/vsto/how-to-create-event-handlers-in-office-projects.md
  docs/vsto/troubleshooting-errors-in-office-solutions.md
  docs/vsto/writing-code-in-office-solutions.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, vs-ide-debug/tech

#3112 Adding a space
  mac/update.md
Labels: change sent to author, ready-to-merge, vs-ide-install/tech

#3113 fix: MD005/list-indent
  .markdownlint.json
  docs/code-quality/ca2300-do-not-use-insecure-deserializer-binaryformatter.md
  docs/code-quality/cpp-core-guidelines-warnings.md
  docs/debugger/autos-and-locals-windows.md
  docs/debugger/debug-using-the-just-in-time-debugger.md
  docs/debugger/historical-debugging.md
  docs/debugger/run-windows-store-apps-in-the-simulator.md
  docs/extensibility/ux-guidelines/ux-essentials-for-visual-studio.md
  docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md
  docs/ide/dotfuscator/install.md
  docs/ide/how-to-view-save-and-configure-build-log-files.md
  docs/ide/reference/generate-constructor.md
  docs/install/using-visual-studio-vm.md
  docs/javascript/javascript-in-vs-2017.md
  docs/profiling/shutdown.md
  docs/vs-2015/debugger/debug-multithreaded-applications-in-visual-studio.md
  docs/vs-2015/debugger/run-windows-store-apps-in-the-simulator.md
  docs/vs-2015/extensibility/ux-guidelines/shared-colors-for-visual-studio.md
  docs/vs-2015/install/how-to-create-and-run-an-unattended-installation-of-visual-studio.md
  docs/vs-2015/misc/shared-colors.md
  docs/vs-2015/modeling/define-a-profile-to-extend-uml.md
  docs/vs-2015/modeling/display-a-uml-model-on-diagrams.md
  docs/vs-2015/profiling/shutdown.md
  docs/vsto/windows-forms-controls-on-office-documents-overview.md
  mac/2017/asp-net-core.md
  mac/2017/publish-app-svc.md
  mac/2017/publish-folder.md
  mac/asp-net-core.md
  mac/publish-app-svc.md
  mac/publish-folder.md
  subscriptions/aliasing.md
  subscriptions/vs-cast.md
  subscriptions/vs-cloudpilot.md
Labels: change sent to author, do-not-merge, visual-studio-dev14/prod, visual-studio-mac/prod, vs-ide-debug/tech, vs-ide-modeling/tech

#3118 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md
  docs/code-quality/install-roslyn-analyzers.md
  docs/code-quality/media/nuget-install-command.png
  docs/code-quality/use-roslyn-analyzers.md
  docs/debugger/debug-live-azure-virtual-machines-time-travel-debugging.md
  docs/debugger/run-windows-store-apps-in-the-simulator.md
  docs/extensibility/creating-custom-editors-and-designers.md
  docs/extensibility/designer-initialization-and-metadata-configuration.md
  docs/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017.md
  docs/extensibility/supplying-undo-support-to-designers.md
  docs/extensibility/ux-guidelines/ux-essentials-for-visual-studio.md
  docs/extensibility/whats-new-visual-studio-2019-sdk.md
  docs/ide/using-regular-expressions-in-visual-studio.md
  docs/install/import-export-installation-configurations.md
  docs/install/media/vs-2019/config-file-recommend-install.png
  docs/install/media/vs-2019/export-configuration-confirmation.png
  docs/install/media/vs-2019/export-configuration-vs-installer.png
  docs/install/media/vs-2019/solution-explorer-config-file.png
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/modeling/customizing-presentation-on-the-diagram.md
  docs/modeling/defining-shapes-and-connectors.md
  docs/modeling/nesting-shapes.md
  docs/modeling/toc.yml
  docs/toc.yml
Labels: do-not-merge

#3125 Improve analyzer predefined ruleset example
  docs/code-quality/analyzer-rule-sets.md
Labels: change sent to author, do-not-merge

#3128 Fix git push error for protected CLA branch
  docs/code-quality/C26453.md
  docs/ide/code-snippets-schema-reference.md
  docs/ide/create-portable-custom-editor-options.md
  docs/ide/csharp-developer-productivity.md
  docs/ide/editorconfig-code-style-settings-reference.md
  docs/ide/editorconfig-naming-conventions.md
  docs/ide/media/vxoperator_icon.gif
  docs/ide/media/vxstruct_icon.gif
  docs/ide/reference/convert-foreach-linq.md
  docs/ide/reference/convert-local-function-method.md
  docs/ide/template-parameters.md
  docs/ide/using-the-task-list.md
  docs/install/import-export-installation-configurations.md
  docs/install/media/vs-2019/vs-installer-export-config.png
  docs/test/live-unit-testing-intro.md
  docs/test/live-unit-testing-start.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#3130 Add HTTP Status Code errors
  docs/debugger/debug-live-azure-apps-troubleshooting.md
Labels: change sent to author, ready-to-merge

#3135 Correct sample item template xml
  docs/extensibility/visual-studio-template-manifest-schema-reference.md
Labels: change sent to author, do-not-merge

#3136 Fix git push error for protected CLA branch
  docs/code-quality/analyzer-rule-sets.md
  docs/debugger/media/get-started-set-breakpoint-cpp.gif
  docs/debugger/media/get-started-set-breakpoint.gif
  docs/extensibility/media/xaml-designer-extensibility-migration-architecture.png
  docs/extensibility/toc.yml
  docs/extensibility/whats-new-visual-studio-2019-sdk.md
  docs/extensibility/xaml-designer-extensibility-migration.md
  docs/ide/filtered-solutions.md
  docs/ide/media/filtered-solutions/load-project-dependencies.png
  docs/ide/media/filtered-solutions/reload-project.png
  docs/ide/media/filtered-solutions/save-as-solution-filter.png
  docs/ide/media/filtered-solutions/show-all-files.PNG
  docs/ide/media/filtered-solutions/solution-filter.PNG
  docs/ide/reference/donotloadprojects-devenv-exe.md
  docs/ide/whats-new-visual-studio-2019.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3142 Fix git push error for protected CLA branch
  docs/debugger/debug-live-azure-apps-troubleshooting.md
  docs/extensibility/visual-cpp-project-extensibility.md
  docs/ide/not-in-toc/default.md
  docs/ide/talk-to-us.md
  docs/install/import-export-installation-configurations.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/porting/port-migrate-and-upgrade-visual-studio-projects.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-general/tech

#3145 Missing square bracket in span notation
  docs/extensibility/inside-the-editor.md
Labels: change sent to author, ready-to-merge

#3153 Update customizing-code-coverage-analysis.md
  docs/test/customizing-code-coverage-analysis.md
Labels: change sent to author, do-not-merge

#3150 Update how-to-use-rule-based-ui-context-for-visual-studio-extensions.md
  docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md
Labels: change sent to author, ready-to-merge

#3156 Remove extra parenthesis
  docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md
Labels: do-not-merge

#3163 chore: Cleanup redirect files
  .openpublishing.redirection.json
  docs/vs-2015/ide/index.md
  docs/vs-2015/ide/whats-new-in-visual-studio.md
  docs/vs-2015/index.md
  docs/vs-2015/install/install-visual-studio.md
Labels: change sent to author, do-not-merge

#3161 chore: Renormalize line endings
  .openpublishing.publish.config.json
Labels: change sent to author, do-not-merge

#3166 Fix git push error for protected CLA branch
  docs/extensibility/launch-visual-studio-dte.md
  docs/extensibility/locating-visual-studio.md
  docs/extensibility/roslyn-version-support.md
  docs/extensibility/toc.yml
  docs/extensibility/walkthrough-accessing-the-dte-object-from-an-editor-extension.md
Labels: change sent to author, do-not-merge

#3172 Fix git push error for protected CLA branch
  subscriptions/TOC.md
  subscriptions/access-github.md
  subscriptions/assign-github.md
  subscriptions/handle-overclaimed-license.md
  subscriptions/vs-azure-devops.md
Labels: do-not-merge
