Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2019-02, with the labels that each got.

#2302 Update README.md - remove 2017
  README.md
Labels: change sent to author, do-not-merge

#2303 Add periods to keep consistency.
  docs/modeling/guidelines-for-writing-t4-text-templates.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#2309 Fix code
  docs/extensibility/extending-the-output-window.md
Labels: change sent to author, do-not-merge

#2314 Remove 'stopping event' from Load Complete Event
  docs/extensibility/debugger/reference/idebugloadcompleteevent2.md
Labels: change sent to author, do-not-merge

#2318 Delete unnecessary spaces
  docs/debugger/allocation-hooks-and-c-run-time-memory-allocations.md
Labels: change sent to author, do-not-merge

#2310 Add missing "Organize usings" .editorconfig setting for separating using groups
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#2355 Fix incorrect default value added in #2310
  docs/ide/editorconfig-code-style-settings-reference.md
Labels: change sent to author, do-not-merge, visual-studio-dev15/prod

#2397 OBAs is proper noun
  docs/vsto/create-vsto-add-ins-for-office-by-using-visual-studio.md
Labels: change sent to author, do-not-merge

#2401 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenuminjectedsources.md
Labels: change sent to author, do-not-merge

#2400 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumframedata.md
Labels: change sent to author, do-not-merge

#2399 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumdebugstreams.md
Labels: change sent to author, do-not-merge

#2385 Delete unnecessary spaces
  docs/debugger/debug-html-css-and-javascript-sample-code.md
Labels: change sent to author, do-not-merge

#2430 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasymbol-get-value.md
Labels: change sent to author, do-not-merge

#2429 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasymbol-get-type.md
Labels: change sent to author, do-not-merge

#2444 Delete unnecessary spaces
  docs/debugger/graphics/mip-map-generation-variant.md
Labels: change sent to author, do-not-merge

#2419 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-findlinesbyrva.md
Labels: change sent to author, do-not-merge

#2418 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-findlinesbylinenum.md
Labels: change sent to author, do-not-merge

#2420 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-findlinesbyva.md
Labels: change sent to author, do-not-merge

#2421 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-getenumtables.md
Labels: change sent to author, do-not-merge

#2422 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-symbolbyid.md
Labels: change sent to author, do-not-merge

#2423 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession.md
Labels: change sent to author, do-not-merge

#2424 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasourcefile.md
Labels: change sent to author, do-not-merge

#2425 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiastackframe.md
Labels: change sent to author, do-not-merge

#2426 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiastackwalker.md
Labels: change sent to author, do-not-merge

#2427 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasymbol-get-basetype.md
Labels: change sent to author, do-not-merge

#2417 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasession-findlinesbyaddr.md
Labels: change sent to author, do-not-merge

#2449 Delete unnecessary spaces
  docs/debugger/how-to-set-a-thread-name-in-native-code.md
Labels: change sent to author, do-not-merge

#2461 Update how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md
  docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md
Labels: change sent to author, do-not-merge

#2451 Delete unnecessary spaces
  docs/debugger/how-to-write-a-run-time-error-reporting-function.md
Labels: change sent to author, do-not-merge

#2452 Delete unnecessary spaces
  docs/debugger/inspect-xaml-properties-while-debugging.md
Labels: change sent to author, do-not-merge

#2447 Delete unnecessary spaces
  docs/debugger/graphics/walkthrough-capturing-graphics-information-programmatically.md
Labels: change sent to author, do-not-merge

#2450 Delete unnecessary spaces
  docs/debugger/how-to-test-and-debug-a-visualizer.md
Labels: change sent to author, do-not-merge

#2448 Delete unnecessary spaces
  docs/debugger/how-to-debug-the-onstart-method.md
Labels: change sent to author, do-not-merge

#2460 Delete unnecessary spaces
  docs/extensibility/adapting-legacy-code-to-the-editor.md
Labels: change sent to author, do-not-merge

#2402 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumlinenumbers.md
Labels: change sent to author, do-not-merge

#2403 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumsectioncontribs.md
Labels: change sent to author, do-not-merge

#2404 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumsegments.md
Labels: change sent to author, do-not-merge

#2412 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiainjectedsource.md
Labels: change sent to author, do-not-merge

#2411 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaimagedata.md
Labels: change sent to author, do-not-merge

#2415 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasectioncontrib.md
Labels: change sent to author, do-not-merge

#2414 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiapropertystorage.md
Labels: change sent to author, do-not-merge

#2458 Delete unnecessary spaces
  docs/debugger/walkthrough-using-intellitrace.md
Labels: change sent to author, do-not-merge

#2435 Delete unnecessary spaces
  docs/debugger/crt-debug-heap-details.md
Labels: change sent to author, do-not-merge

#2456 Delete unnecessary spaces
  docs/debugger/using-the-debuggerdisplay-attribute.md
Labels: change sent to author, do-not-merge

#2436 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasymbol.md
Labels: change sent to author, do-not-merge

#2455 Delete unnecessary spaces
  docs/debugger/using-run-time-checks-without-the-c-run-time-library.md
Labels: change sent to author, do-not-merge

#2437 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiatable.md
Labels: change sent to author, do-not-merge

#2413 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idialinenumber.md
Labels: change sent to author, do-not-merge

#2438 Delete unnecessary spaces
  docs/debugger/debug-interface-access/memorytypeenum.md
Labels: change sent to author, do-not-merge

#2439 Delete unnecessary spaces
  docs/debugger/debug-interface-access/querying-the-dot-pdb-file.md
Labels: change sent to author, do-not-merge

#2440 Delete unnecessary spaces
  docs/debugger/debug-interface-access/stackframetypeenum.md
Labels: change sent to author, do-not-merge

#2453 Delete unnecessary spaces
  docs/debugger/javascript-console-commands.md
Labels: change sent to author, do-not-merge

#2441 Delete unnecessary spaces
  docs/debugger/expressions-in-the-debugger.md
Labels: change sent to author, do-not-merge

#2446 Delete unnecessary spaces
  docs/debugger/historical-debugging-inspect-app.md
Labels: change sent to author, do-not-merge

#2442 Delete unnecessary spaces
  docs/debugger/format-specifiers-in-cpp.md
Labels: change sent to author, do-not-merge

#2459 Delete unnecessary spaces
  docs/debugger/quickstart-debug-javascript-using-the-console.md
Labels: change sent to author, do-not-merge

#2428 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasymbol-get-intro.md
Labels: change sent to author, do-not-merge

#2443 Delete unnecessary spaces
  docs/debugger/format-specifiers-in-csharp.md
Labels: change sent to author, do-not-merge

#2416 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiasegment.md
Labels: change sent to author, do-not-merge

#2405 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumsourcefiles.md
Labels: change sent to author, do-not-merge

#2457 Delete unnecessary spaces
  docs/debugger/quickstart-debug-html-and-css.md
Labels: change sent to author, do-not-merge

#2454 Delete unnecessary spaces
  docs/debugger/just-my-code.md
Labels: change sent to author, do-not-merge

#2445 Fix broken link re. test adapter extension deprecation
  docs/test/test-explorer-faq.md
Labels: area - test, change sent to author, do-not-merge

#2503 Fix code
  docs/extensibility/extending-the-output-window.md
Labels: change sent to author, do-not-merge

#2467 Delete unnecessary spaces
  docs/extensibility/adding-a-menu-controller-to-a-toolbar.md
Labels: change sent to author, do-not-merge

#2468 Delete unnecessary spaces
  docs/extensibility/adding-a-most-recently-used-list-to-a-submenu.md
Labels: change sent to author, do-not-merge

#2469 Delete unnecessary spaces
  docs/extensibility/adding-an-attribute-to-a-project-item.md
Labels: change sent to author, do-not-merge

#2470 Delete unnecessary spaces
  docs/extensibility/changing-the-appearance-of-a-command.md
Labels: change sent to author, do-not-merge

#2472 Delete unnecessary spaces
  docs/extensibility/adding-user-control-to-the-start-page.md
Labels: change sent to author, do-not-merge

#2473 Delete unnecessary spaces
  docs/extensibility/changing-the-text-of-a-menu-command.md
Labels: change sent to author, do-not-merge

#2474 Delete unnecessary spaces
  docs/extensibility/command-code-enumerator.md
Labels: change sent to author, do-not-merge

#2475 Delete unnecessary spaces
  docs/extensibility/creating-a-multi-instance-tool-window.md
Labels: change sent to author, do-not-merge

#2476 Delete unnecessary spaces
  docs/extensibility/creating-a-windows-forms-toolbox-control.md
Labels: change sent to author, do-not-merge

#2477 Delete unnecessary spaces
  docs/extensibility/creating-a-wpf-toolbox-control.md
Labels: change sent to author, do-not-merge

#2478 Delete unnecessary spaces
  docs/extensibility/creating-an-extension-with-a-vspackage.md
Labels: change sent to author, do-not-merge

#2480 Delete unnecessary spaces
  docs/extensibility/debugger/event-sources-visual-studio-sdk.md
Labels: change sent to author, do-not-merge

#2481 Delete unnecessary spaces
  docs/extensibility/debugger/getting-a-port.md
Labels: change sent to author, do-not-merge

#2482 Delete unnecessary spaces
  docs/extensibility/creating-an-extension-with-a-menu-command.md
Labels: change sent to author, do-not-merge

#2483 Delete unnecessary spaces
  docs/extensibility/debugger/getting-local-properties.md
Labels: change sent to author, do-not-merge

#2484 Delete unnecessary spaces
  docs/extensibility/debugger/implementing-getmethodproperty.md
Labels: change sent to author, do-not-merge

#2485 Delete unnecessary spaces
  docs/extensibility/debugger/reference/ad-process-id-type.md
Labels: change sent to author, do-not-merge

#2486 Delete unnecessary spaces
  docs/extensibility/debugger/reference/ad-process-id.md
Labels: change sent to author, do-not-merge

#2487 Delete unnecessary spaces
  docs/extensibility/debugger/reference/address-kind.md
Labels: change sent to author, do-not-merge

#2488 Delete unnecessary spaces
  docs/extensibility/debugger/reference/assemblylocresolution.md
Labels: change sent to author, do-not-merge

#2489 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-flags90.md
Labels: change sent to author, do-not-merge

#2490 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-location.md
Labels: change sent to author, do-not-merge

#2491 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-request-info.md
Labels: change sent to author, do-not-merge

#2492 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-request-info2.md
Labels: change sent to author, do-not-merge

#2493 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-resolution-location.md
Labels: change sent to author, do-not-merge

#2494 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bpreqi-fields90.md
Labels: change sent to author, do-not-merge

#2495 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bstr-array.md
Labels: change sent to author, do-not-merge

#2524 Delete unnecessary spaces
  docs/extensibility/debugger/reference/evalflags.md
Labels: change sent to author, do-not-merge

#2496 Delete unnecessary spaces
  docs/debugger/mfc-debugging-techniques.md
Labels: change sent to author, do-not-merge

#2497 Delete unnecessary spaces
  docs/extensibility/adding-a-shortcut-menu-in-a-tool-window.md
Labels: change sent to author, do-not-merge

#2498 Delete unnecessary spaces
  docs/extensibility/adding-a-tool-window.md
Labels: change sent to author, do-not-merge

#2499 Delete unnecessary spaces
  docs/extensibility/adding-an-lsp-extension.md
Labels: change sent to author, do-not-merge

#2522 Delete unnecessary spaces
  docs/extensibility/debugger/reference/dwtype-kind.md
Labels: change sent to author, do-not-merge

#2521 Delete unnecessary spaces
  docs/extensibility/debugger/reference/displaykind.md
Labels: change sent to author, do-not-merge

#2523 Delete unnecessary spaces
  docs/extensibility/debugger/reference/encunavailablereason.md
Labels: change sent to author, do-not-merge

#2520 Delete unnecessary spaces
  docs/extensibility/debugger/reference/disassemblydata.md
Labels: change sent to author, do-not-merge

#2501 Delete unnecessary spaces
  docs/extensibility/debugger/getting-local-values.md
Labels: change sent to author, do-not-merge

#2519 Delete unnecessary spaces
  docs/extensibility/debugger/reference/debug-reason.md
Labels: change sent to author, do-not-merge

#2518 Delete unnecessary spaces
  docs/extensibility/debugger/reference/debug-custom-viewer.md
Labels: change sent to author, do-not-merge

#2500 Delete unnecessary spaces
  docs/extensibility/creating-a-basic-project-system-part-2.md
Labels: change sent to author, do-not-merge

#2517 Delete unnecessary spaces
  docs/extensibility/debugger/reference/debug-address.md
Labels: change sent to author, do-not-merge

#2516 Delete unnecessary spaces
  docs/extensibility/debugger/reference/debug-address-union.md
Labels: change sent to author, do-not-merge

#2515 Delete unnecessary spaces
  docs/extensibility/debugger/reference/context-info.md
Labels: change sent to author, do-not-merge

#2514 Delete unnecessary spaces
  docs/extensibility/debugger/reference/context-info-fields.md
Labels: change sent to author, do-not-merge

#2513 Delete unnecessary spaces
  docs/extensibility/debugger/evaluating-locals.md
Labels: change sent to author, do-not-merge

#2512 Delete unnecessary spaces
  docs/extensibility/debugger/reference/const-guid-array.md
Labels: change sent to author, do-not-merge

#2511 Delete unnecessary spaces
  docs/extensibility/debugger/reference/connection-protocol.md
Labels: change sent to author, do-not-merge

#2510 Delete unnecessary spaces
  docs/extensibility/debugger/reference/computer-info.md
Labels: change sent to author, do-not-merge

#2509 Delete unnecessary spaces
  docs/debugger/debug-interface-access/idiaenumdebugstreams-item.md
Labels: change sent to author, do-not-merge

#2508 Delete unnecessary spaces
  docs/extensibility/debugger/reference/code-path.md
Labels: change sent to author, do-not-merge

#2507 Delete unnecessary spaces
  docs/extensibility/debugger/reference/built-type.md
Labels: change sent to author, do-not-merge

#2541 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbreakpointboundevent2-getpendingbreakpoint.md
Labels: change sent to author, do-not-merge

#2540 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbreakpointboundevent2-enumboundbreakpoints.md
Labels: change sent to author, do-not-merge

#2539 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugboundbreakpoint2-getstate.md
Labels: change sent to author, do-not-merge

#2538 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugboundbreakpoint2-getpendingbreakpoint.md
Labels: change sent to author, do-not-merge

#2537 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugboundbreakpoint2-getbreakpointresolution.md
Labels: change sent to author, do-not-merge

#2536 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugboundbreakpoint2-enable.md
Labels: change sent to author, do-not-merge

#2535 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugboundbreakpoint2-delete.md
Labels: change sent to author, do-not-merge

#2534 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbinder3-getmemorycontext64.md
Labels: change sent to author, do-not-merge

#2533 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbeforesymbolsearchevent2-getmodulename.md
Labels: change sent to author, do-not-merge

#2532 Delete unnecessary spaces
  docs/extensibility/debugger/reference/guid-array.md
Labels: change sent to author, do-not-merge

#2531 Delete unnecessary spaces
  docs/extensibility/debugger/reference/frameinfo-flags.md
Labels: change sent to author, do-not-merge

#2530 Delete unnecessary spaces
  docs/extensibility/debugger/reference/field-modifiers.md
Labels: change sent to author, do-not-merge

#2529 Delete unnecessary spaces
  docs/extensibility/debugger/reference/field-kind.md
Labels: change sent to author, do-not-merge

#2528 Delete unnecessary spaces
  docs/extensibility/debugger/reference/field-kind-ex.md
Labels: change sent to author, do-not-merge

#2527 Delete unnecessary spaces
  docs/extensibility/debugger/reference/field-info.md
Labels: change sent to author, do-not-merge

#2526 Delete unnecessary spaces
  docs/extensibility/debugger/reference/field-info-fields.md
Labels: change sent to author, do-not-merge

#2525 Delete unnecessary spaces
  docs/extensibility/debugger/reference/evalflags90.md
Labels: change sent to author, do-not-merge

#2547 Delete unnecessary spaces
  docs/debugger/debug-interface-access/cv-hreg-e.md
Labels: change sent to author, do-not-merge

#2546 Delete unnecessary spaces
  docs/debugger/debug-interface-access/cv-cpu-type-e.md
Labels: change sent to author, do-not-merge

#2545 Delete unnecessary spaces
  docs/debugger/debug-interface-access/cv-cfl-lang.md
Labels: change sent to author, do-not-merge

#2544 Delete unnecessary spaces
  docs/debugger/debug-interface-access/cv-call-e.md
Labels: change sent to author, do-not-merge

#2543 Delete unnecessary spaces
  docs/debugger/debug-interface-access/cv-access-e.md
Labels: change sent to author, do-not-merge

#2542 Delete unnecessary spaces
  docs/debugger/debug-interface-access/basictype.md
Labels: change sent to author, do-not-merge

#2551 Update using-the-debuggerdisplay-attribute.md
  docs/debugger/using-the-debuggerdisplay-attribute.md
Labels: change sent to author, do-not-merge

#2479 Delete unnecessary spaces
  docs/extensibility/creating-and-managing-modal-dialog-boxes.md
Labels: change sent to author, do-not-merge

#2558 Delete unnecessary spaces
  docs/debugger/debug-interface-access/diaaddressmapentry.md
Labels: change sent to author, do-not-merge

#2557 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbreakpointrequest2-getlocationtype.md
Labels: change sent to author, do-not-merge

#2556 Delete unnecessary spaces
  docs/extensibility/debugger/enumerating-locals.md
Labels: change sent to author, do-not-merge

#2555 Delete unnecessary spaces
  docs/extensibility/debugger/reference/idebugbreakpointchecksumrequest2-getchecksum.md
Labels: change sent to author, do-not-merge

#2554 Delete unnecessary spaces
  docs/extensibility/debugger/evaluating-a-watch-expression.md
Labels: change sent to author, do-not-merge

#2553 Delete unnecessary spaces
  docs/debugger/debug-interface-access/datakind.md
Labels: change sent to author, do-not-merge

#2573 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-location-code-context.md
Labels: change sent to author, do-not-merge

#2572 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-location-code-address.md
Labels: change sent to author, do-not-merge

#2571 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-flags.md
Labels: change sent to author, do-not-merge

#2570 Delete unnecessary spaces
  docs/extensibility/debugger/reference/bp-error-type.md
Labels: change sent to author, do-not-merge
