Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2020-01, with the labels that each got.

#4580 Fix git push error for protected CLA branch
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
Labels: do-not-merge

#4598 Fix git push error for protected CLA branch
  docs/javascript/TOC.yml
  docs/javascript/debug-nodejs.md
  docs/javascript/index.yml
  docs/javascript/media/aspnet-core-ts-intellisense.png
  docs/javascript/media/aspnet-core-ts-mvc-template.png
  docs/javascript/media/aspnet-core-ts-nuget.png
  docs/javascript/media/aspnet-core-ts-running-app.png
  docs/javascript/media/aspnet-core-ts-set-breakpoint.png
  docs/javascript/tutorial-aspnet-with-typescript.md
  docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md
  docs/python/learn-django-in-visual-studio-step-02-create-an-app.md
  docs/python/learn-flask-visual-studio-step-02-create-app.md
  mac/create-new-projects.md
Labels: do-not-merge

#4600 Fix git push error for protected CLA branch
  docs/code-quality/ca5397.md
  docs/code-quality/ca5398.md
Labels: do-not-merge

#4605 Fix git push error for protected CLA branch
  docs/ide/user-permissions-and-visual-studio.md
  docs/python/installing-python-interpreters.md
  mac/TOC.md
  mac/blazor.md
  mac/extending-visual-studio-mac.md
  mac/media/blazor-azure-publish.png
  mac/media/blazor-intellisense.gif
  mac/media/blazor-intellisense.png
  mac/media/blazor-name-project.png
  mac/media/blazor-new-app-in-edge.png
  mac/media/blazor-new-app-in-safari.png
  mac/media/blazor-new-project.png
  mac/media/blazor-project-template.png
  mac/media/blazor-select-target-framework.png
  mac/net-core-support.md
Labels: do-not-merge

#4607 Fix git push error for protected CLA branch
  docs/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template.md
  docs/test/how-to-use-microsoft-test-framework-for-cpp.md
  docs/test/writing-unit-tests-for-c-cpp.md
Labels: do-not-merge

#4610 Fix git push error for protected CLA branch
  docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md
  docs/debugger/debug-live-azure-virtual-machines.md
  docs/debugger/media/attach-process-menu.png
  docs/debugger/media/connect-remote-system.png
  docs/debugger/media/docker-attach-complete.png
  docs/debugger/media/select-docker-container.png
  docs/debugger/pseudovariables.md
  docs/ide/developer-community-privacy.md
  docs/ide/media/report-a-problem-logs-collected.png
  docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md
  docs/ide/step-2-create-a-random-addition-problem.md
  docs/ide/step-3-add-a-countdown-timer.md
  docs/ide/step-4-add-the-checktheanswer-parens-method.md
  docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md
  docs/ide/step-6-add-a-subtraction-problem.md
  docs/ide/step-7-add-multiplication-and-division-problems.md
  docs/ide/step-8-customize-the-quiz.md
  docs/install/update-a-network-installation-of-visual-studio.md
  docs/install/update-servicing-baseline.md
  docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md
Labels: do-not-merge

#4617 Fix git push error for protected CLA branch
  docs/code-quality/ca1710.md
  docs/javascript/tutorial-aspnet-with-typescript.md
Labels: do-not-merge

#4623 Update display-data-in-blend.md
  docs/xaml-tools/display-data-in-blend.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4624 Fix git push error for protected CLA branch
  docs/code-quality/code-metrics-values.md
  docs/code-quality/how-to-generate-code-metrics-data.md
  docs/xaml-tools/xaml-overview.md
  subscriptions/_img/vs-whitesource/vs-whitesource-tile.PNG
  subscriptions/vs-whitesource.md
Labels: do-not-merge

#4632 Update memory-usage.md
  docs/profiling/memory-usage.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4633 Update profiling-feature-tour.md
  docs/profiling/profiling-feature-tour.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4637 Fix git push error for protected CLA branch
  docs/code-quality/ca5358.md
  docs/code-quality/security-rules-rule-set-for-managed-code.md
  docs/code-quality/toc.yml
Labels: do-not-merge

#4639 Fix git push error for protected CLA branch
  docs/cross-platform/unity-scripting-upgrade.md
  docs/debugger/what-s-new-for-the-debugger-in-visual-studio.md
  docs/ide/visual-studio-performance-tips-and-tricks.md
  docs/vs-2015/extensibility/installing-an-isolated-shell-application.md
  docs/vs-2015/extensibility/internals/how-to-generate-registry-information-for-an-installer.md
  subscriptions/sign-in-github.md
Labels: do-not-merge

#4658 Fix git push error for protected CLA branch
  docs/ide/reference/options-text-editor-csharp-advanced.md
  docs/install/includes/install-error-codes-md.md
  docs/install/includes/install_get_support_md.md
  docs/install/includes/vs-2017/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2017/workload-component-id-vs-community.md
  docs/install/includes/vs-2017/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2017/workload-component-id-vs-express.md
  docs/install/includes/vs-2017/workload-component-id-vs-feedback-client.md
  docs/install/includes/vs-2017/workload-component-id-vs-professional.md
  docs/install/includes/vs-2017/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2017/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2017/workload-component-id-vs-test-controller.md
  docs/install/includes/vs-2017/workload-component-id-vs-test-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-controller.md
  docs/install/includes/workloads-components-header-2017_md.md
  docs/install/includes/workloads-components-header-2019_md.md
  docs/install/includes/workloads-components-universal-header_md.md
  docs/vs-2015/install/create-an-offline-installation-of-visual-studio.md
Labels: do-not-merge

#4643 Update container-launch-settings.md
  docs/containers/container-launch-settings.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-azure/tech

#4661 Fix git push error for protected CLA branch
  docs/windows/index.yml
Labels: do-not-merge

#4657 Add missing editorconfig setting value
  docs/ide/editorconfig-language-conventions.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4662 Add link to CMake-specific debugging docs
  docs/ide/customize-build-and-debug-tasks-in-visual-studio.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4674 Fix git push error for protected CLA branch
  subscriptions/program-mpn.md
Labels: do-not-merge

#4682 Correct Name Of Individual Component Cpp Core Features
  docs/debugger/how-to-start-spy-increment.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#4683 Fix git push error for protected CLA branch
  docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md
  docs/debugger/walkthrough-writing-a-visualizer-in-visual-basic.md
Labels: do-not-merge

#4679 Added missing line concatenation character
  docs/install/command-line-parameter-examples.md
Labels: assessing_(C&L), change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#4692 Fix git push error for protected CLA branch
  subscriptions/vs-azure.md
Labels: do-not-merge

#4694 Fix git push error for protected CLA branch
  docs/debugger/getting-started-with-the-debugger-cpp.md
  docs/debugger/media/vs-2019/get-started-create-console-project-cpp.png
  docs/debugger/media/vs-2019/get-started-create-console-project-vb.png
  docs/debugger/media/vs-2019/get-started-create-console-project.png
  docs/get-started/csharp/tutorial-debugger.md
  docs/get-started/visual-basic/tutorial-debugger.md
Labels: do-not-merge

#4695 Fix git push error for protected CLA branch
  docs/profiling/how-to-launch-a-stand-alone-native-application-to-collect-concurrency-data.md
Labels: do-not-merge

#4710 Resolved Issue Promote Flag #3141
  docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-ide-sdk/tech

#4716 Update allow list
  docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md
Labels: change sent to author, do-not-merge, visual-studio-windows/prod, vs-installation/tech

#4719 Fix git push error for protected CLA branch
  docs/code-quality/C26414.md
  docs/ide/reference/generate-xml-documentation-comments.md
  docs/ide/reference/media/doc-styles-cs.png
  docs/install/modify-visual-studio.md
  mac/2017/uninstall.md
  mac/uninstall.md
  subscriptions/assign-license.md
Labels: do-not-merge

#4722 Fix git push error for protected CLA branch
  docs/docfx.json
  docs/test/how-to-use-boost-test-for-cpp.md
Labels: do-not-merge

#4524 Add a note about httpclient
  docs/containers/tutorial-multicontainer.md
Labels: assessing_(C&L), change sent to author, ready-to-merge, visual-studio-windows/prod, vs-azure/tech

#4608 Update common-msbuild-project-properties.md
  docs/msbuild/common-msbuild-project-properties.md
Labels: assessing_(C&L), change sent to author, msbuild/tech, ready-to-merge, visual-studio-windows/prod
