Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2020-03, with the labels that each got.

#4874 Fix git push error for protected CLA branch
  docs/get-started/csharp/tutorial-console.md
Labels: do-not-merge

#4879 Fix git push error for protected CLA branch
  docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md
  subscriptions/vs-cast.md
Labels: do-not-merge

#4883 [debugger] Added links to intrinsic functions
  docs/debugger/expressions-in-the-debugger.md
Labels: aq-pr-triaged, change sent to author, ready-to-merge, visual-studio-windows/prod, vs-ide-debug/tech

#4888 Fix git push error for protected CLA branch
  docs/code-quality/in-source-suppression-overview.md
  docs/test/getting-started-with-unit-testing.md
  subscriptions/_img/cloud-admin/access-control-add.png
  subscriptions/_img/cloud-admin/add-role-user-access-admin.png
  subscriptions/_img/cloud-admin/azure-cost-billing.png
  subscriptions/_img/cloud-admin/subscription-list.png
  subscriptions/cloud-admin.md
Labels: do-not-merge

#4895 Fix git push error for protected CLA branch
  subscriptions/_img/connect-emails/connect-emails-button.png
  subscriptions/_img/connect-emails/connect-emails-confirm.png
  subscriptions/_img/connect-emails/connect-emails-flyout.png
  subscriptions/_img/maximum-usage/maximum-usage-full-report.png
  subscriptions/_img/maximum-usage/maximum-usage-menu.png
  subscriptions/_img/over-claimed/over-claimed-alert.png
  subscriptions/_img/search-filter/clear-filter.png
  subscriptions/_img/search-filter/filter-list.png
  subscriptions/_img/using-admin-portal/details-page.png
  subscriptions/_img/using-admin-portal/subscribers-page.png
  subscriptions/_img/volume-license/super-admin-notice-2020.png
  subscriptions/handle-overclaimed-license.md
  subscriptions/maximum-usage.md
  subscriptions/mpsa.md
  subscriptions/personal-email-sign-ins.md
  subscriptions/search-license.md
  subscriptions/using-admin-portal.md
  subscriptions/volume-license.md
Labels: do-not-merge

#4898 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/install/visual-studio-administrator-guide.md
  subscriptions/azure-ea-devtest.md
Labels: do-not-merge

#4903 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/code-quality/ca1053.md
  docs/code-quality/fxcop-analyzers-faq.md
  docs/code-quality/fxcop-analyzers.yml
  docs/code-quality/fxcop-rule-port-status.md
  docs/code-quality/install-fxcop-analyzers.md
  docs/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers.md
  docs/code-quality/toc.yml
  subscriptions/access-github.md
  subscriptions/activate-store-subscriptions.md
  subscriptions/admin-inventory.md
  subscriptions/anonymization.md
Labels: do-not-merge

#4913 Fix git push error for protected CLA branch
  docs/test/writing-unit-tests-for-c-cpp.md
  subscriptions/admin-inventory.md
  subscriptions/contact-my-admin.md
  subscriptions/download-software.md
  subscriptions/find-keys.md
  subscriptions/internet-demos.md
Labels: do-not-merge

#4916 Fix git push error for protected CLA branch
  docs/cross-platform/visual-studio-emulator-for-android.md
  docs/get-started/includes/ide-overview.md
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/visual-studio-administrator-guide.md
  subscriptions/manage-mpn-subscriptions.md
  subscriptions/manage-teams.md
  subscriptions/manage-vs-subscriptions.md
  subscriptions/open-migration.md
  subscriptions/product-availability.md
  subscriptions/product-keys.md
  subscriptions/program-mpn.md
  subscriptions/program-startups.md
  subscriptions/sign-in-github.md
Labels: do-not-merge

#4919 Fix git push error for protected CLA branch
  docs/get-started/includes/ide-overview.md
Labels: do-not-merge

#4928 Add link to recommended MSBuild Properties
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
Labels: aq-pr-triaged, change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-test/tech

#4930 Fix git push error for protected CLA branch
  docs/ide/media/vs2019_signinpopup.png
  docs/ide/media/vs2019_username.png
  docs/ide/media/vs2019_usernotsignedin.png
  docs/ide/signing-in-to-visual-studio.md
Labels: do-not-merge

#4934 Fix git push error for protected CLA branch
  docs/install/visual-studio-administrator-guide.md
Labels: do-not-merge

#4936 Fix git push error for protected CLA branch
  docs/python/media/environments/environments-add-matplotlib-2019.png
  docs/python/media/environments/environments-add-matplotlib2-2019.png
  docs/python/media/environments/environments-installed-packages-2019.png
  docs/python/media/packages-unresolved-import.png
  docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md
Labels: do-not-merge

#4937 Fix git push error for protected CLA branch
  docs/toc.yml
Labels: do-not-merge

#4653 With VS 16.5 one of Known issues is fixed
  docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md
Labels: aq-pr-triaged, change sent to author, ready-to-merge, visual-studio-windows/prod, vs-ide-general/tech

#4940 Fix git push error for protected CLA branch
  docs/ide/whats-new-visual-studio-2019.md
  docs/install/includes/vs-2019/workload-component-id-vs-build-tools.md
  docs/install/includes/vs-2019/workload-component-id-vs-community.md
  docs/install/includes/vs-2019/workload-component-id-vs-enterprise.md
  docs/install/includes/vs-2019/workload-component-id-vs-professional.md
  docs/install/includes/vs-2019/workload-component-id-vs-team-explorer.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-agent.md
  docs/install/includes/vs-2019/workload-component-id-vs-test-controller.md
  docs/install/includes/workloads-components-header-2019_md.md
  docs/install/includes/workloads-components-universal-header_md.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/install/workload-and-component-ids.md
  docs/install/workload-component-id-vs-build-tools.md
  docs/install/workload-component-id-vs-community.md
  docs/install/workload-component-id-vs-enterprise.md
  docs/install/workload-component-id-vs-professional.md
Labels: do-not-merge

#4947 Fix git push error for protected CLA branch
  docs/ide/editorconfig-code-style-settings-reference.md
  docs/install/workload-and-component-ids.md
  docs/install/workload-component-id-vs-team-explorer.md
  docs/install/workload-component-id-vs-test-agent.md
  docs/install/workload-component-id-vs-test-controller.md
  docs/install/workload-component-id-vs-test-professional.md
Labels: do-not-merge

#4951 Fix git push error for protected CLA branch
  docs/code-quality/install-fxcop-analyzers.md
  docs/debugger/decompilation.md
  docs/ide/editorconfig-code-style-settings-reference.md
  subscriptions/sign-in-issues.md
  subscriptions/sign-in-msa.md
  subscriptions/sign-in-work.md
  subscriptions/software-download-list.md
  subscriptions/use-connected-identities.md
Labels: do-not-merge

#4955 Fix git push error for protected CLA branch
  subscriptions/_img/aliasing/account-aliases.png
  subscriptions/_img/assign-license-bulk/bulk-add-upload-failure.png
  subscriptions/_img/assign-license-bulk/bulk-add-upload-success.png
  subscriptions/admin-prefs.md
  subscriptions/aliasing.md
  subscriptions/assign-github.md
  subscriptions/assign-license-bulk.md
  subscriptions/personal-email-sign-ins.md
  subscriptions/vs-azure.md
Labels: do-not-merge

#4938 Update configure-unit-tests-by-using-a-dot-runsettings-file.md
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
Labels: aq-pr-triaged, change sent to author, do-not-merge, visual-studio-windows/prod, vs-ide-test/tech

#4962 Fix git push error for protected CLA branch
  docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md
  docs/javascript/develop-javascript-code-without-solutions-projects.md
  docs/javascript/javascript-in-vs-2019.md
  docs/javascript/media/aspnet-core-ts-jquery-example.png
  docs/javascript/media/aspnet-core-ts-jquery-intellisense.png
  docs/javascript/media/npm-add-package-intellisense.png
  docs/javascript/media/npm-add-package-json.png
  docs/javascript/media/npm-add-package.png
  docs/javascript/media/npm-output.png
  docs/javascript/npm-package-management.md
  docs/javascript/tutorial-aspnet-with-typescript.md
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
  docs/profiling/beginners-guide-to-performance-profiling.md
  docs/profiling/index.yml
  docs/profiling/media/diag-tools-perftips.png
  docs/profiling/profiling-feature-tour.md
  docs/profiling/quickstart-cpu-usage-aspnet.md
  docs/profiling/quickstart-cpu-usage-managed.md
  docs/profiling/quickstart-cpu-usage-native.md
  docs/profiling/toc.yml
  docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md
  mac/TOC.md
  mac/TOC.yml
  mac/context.yml
  subscriptions/personal-email-sign-ins.md
  subscriptions/vs-azure-payg.md
Labels: do-not-merge

#4978 Fix git push error for protected CLA branch
  docs/cross-platform/application-lifecycle-management-alm-with-unity-apps.md
  docs/cross-platform/change-log-visual-studio-tools-for-unity-mac.md
  docs/cross-platform/change-log-visual-studio-tools-for-unity.md
  docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md
  docs/debugger/media/attach-process-menu-docker-windows.png
  docs/debugger/media/docker-attach-complete-windows.png
  docs/ide/quickstart-personalize-the-ide.md
  docs/ide/reference/task-list-environment-options-dialog-box.md
  docs/install/includes/install_get_support_md.md
  docs/install/troubleshooting-installation-issues.md
  docs/javascript/javascript-in-vs-2017.md
  docs/profiling/analyze-memory-usage.md
  docs/profiling/profiling-feature-tour.md
  docs/vs-2015/cross-platform/application-lifecycle-management-alm-with-unity-apps.md
  subscriptions/access-github.md
  subscriptions/activate-store-subscriptions.md
  subscriptions/admin-inventory.md
  subscriptions/admin-responsibilities.md
  subscriptions/admin-roles.md
  subscriptions/anonymization.md
  subscriptions/assign-license.md
  subscriptions/assignments-orders.md
  subscriptions/azure-ea-devtest.md
  subscriptions/cloud-admin.md
  subscriptions/contact-my-admin.md
  subscriptions/delete-license.md
  subscriptions/download-software.md
  subscriptions/edit-license.md
  subscriptions/exporting-subscriptions.md
  subscriptions/find-keys.md
  subscriptions/handle-expired-license.md
  subscriptions/handle-overclaimed-license.md
  subscriptions/internet-demos.md
  subscriptions/manage-mpn-subscriptions.md
  subscriptions/manage-teams.md
  subscriptions/manage-vs-subscriptions.md
  subscriptions/maximum-usage.md
  subscriptions/mpsa.md
  subscriptions/open-migration.md
  subscriptions/product-availability.md
  subscriptions/product-keys.md
  subscriptions/program-mpn.md
  subscriptions/program-startups.md
  subscriptions/search-license.md
  subscriptions/sign-in-github.md
  subscriptions/sign-in-issues.md
  subscriptions/sign-in-msa.md
  subscriptions/sign-in-work.md
  subscriptions/software-download-list.md
  subscriptions/use-connected-identities.md
  subscriptions/using-admin-portal.md
  subscriptions/using-the-subscriber-portal.md
  subscriptions/volume-license.md
  subscriptions/vs-alternate-identity.md
  subscriptions/vs-azure-community.md
  subscriptions/vs-azure-devops.md
  subscriptions/vs-azure-payg.md
  subscriptions/vs-azure.md
Labels: do-not-merge

#4980 Update VS build numbers and release dates
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: aq-pr-triaged, change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech

#4983 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  docs/_breadcrumb/toc.yml
  docs/profiling/memory-usage-without-debugging2.md
  docs/profiling/memory-usage.md
  docs/test/improve-code-quality.md
  docs/test/index.yml
  docs/test/intellitest-manual/getting-started.md
  docs/test/intellitest-manual/index.md
  docs/test/intellitest-manual/introduction.md
  docs/test/toc.yml
Labels: do-not-merge

#4998 Fix git push error for protected CLA branch
  docs/install/advanced-build-tools-container.md
  docs/install/build-tools-container.md
  scripting-docs/index.md
  subscriptions/assign-license-bulk.md
  subscriptions/vs-cast.md
  subscriptions/vs-cloudpilot.md
  subscriptions/vs-code-magazine.md
  subscriptions/vs-concierge-chat.md
  subscriptions/vs-datacamp.md
  subscriptions/vs-ems.md
  subscriptions/vs-ide-benefit.md
  subscriptions/vs-linkedin-learning.md
  subscriptions/vs-m365.md
  subscriptions/vscloud-billing-faq.md
  subscriptions/vscloud-csp.md
  subscriptions/vscloud-overview.md
Labels: do-not-merge

#5001 Fix git push error for protected CLA branch
  subscriptions/_img/whats-new/new-admin-ui.png
  subscriptions/vs-office365.md
  subscriptions/vs-parasoft.md
  subscriptions/vs-pbi.md
  subscriptions/vs-pluralsight.md
  subscriptions/vs-tech-support.md
  subscriptions/vs-visual-studio-app-center.md
  subscriptions/vs-whitesource.md
  subscriptions/vs-windows-dev.md
  subscriptions/whats-new-in-subscriptions.md
Labels: do-not-merge

#5003 Typo fix
  docs/javascript/tutorial-nodejs.md
Labels: aq-pr-triaged, change sent to author, ready-to-merge, visual-studio-windows/prod, vs-javascript/tech

#5004 Fix git push error for protected CLA branch
  docs/install/visual-studio-build-numbers-and-release-dates.md
Labels: do-not-merge

#4946 Remove TfsPublisher from docs
  docs/test/vstest-console-options.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-ide-test/tech

#5039 Fix git push error for protected CLA branch
  docs/deployment/deploying-clickonce-applications-for-testing-and-production-without-resigning.md
  docs/extensibility/the-structure-of-the-content-types-dot-xml-file.md
  docs/ide/reference/convert-between-auto-property-and-full-property.md
  docs/ide/reference/media/convert-auto-property-to-full-property.png
  docs/ide/reference/media/convert-full-property-to-auto-property.png
  docs/toc.yml
  docs/vs-2015/deployment/deploying-clickonce-applications-for-testing-and-production-servers-without-resigning.md
  docs/vs-2015/extensibility/the-structure-of-the-content-types-dot-xml-file.md
  docs/vs-2015/workflow-designer/receive-activity-designer.md
  docs/vs-2015/workflow-designer/receiveandsendreply-template-designer.md
  docs/vs-2015/workflow-designer/send-activity-designer.md
  docs/vs-2015/workflow-designer/sendandreceivereply-template-designer.md
  docs/workflow-designer/receiveandsendreply-template-designer.md
  docs/workflow-designer/send-activity-designer.md
  docs/workflow-designer/sendandreceivereply-template-designer.md
Labels: do-not-merge

#5041 Fix git push error for protected CLA branch
  docs/ide/reference/add-explicit-cast.md
  docs/ide/reference/media/add-explicit-cast.png
  docs/profiling/beginners-guide-to-performance-profiling.md
  docs/profiling/media/diag-tools-perftips.png
  docs/profiling/profiling-feature-tour.md
  docs/profiling/quickstart-cpu-usage-aspnet.md
  docs/profiling/quickstart-cpu-usage-managed.md
  docs/profiling/quickstart-cpu-usage-native.md
  docs/toc.yml
Labels: do-not-merge

#5042 Fix git push error for protected CLA branch
  docs/ide/walkthrough-creating-a-code-snippet.md
Labels: do-not-merge

#5024 string comparison is case insensitive
  docs/msbuild/msbuild-conditions.md
Labels: aq-pr-triaged, change sent to author, do-not-merge, msbuild/tech, visual-studio-windows/prod
