Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2022-07, with the labels that each got.

#8229 Repo sync for protected CLA branch
  docs/debugger/autos-and-locals-windows.md
  docs/debugger/media/vs-2022/autos-cplus.png
  docs/debugger/media/vs-2022/autos-csharp.png
  docs/debugger/media/vs-2022/autos-return-value-csharp-2.png
  docs/debugger/media/vs-2022/debug-location-toolbar.png
  docs/debugger/media/vs-2022/ee-search-locals.png
  docs/debugger/media/vs-2022/locals-filestream.png
  docs/deployment/deploying-applications-services-and-components-resources.md
  docs/ide/customizing-window-layouts-in-visual-studio.md
  docs/ide/quickstart-personalize-the-ide.md
  docs/ide/reference/accessibility-tips-and-tricks.md
  docs/ide/troubleshooting-broken-references.md
  docs/ide/visual-studio-search.md
Labels: do-not-merge, change sent to author, visual-studio-windows/prod, vs-ide-general/tech, CLA

#8232 Repo sync for protected CLA branch
  docker/tutorials/docker-tutorial.md
  docs/extensibility/support-for-the-visual-studio-sdk.md
Labels: do-not-merge, change sent to author, vs-ide-sdk/tech, CLA, vs-code/prod

#8239 Repo sync for protected CLA branch
  subscriptions/manage-vs-subscriptions.md
  subscriptions/sign-in-msa.md
  subscriptions/sign-in-work.md
  subscriptions/using-admin-portal.md
  subscriptions/using-the-subscriber-portal.md
Labels: do-not-merge, CLA

#8245 Repo sync for protected CLA branch
  docs/designers/walkthrough-windows-forms-designer.md
  subscriptions/_img/add-monthly-subs/subs-added-confirmation.png
  subscriptions/about-benefits.md
  subscriptions/access-github.md
  subscriptions/account-removed.md
  subscriptions/add-monthly-subs.md
  subscriptions/admin-expiration.md
  subscriptions/admin-inventory.md
  subscriptions/faq/subscriber/azure/index.md
Labels: do-not-merge, change sent to author, visual-studio-family/prod, vs-ide-designers/tech, CLA

#8249 Repo sync for protected CLA branch
  docs/ide/reference/options-windows-forms-designer.md
  docs/ide/whats-new-visual-studio-2022.md
  subscriptions/admin-preferences.md
  subscriptions/admin-responsibilities.md
  subscriptions/admin-roles.md
  subscriptions/agreement-renewals.md
  subscriptions/aliasing.md
Labels: do-not-merge, change sent to author, vs-subscriptions/tech, CLA, visual-studio-dev17/prod

#8252 Repo sync for protected CLA branch
  docs/debugger/configure-firewall-for-remote-debugging-dialog-box.md
  docs/debugger/configure-the-windows-firewall-for-remote-debugging.md
  docs/debugger/remote-debugger-port-assignments.md
  docs/ide/quickstart-personalize-the-ide.md
Labels: do-not-merge, change sent to author, visual-studio-windows/prod, vs-ide-general/tech, CLA

#8256 Update toc.yml (Typo "GitHub actions"→"GitHub Actions")
  docs/azure/toc.yml
Labels: do-not-merge, review-team-triage, needs-human-review

#8257 Repo sync for protected CLA branch
  docs/version-control/index.yml
  docs/xaml-tools/draw-shapes-and-paths.md
  subscriptions/contact-my-admin.md
  subscriptions/delete-license.md
  subscriptions/download-software.md
  subscriptions/edit-license.md
  subscriptions/exporting-subscriptions.md
  subscriptions/find-keys.md
  subscriptions/handle-expired-license.md
  subscriptions/handle-overclaimed-license.md
  subscriptions/internet-demos.md
  subscriptions/manage-mpn-subscriptions.md
Labels: do-not-merge, CLA

#8258 Repo sync for protected CLA branch
  subscriptions/manage-teams.md
  subscriptions/maximum-usage.md
  subscriptions/microsoft-365-apps-for-enterprise.md
  subscriptions/migrate-subscriptions.md
  subscriptions/mpsa.md
Labels: do-not-merge, CLA

#8265 Repo sync for protected CLA branch
  docs/ide/productivity-shortcuts.md
Labels: do-not-merge, CLA

#8271 Repo sync for protected CLA branch
  subscriptions/subscription-expiration.md
  subscriptions/subscription-level-changes.md
  subscriptions/subscription-removed.md
  subscriptions/use-connected-identities.md
  subscriptions/using-admin-portal.md
  subscriptions/using-the-subscriber-portal.md
Labels: do-not-merge, change sent to author, visual-studio-family/prod, vs-subscriptions/tech, CLA

#8233 MSBuild: UsingTasks are first-one-wins
  docs/msbuild/how-to-configure-targets-and-tasks.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, msbuild/tech, aq-pr-triaged, qualifies-for-auto-merge

#8273 Repo sync for protected CLA branch
  docs/debugger/remote-debugger-port-assignments.md
  docs/profiling/index.yml
Labels: do-not-merge, CLA

#8254 Typo "GitHub Action"→"GitHub Actions"
  docs/azure/overview-github-actions.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-azure/tech, aq-pr-triaged, qualifies-for-auto-merge

#8277 Repo sync for protected CLA branch
  docs/debugger/project-settings-for-csharp-debug-configurations-dotnetcore.md
Labels: do-not-merge, CLA

#8281 Repo sync for protected CLA branch
  .openpublishing.redirection.json
  docs/ide/media/vs-2022/attach-to-process.png
  docs/ide/report-a-problem-perfview-minidumps.md
  docs/ide/user-permissions-and-visual-studio.md
  docs/vsto/deploying-an-office-solution-by-using-windows-installer.md
  docs/vsto/how-to-programmatically-associate-a-web-page-with-an-outlook-folder.md
  docs/vsto/how-to-programmatically-save-workbooks.md
  docs/vsto/media/installshield-applicationfiles.png
  docs/vsto/media/installshield-applicationregistry.gif
  docs/vsto/media/installshield-outputfiles.png
  docs/vsto/media/installshield-projectassistant.png
  docs/vsto/media/installshield-redistributablesfile.png
  docs/vsto/media/installshield-refreshbutton.png
  docs/vsto/toc.yml
  subscriptions/_img/vs-cast-highlight/vs-cast-highlight-landing.png
  subscriptions/_img/vs-cast-highlight/vs-cast-highlight-tile.png
  subscriptions/toc.yml
  subscriptions/vs-cast.md
Labels: do-not-merge, CLA

#8111 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#8290 Repo sync for protected CLA branch
  docs/profiling/cpu-usage.md
  docs/test/includes/coded-ui-test-deprecation.md
Labels: do-not-merge, CLA

#8293 Repo sync for protected CLA branch
  subscriptions/volume-license.md
  subscriptions/vs-alternate-identity.md
  subscriptions/vs-azure-community.md
  subscriptions/vs-azure-devops.md
  subscriptions/vs-azure-eligibility.md
  subscriptions/vscloud-billing-faq.yml
  subscriptions/vscloud-csp.md
Labels: do-not-merge, CLA

#8205 Fix API typo
  docs/extensibility/toc.yml
  docs/extensibility/vssdk-messages/index.md
Labels: do-not-merge, change sent to author, visual-studio-windows/prod, vs-ide-sdk/tech, aq-pr-triaged, needs-human-review

#8158 Update set-defaults-for-enterprise-deployments.md
  docs/install/set-defaults-for-enterprise-deployments.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech, aq-pr-triaged, qualifies-for-auto-merge

#8197 Update set-defaults-for-enterprise-deployments.md
  docs/install/set-defaults-for-enterprise-deployments.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech, aq-pr-triaged, qualifies-for-auto-merge

#8219 Updating the blog link
  docs/install/visual-studio-on-arm-devices.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, vs-installation/tech, aq-pr-triaged, qualifies-for-auto-merge

#8297 Typo "GitHub Action workflows"→"GitHub Actions workflows"
  docs/deployment/deploying-applications-services-and-components.md
Labels: change sent to author, ready-to-merge, vs-ide-deployment/tech, qualifies-for-auto-merge

#8300 Repo sync for protected CLA branch
  mac/TOC.yml
  mac/installation.md
  mac/media/set-up-git-repository/version-control-git-14-2022.png
  mac/media/set-up-git-repository/version-control-git-clone.png
  mac/media/working-with-git/version-control-commit-push-2022.png
  mac/media/working-with-git/version-control-git-branch-name-2022.png
  mac/media/working-with-git/version-control-git-changes-window.png
  mac/media/working-with-git/version-control-git-commit-message.png
  mac/media/working-with-git/version-control-git-file-version-compare.png
  mac/media/working-with-git/version-control-git-menu-2022.png
  mac/media/working-with-git/version-control-git-version-control-menu-2022.png
  mac/set-up-git-repository.md
  mac/set-up-subversion-repository.md
  mac/task-comments.md
  mac/version-control.md
  mac/working-with-git-2019.md
  mac/working-with-git.md
  mac/working-with-subversion.md
Labels: do-not-merge, CLA

#8304 Repo sync for protected CLA branch
  docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer.md
  docs/get-started/media/docs-programming-language-control.png
Labels: do-not-merge, change sent to author, visual-studio-windows/prod, vs-ide-general/tech, CLA

#8306 Repo sync for protected CLA branch
  docs/ide/reference/media/vs-2022/tools-options-text-editor-general.png
  docs/ide/reference/options-text-editor-general.md
  docs/ide/reference/property-pages-javascript-esproj.md
  docs/install/media/vs-2022/capture-vm.png
  docs/install/using-visual-studio-vm.md
  docs/install/visual-studio-build-numbers-and-release-dates.md
  docs/javascript/TOC.yml
  docs/javascript/compile-typescript-code-npm.md
  docs/javascript/create-application-with-vuejs.md
  docs/javascript/debug-nodejs.md
  docs/javascript/quickstart-vuejs-with-nodejs.md
  docs/javascript/tutorial-create-angular-app.md
  docs/javascript/tutorial-create-react-app.md
  docs/javascript/tutorial-create-vue-app.md
  docs/toc.yml
Labels: do-not-merge, CLA

#8308 Repo sync for protected CLA branch
  docs/ide/whats-new-visual-studio-docs.md
Labels: do-not-merge, CLA

#8318 Repo sync for protected CLA branch
  .openpublishing.redirection.json
  docs/debugger/media/vs-2022/dbg-ienumerable-debugger-visualizer.png
  docs/debugger/media/vs-2022/dbg-ienumerable-visualizer-data.png
  docs/debugger/media/vs-2022/dbg-ienumerable-visualizer-filtering.gif
  docs/debugger/toc.yml
  docs/debugger/view-data-ienumerable-table-visualizer.md
  docs/debugger/view-data-in-ienumerable-visualizer.md
  docs/ide/whats-new-visual-studio-docs.md
Labels: do-not-merge, CLA

#8294 Update tutorial-custom-task-code-generation.md
  docs/msbuild/tutorial-custom-task-code-generation.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, msbuild/tech, aq-pr-triaged, qualifies-for-auto-merge

#8296 Update multitooltask-task.md
  docs/msbuild/multitooltask-task.md
Labels: change sent to author, ready-to-merge, visual-studio-windows/prod, aq-pr-triaged, qualifies-for-auto-merge
