Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2025-05, with the labels that each got.

#10748 Fix typo: paramter -> parameter
  docs/debugger/debug-interface-access/idiadatasource-loaddatafromcodeviewinfo.md
  docs/debugger/debug-interface-access/idiadatasource-loaddatafrommiscinfo.md
Labels: do-not-merge, change sent to author, visual-studio-windows/svc, debug-diagnostics/subsvc

#10744 Update live-unit-testing.md - fixed casing in .lutignore samples.
  docs/test/live-unit-testing.md
Labels: change sent to author, ready-to-merge, aq-pr-triaged, visual-studio-windows/svc, test-tools/subsvc

#10757 Fix typo in copilot-agent-mode.md
  docs/ide/copilot-agent-mode.md
Labels: do-not-merge, change sent to author, visual-studio-windows/svc, ai-tools/subsvc

#10768 Fix typo: highlighed -> highlighted
  subscriptions/assign-license-bulk.md
Labels: do-not-merge, change sent to author, visual-studio-family/svc, subscriptions/subsvc

#10769 Fix typo: charater -> character
  docs/snippets/cpp/VS_Snippets_Misc/system.net.httpwebrequest.addrange/cpp/source.cpp
  docs/snippets/cpp/VS_Snippets_Misc/system.net.httpwebrequest.addrange2/cpp/source.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10771 Fix typo: Alphabeticaly -> Alphabetically
  docs/snippets/cpp/VS_Snippets_Misc/NVC_MFC_Misc/cpp/Misc.rc
  docs/snippets/cpp/VS_Snippets_Misc/NVC_MFC_VisualStudioDemo/cpp/VisualStudioDemo.rc
Labels: do-not-merge, review-team-triage, needs-human-review

#10774 Fix typo: orginal -> original
  docs/debugger/debug-interface-access/idiainputassemblyfile-get-filename.md
  docs/debugger/debug-interface-access/idiainputassemblyfile-get-version.md
  docs/debugger/debug-interface-access/idiainputassemblyfile.md
  docs/snippets/cpp/VS_Snippets_Misc/NVC_MFC_WordPad/cpp/wordpdoc.cpp
  docs/snippets/cpp/VS_Snippets_Winforms/DataGridTableStyle_ResetGridLineColor/CPP/datagridtablestyle_resetgridlinecolor.cpp
Labels: do-not-merge, change sent to author, needs-human-review, visual-studio-windows/svc, debug-diagnostics/subsvc

#10773 Fix typo: Delcaration -> Declaration
  docs/snippets/cpp/VS_Snippets_Misc/cx_partial/cpp/class1.h
Labels: do-not-merge, review-team-triage, needs-human-review

#10775 Fix typo: properites -> properties
  docs/vsto/codesnippet/CSharp/Trin_RibbonButtons/Trin_RibbonButtons.csproj
  docs/vsto/codesnippet/CSharp/Trin_RibbonOutlookBasic/Trin_RibbonOutlookBasic.csproj
  docs/vsto/codesnippet/CSharp/Trin_VstcoreOutlookSecurity/Trin_VstcoreOutlookSecurity.csproj
  docs/vsto/codesnippet/VisualBasic/Trin_RibbonButtons/Trin_RibbonButtons.vbproj
  docs/vsto/codesnippet/VisualBasic/Trin_RibbonOutlookBasic/Trin_RibbonOutlookBasic.vbproj
  docs/vsto/codesnippet/VisualBasic/Trin_VstcoreOutlookSecurity/Trin_VstcoreOutlookSecurity.vbproj
Labels: do-not-merge, review-team-triage, needs-human-review
