Repository MicrosoftDocs/visualstudio-docs, pull requests merged in 2025-07, with the labels that each got.

#10923 Fix typo: idetified -> identified
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.AccessibleObject/CPP/chartcontrol.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10927 Fix typo: symetrical -> symmetrical
  docs/snippets/cpp/VS_Snippets_Winforms/System.Drawing.Drawing2D.ClassicGraphicsPathExamples/CPP/form1.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10926 Fix typo: Initalize -> Initialize
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.ComboBoxSelectedText/CPP/form1.cpp
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.MenuItemMergeOrder/CPP/form1.cpp
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.NotifyIconExample/CPP/form1.cpp
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.TrackBarExample/CPP/form1.cpp
  docs/snippets/cpp/VS_Snippets_Winforms/System.Windows.Forms.TreeViewAndPrintPreview/CPP/form1.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10928 Fix typo: Sring -> String
  docs/snippets/cpp/VS_Snippets_Winforms/ComboBox/CPP/comboboxcomplex.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10930 Fix typo: releated -> related
  docs/snippets/cpp/VS_Snippets_Winforms/Control_StyleChanged/CPP/control_stylechanged.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10931 Fix typo: coloumns -> columns
  docs/snippets/cpp/VS_Snippets_Winforms/DataGridTableStyle_Header_4/CPP/datagridtablestyle_header_4.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10938 Fix typo: adminstrator -> administrator
  docs/snippets/cpp/VS_Snippets_Winforms/Classic Application.ThreadException Example/CPP/source.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10935 Fix typo: combinateion -> combination
  docs/snippets/cpp/VS_Snippets_Winforms/MeasureItemEventArgs/CPP/form1.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10937 Fix typo: propery -> property
  docs/snippets/cpp/VS_Snippets_Winforms/PropertyTabExample/CPP/class1.cpp
Labels: do-not-merge, review-team-triage, needs-human-review

#10942 Fix typo: caller/calle -> caller/callee
  docs/debugger/debug-interface-access/idiasymbol-get-pgoedgecount.md
Labels: do-not-merge, change sent to author, visual-studio-windows/svc, debug-diagnostics/subsvc

#10941 Fix typo: Autio -> Audio
  docs/profiling/cpu-insights.md
Labels: do-not-merge, change sent to author, visual-studio-windows/svc, debug-diagnostics/subsvc

#10945 Correct application patterns for visual studio
  docs/extensibility/ux-guidelines/application-patterns-for-visual-studio.md
Labels: do-not-merge, change sent to author, aq-pr-triaged, visual-studio-windows/svc, extensibility-integration/subsvc

#10951 Add -bl placeholder docs and example
  docs/msbuild/msbuild-command-line-reference.md
Labels: do-not-merge, change sent to author, aq-pr-triaged, visual-studio-windows/svc, msbuild/subsvc

#10971 Remove some redundant, confusing language.
  docs/debugger/using-the-debuggerdisplay-attribute.md
Labels: change sent to author, ready-to-merge, aq-pr-triaged, visual-studio-windows/svc, debug-diagnostics/subsvc
